### ISSUE TITLE
Uneven plot dimensions in Bokeh Gridmatrix

### ISSUE THREAD

**Issue by mrksr** [pyviz/holoviews#1025]
When changing the plot dimensions in a bokeh `GridMatrix`, the first column and last row behave different to the rest of the plot. This happens both when the size of the inner plots is adjusted using `%%opts Scatter Histogram [width=100 height=100]`...
![Resized GridMatrix](https://i.imgur.com/5kC7XLj.png)

... or when the whole plot is resized using `%%output size=150`:
![Resized GridMatrix](https://i.imgur.com/nF3T2ZY.png)

**Comment by philippjfr** [comment]
This is now fixed since we use frame_width and frame_height.
