### ISSUE TITLE
option for re-flow of a layout for each frame

### ISSUE THREAD

**Issue by RafalSkolasinski** [pyviz/holoviews#1113]
It would be nice feature to let holomap to respect aspect of each figure inside it,

for example
```
%%opts Raster (cmap='viridis' interpolation='nearest') [aspect='equal' colorbar=True]
hv.HoloMap(plot_data, kdims=['L', 'W''])
```

creates holomap that every frame has same aspect, even when each element of ``plot_data`` got different one, i.e. these are different rectangulars.

**Comment by philippjfr** [comment]
For a quick bit of background, currently HoloViews computes the layout of the matplotlib canvas once and then retains that layout (i.e. the positions and dimensions of each axis) throughout the animation. This has the nice property of stopping axes jumping or jittering around. We could add an option to control whether the Layout is recomputed on each frame, which will cause axes to jitter but will also allow changing aspect ratios for each plot over the course of the animation.

**Comment by philippjfr** [comment]
Thinking about this again I think if you want completely new layout reorganizations you should simply recreate the plot in its entirety. When using [panel](https://github.com/pyviz/panel) this is already possible.
