### ISSUE TITLE
Dimension.type should determine axis types

### ISSUE THREAD

**Issue by philippjfr** [pyviz/holoviews#1312]
Currently the plotting code figures out the axis types based on the types of the data itself, this generally works well but there's some cases where you might want define a length zero element and still guarantee that the axis is initialized correctly. In this case it would be easiest if the axis code also looked at the declared ``Dimension.type``.

**Comment by jlstevens** [comment]
Agreed, that would make sense.

**Comment by philippjfr** [comment]
This has been implemented.
