### ISSUE TITLE
Redisplaying objects with LinkedStreams

### ISSUE THREAD

**Issue by philippjfr** [pyviz/holoviews#1345]
Since streams are linked to specific objects, redisplaying the same object multiple times will link the different plots together. If we were to simply unlink the source on the object by making an unlinked clone a user can avoid this problem but the unlinked object will no longer respond to updates from the new (or old) plot. Alternatively you could simply reset the subscribers on the linked streams, which has the opposite problem in that the old plot will no longer respond to interactions. What is really needed to make an object completely unlinked while still responding dynamically to updates on the new plot. This would require an easy way to make a deep clone of an object, where all LinkedStream instances are replaced with new instances.

**Comment by jlstevens** [comment]
Is this related to the issue about pushing data to cells that might be deleted by the user?

**Comment by philippjfr** [comment]
I no longer think this should have any special API, the simpler solution is just to tell people to create a new object.
