### ISSUE TITLE
Documentation for using datashader in HoloViews

### ISSUE THREAD

**Issue by jbednar** [pyviz/holoviews#1423]
Would be nice to address some of the problems listed here:

https://github.com/bokeh/datashader/issues/237

**Comment by philippjfr** [comment]
@jbednar Would you consider that this has been addressed with the user guide?

**Comment by jbednar** [comment]
In general, yes, though I'm not sure about the specific issue raised in https://github.com/bokeh/datashader/issues/237 .

**Comment by philippjfr** [comment]
Closing this, if we want improved documentation that should become a more specific issue.
