### ISSUE TITLE
Document, rename or remove the Aliases utility

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#1427]
I think this utility is still useful, even if it might now be misnamed. Example usage:

```
>>> import holoviews as hv
>>> al = hv.util.Aliases(name1='Long label', name2='Long label 2')
>>> al.name1
('name1', 'Long label')
```

It can be useful for defining all your dimension tuples at the top of the notebook instead of repeating such tuples. I believe it can also accept fully-fledged dimension objects.

**Comment by jlstevens** [comment]
@jbednar I really would like a solution to this and I do feel such a utility would be really helpful, especially for more elaborate examples and bigger projects.

Implementing something here is easy, the problem is deciding what to implement. I'll leave this issue on the 1.8 milestone in case you have any new suggestions otherwise I will remove that milestone.

**Comment by philippjfr** [comment]
I'm still -1 on having the alias object, but won't object if you insist, but I would like to see this and the corresponding PR closed on this release as this has dragged out a long time now.

**Comment by philippjfr** [comment]
The issue does correctly suggest that if we're not going to improve aliases we should delete the current implementation, which is what I'd vote for.
