### ISSUE TITLE
Organize assets.holoviews.org properly

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#1553]
Currently this S3 bucket is a bit of a mess. In particular, I'll be adding gifs to the ``/gifs`` directory but this currently contains gifs for the linked streams examples. Those gifs should be moved into an appropriate folder, maybe mirroring ``/examples/streams/bokeh``where the notebooks are.

**Comment by jlstevens** [comment]
I've fixed this now. @philippjfr Any other clean up you want on S3? If not, I'll close this issue.

**Comment by jlstevens** [comment]
Some of this has been done now. Maybe it is ready to be closed? Assigning to 1.8.1.

**Comment by philippjfr** [comment]
Definitely think this can be closed.
