### ISSUE TITLE
Test numpy and pandas utilities against each other

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#1666]
We have a number of utilities that use pandas when available but fall back to numpy when pandas is not available. As we only have numpy as a core dependency (but as devs we almost always have pandas installed), I would be happier if we had some unit tests to compare these implementations against each other to make sure the numpy version keeps working as expected.

**Comment by jlstevens** [comment]
In issue #1911, Philipp mentions that the two things that need to be tested are ``util.unique_array`` and ``util.groupby``. I've assigned this issue to the 1.9 milestone.

**Comment by philippjfr** [comment]
We now run the test suite in a reduced dependency environment and both functions are tested independently.
