### ISSUE TITLE
x axis extent issue when overlay is done

### ISSUE THREAD

**Issue by shaginhekvs** [pyviz/holoviews#1744]
I have written the code below to do 2 things 
1. methogh get_view: dynamically change number of timestamp curves being plotted as NDoverlay by using dynamicmap and then datashade since data points are huge . the axis has been formatted with datetimeformatter 
2. get_view_label : add label since datashade cannot add labels
I have followed the steps as below: 
[http://holoviews.org/user_guide/Large_Data.html](url)

**Problem 1** is when the labels are overlaid plot1 * plot2 in show_plot, the x axis range of plot1 in show_plot is completely lost as can be seen below : 
![2017-07-22](https://user-images.githubusercontent.com/26320110/28488505-261fb7e0-6ede-11e7-9167-61cea1b12431.png)

however, when only plot1 is plotted, the x axis range is completely fine. 
![2017-07-22 1](https://user-images.githubusercontent.com/26320110/28488508-2fc62c20-6ede-11e7-9b21-77eb3c924930.png)

**Problem 2** is that the color mapping of data: when i use box zoom to zoom into the overlaid plot, the default color map is not what is used by datashade or maybe i'm missing something. How can i make the plot and the labels have the same color mapping in this case ? 
![2017-07-22 2](https://user-images.githubusercontent.com/26320110/28488510-35a1a4a8-6ede-11e7-92bb-69d8a2720ff0.png)

     
     def get_view(self,**params):
          self.set_plotted_data_dict(False,False)
          curves_dict={}
          count=0
          color_points={}
          curves_nd_ovrly=hv.NdOverlay([])
          labels_nd_ovrly=hv.NdOverlay([])
          for key,value in self.plotted_data_dict.items():
               for name,df in value.items():
                    if(len(df)==0):
                         continue
                    list_cols=df.columns.values.tolist()
                    dfs_list=[]
                    df['date'] = df.index.astype('datetime64[ns]').values.astype('int64')/10**6
                    for col in list_cols:
                         dfs_list.append(df[['date',col]])
                    for df_single_col in dfs_list:
                         #print(df_single_col.head())
                         col_name=df_single_col.columns.values.tolist()
                         col_name.remove('date')
                         col_name=col_name[0]
                         #print('{} is problem'.format(col_name))
                         curves_dict[name+'_'+col_name]=hv.Curve(df_single_col, kdims=[('date', 'Date')],\
                               vdims=[hv.Dimension(col_name, label=self.plot_pol,unit=plotting_options_units[self.plot_pol] )]).opts(options={'Curve':{'style':dict(color=Sets1to3[count]),'norm':dict(framewise=True),'plot':dict(tools=['box_select','resize'],finalize_hooks=[apply_formatter],legend_limit=0)}})
                         count+=1
                    curves_nd_ovrly=hv.NdOverlay(curves_dict,kdims=['k'])
          return curves_nd_ovrly
     def get_view_label(self,**params):
          self.set_plotted_data_dict(False,False)
          curves_dict={}
          count=0
          color_points={}
          curves_nd_ovrly=hv.NdOverlay([])
          labels_nd_ovrly=hv.NdOverlay([])
          for key,value in self.plotted_data_dict.items():
               for name,df in value.items():
                    if(len(df)==0):
                         continue
                    list_cols=df.columns.values.tolist()
                    dfs_list=[]
                    df['date'] = df.index.astype('datetime64[ns]').values.astype('int64')/10**6
                    date_1=df['date'].iloc[0]
                    for col in list_cols:
                         dfs_list.append(df[['date',col]])
                    for df_single_col in dfs_list:
                         #print(df_single_col.head())
                         col_name=df_single_col.columns.values.tolist()
                         col_name.remove('date')
                         pol_name=col_name[0]
                         col_name=col_name[0]
                         
                         #print('{} is problem'.format(col_name))
                         curves_dict[name+'_'+col_name]=hv.Curve(df_single_col, kdims=[('date', 'Date')],\
                               vdims=[hv.Dimension(col_name, label=self.plot_pol,unit=plotting_options_units[self.plot_pol] )]).opts(options={'Curve':{'style':dict(color=Sets1to3[count]),'norm':dict(framewise=True),'plot':dict(tools=['box_select','resize'],finalize_hooks=[apply_formatter],legend_limit=0)}})
                         if(pol_name!='date'):color_points[name+'_'+pol_name]=hv.Points([0,0],label=name+'_'+pol_name).opts(options={'Points':{'style':dict(color=Sets1to3[count]),'plot':dict(tools=['box_select','resize'],legend_limit=0)}})
                         count+=1
                    curves_nd_ovrly=hv.NdOverlay(curves_dict,kdims=['k'])
                    labels_nd_ovrly=hv.NdOverlay(color_points,kdims=['k'])
          return labels_nd_ovrly
     
     
     def show_plot(self): 
          plot1=dynspread(datashade(hv.DynamicMap(self.get_view,kdims=[],streams=[self,hv.streams.RangeXY(transient=True)]),width=1500,height=300,streams=[self,hv.streams.RangeXY(transient=True)],aggregator=ds.count_cat('k')).opts(options={'RGB':{'norm':dict(framewise=True),'plot': dict(width=1200, height=300,tools=['box_select','resize'],finalize_hooks=[apply_formatter])}}))
          #plot1=hv.DynamicMap(self.get_view,kdims=[],streams=[self,hv.streams.RangeXY(transient=True)]).opts(options={'RGB':{'norm':dict(framewise=True),'plot': dict(width=1200, height=300,tools=['box_select','resize'],finalize_hooks=[apply_formatter])}})
          
          plot2=hv.DynamicMap(self.get_view_label,kdims=[],streams=[self]).opts(options={'Points':{'norm':dict(framewise=True),'plot': dict(width=1200, height=300,tools=['box_select','resize'],finalize_hooks=[apply_formatter])}})
          
          #return plot1*plot2
          return plot1

**Comment by jlstevens** [comment]
Thanks for reporting this!

Tackling the first problem you mentioned: could you show me what plot2 looks like by itself?

**Comment by shaginhekvs** [comment]
@jlstevens sorry, i meant the first plot is for plot1* plot2 , not plot1 + plot2 , so I haven't plotted it separately.

**Comment by shaginhekvs** [comment]
![2017-07-22 3](https://user-images.githubusercontent.com/26320110/28492088-e9489192-6f2e-11e7-9a97-382357679fe0.png)
 @jlstevens  here is also plot2 separately, if you would like to see

**Comment by philippjfr** [comment]
Sorry we never addressed this issue, but without a fully reproducible example it's very difficult.
