### ISSUE TITLE
dimensions with the same label (not name) get auto-linked axes in layout

### ISSUE THREAD

**Issue by timothydmorton** [pyviz/holoviews#1783]
Dimensions with different names but the same label; e.g. `('x_frequency', 'Frequency')` and `('y_frequency', 'Frequency')` should not automatically get linked axes in a layout.  In addressing #1776, I have found that in order to prevent automatic linking, I need to give different *label* names as well.

**Comment by philippjfr** [comment]
This was fixed in 1.11.0
