### ISSUE TITLE
More broken docs links

### ISSUE THREAD

**Issue by timothydmorton** [pyviz/holoviews#1793]
http://holoviews.org/reference/elements/bokeh/Pandas_Conversion.html
http://holoviews.org/reference/elements/bokeh/Columnnar_Data.html

**Comment by jlstevens** [comment]
Thanks for reporting these.

Where did you find these broken links? I could download the website off S3 and grep but it is easier if I just ask. :-)

**Comment by timothydmorton** [comment]
Bottom of here: http://holoviews.org/reference/elements/bokeh/Table.html

**Comment by timothydmorton** [comment]
here's another:

http://holoviews.org/user_guide/Linked_Streams.html

linked to in http://holoviews.org/user_guide/Responding_to_Events.html

(I'm clearly your most avid documentation consumer here....)

**Comment by jlstevens** [comment]
That one (and many others!) was fixed in the PR referenced above. We haven't rebuilt the website to make the updates live just yet so until we do that, I would recommend you check that PR to see if the link has been fixed there.

**Comment by philippjfr** [comment]
Going to close this, the remaining broken links are listed in https://github.com/pyviz/holoviews/issues/1650
