### ISSUE TITLE
BoundsXY stream doesn't reset with bokeh "reset" button

### ISSUE THREAD

**Issue by timothydmorton** [pyviz/holoviews#1888]
I would think that pressing the bokeh "reset" toolbar button should reset all active linked streams (like `BoundsXY` streams, for example) to their initial state, so that all box selections should disappear.  This doesn't appear to be the case.

**Comment by jlstevens** [comment]
Possibly. That reset-axis bug is a high priority fix imho and we should test once that is addressed.

**Comment by philippjfr** [comment]
Definitely not related. The ``Bounds`` streams work via 'selectiongeometry' events and the reset tool will never trigger one of those. We can probably attach another callback on the reset tool. I'll play around a bit and will come up with something. As long as we all agree resetting the selection with the reset tool is the most sensible approach.

**Comment by timothydmorton** [comment]
Is there any other way to "un-select" a selection box?  If not, then attaching reset to this action seems sensible to me, though I'm sure I'm missing some other reason why someone else wouldn't like it...

**Comment by philippjfr** [comment]
>I'm sure I'm missing some other reason why someone else wouldn't like it...

Tbh I can't either and it seems quite sensible, happy to go ahead with this.

**Comment by philippjfr** [comment]
We added a Reset stream quite a while ago, which could be used to implement any desired reset actions. I no longer think we should perform the reset of other linked streams automatically.
