### ISSUE TITLE
Adding a colorbar changes plot dimensions (bokeh)

### ISSUE THREAD

**Issue by ceball** [pyviz/holoviews#1947]
https://github.com/ioam/holoviews/issues/167#issuecomment-129191860

<img width="511" alt="screen shot 2017-10-01 at 6 29 29 pm" src="https://user-images.githubusercontent.com/1929/31057194-89ed6c88-a6d6-11e7-839b-c698267dae55.png">

See https://github.com/bokeh/bokeh/issues/5186

Does not happen with mpl.

Hope you are ok having an issue that is only really a link to an issue on the underlying plotting backend, but initially I thought it was a problem with holoviews (until I did some digging).

**Comment by philippjfr** [comment]
This will never get fixed because it's core to how bokeh's layouts work but you can now set the ``frame_width``/``frame_height`` to work around it.
