### ISSUE TITLE
Enable match_aspect keyword from bokeh

### ISSUE THREAD

**Issue by timothydmorton** [pyviz/holoviews#1953]
Bokeh allows an option to match the aspect ratio of a plot: https://bokeh.pydata.org/en/latest/docs/reference/models/plots.html#bokeh.models.plots.Plot.match_aspect.  This would be useful to be able to do in holoviews as well.

**Comment by philippjfr** [comment]
So I've just been playing with it, and I can't really figure out how it's meant to work. If you supply just the width it works fine and scales the height appropriately, but when you supply the height it seems to do the inverse of what I'd expect. If someone can confirm I'm not just confused, we should file an issue with bokeh and postpone this.

**Comment by philippjfr** [comment]
We now allow setting aspect='equal' and/or data_aspect=1 to enable this.
