### ISSUE TITLE
Allow lines with arbitrary slopes (generalization of HLine and VLine)

### ISSUE THREAD

**Issue by ea42gh** [pyviz/holoviews#1993]
Allow lines through a given point with a given slope,
without requiring ranges

(i.e., line should always extend from current plot boundary to current plot boundary, which need not include the given point)

**Comment by philippjfr** [comment]
There's currently a PR in matplotlib that would make this easier (https://github.com/matplotlib/matplotlib/pull/9321), but we'd also have to get something similar upstream into bokeh to support this.
