### ISSUE TITLE
Narrow extents fail to work

### ISSUE THREAD

**Issue by ghost** [pyviz/holoviews#1998]
Use holoviews 1.8.4 and try this in a notebook (or any other renderer)

```import holoviews as hv
import numpy as np
import pandas as pd
import datetime
hv.extension('bokeh')

now = datetime.datetime.utcnow()
delta = lambda t: datetime.timedelta(seconds=t)

extents = (now, 1.1601469999999985, now + delta(99), 1.1601470000000011)
hv.Curve(
    pd.DataFrame({'time': [now + delta(i) for i in range(0, 100)], 'value' : [1.60417] * 100}), 
    kdims=['time'], 
    vdims=['value'],
    extents=extents
)
```
Instead of producing a simple straight line, this will produce a plot with 'undefined' bounds.

**Comment by philippjfr** [comment]
I assume these are numerical precision issues that also exist in bokeh and are probably the result of Javascript limitations.

**Comment by philippjfr** [comment]
Closing since there is no way to address this in HoloViews. Should be filed with bokeh but even then I'm not optimistic this can be fixed.
