### ISSUE TITLE
HoloMap selection problem

### ISSUE THREAD

**Issue by ea42gh** [pyviz/holoviews#2025]
```
dat= pd.concat([ pd.DataFrame(dict(test=1, typ='A',x=np.random.normal(size=100),y=np.random.normal(size=100))),
                 pd.DataFrame(dict(test=2, typ='C',x=np.random.normal(size=300),y=np.random.normal(size=300))),
                 pd.DataFrame(dict(test=3, typ=['B','B']))] )
hv.operation.histogram( hv.Dataset(dat).groupby(['typ','test']) )
```
when first displayed, the 'test' selector alllows selections 1,2,3
but keeps the typ='A' histogram displayed.
Once the typ selector is changed, the test selector is constrained to valid entries only

**Comment by philippjfr** [comment]
I suppose it should be restricted on first display as well, probably not going to prioritize this though.

**Comment by philippjfr** [comment]
In the next major release we no longer have any support for non-orthogonal dimensions which means that this issue no longer occurs.
