### ISSUE TITLE
Alias dimensions

### ISSUE THREAD

**Issue by Sieboldianus** [pyviz/holoviews#2026]
First of all: thanks to this great project, I love Holoviews and the way it renders my data.

I am still fighting with Dimensions. [Here]() it says that aliases can be provided in the form of `('year', 'Year')`, example code:

```python
macro_df = pd.read_csv('http://assets.holoviews.org/macro.csv', '\t')
key_dimensions   = [('year', 'Year'), ('country', 'Country')]
value_dimensions = [('unem', 'Unemployment'), ('capmob', 'Capital Mobility'),
                    ('gdp', 'GDP Growth'), ('trade', 'Trade')]
macro = hv.Table(macro_df, kdims=key_dimensions, vdims=value_dimensions)
```

Now, with my data, I got the value-dimensions renamed but not  for the key-dimensions:
```python
df = pd.DataFrame(MyTabularData)
df = pd.melt(df, id_vars='atkmindex', var_name='Tags', value_name='Percentage of Users')
df['Tags'] = [d.replace('_', ' ').title() for d in df.Tags]
value_dim = hv.Dimension('Percentage of Users', value_format=percent_format, range=(0, 90))
ds = hv.Dataset(df, vdims=[value_dim])
#does not work ("TypeError: not all arguments converted during string formatting":
curves = ds.to(hv.Curve, kdims=[('atkmindex', 'AT South to North')], groupby='Tags').overlay()
#does work:
curves = ds.to(hv.Curve, kdims=['atkmindex'], groupby='Tags').overlay()
```

Could you give me a hint how the Dimension Alias in case for kdims works?

**Comment by philippjfr** [comment]
Sorry that this stalled for so long (>1 year!!!). Just to answer the question, the problem here is that the aliases must be defined when the Dataset is originally defined:

```python
hv.Dataset(df, [('atkmindex', 'AT South to North'), 'Tags'], value_dim)
```

**Comment by Sieboldianus** [comment]
Great - I am long through with this project, but I'll remember to look at it - still working with Holoviews! Hopefully your answer will help others, too. Many thanks.
