### ISSUE TITLE
box_select and lasso_select for Curves

### ISSUE THREAD

**Issue by tomriis** [pyviz/holoviews#2051]
I am curious if the same ability to use selection1D to select multiple [points](http://holoviews.org/reference/streams/bokeh/Selection1D_points.html) is available to make multiple selections of Curves? Using tap tool works great on selecting curves as demonstrated [here](http://holoviews.org/reference/streams/bokeh/Selection1D.html), however adding box_select or lasso_select tools doesn't seem to allow the selection of curves as it does for points. Is this a known limitation?

Code Im trying to demonstrate this on

````
%opts NdOverlay [legend_limit=0] Curve [tools=['tap','box_select','lasso_select']] (line_width=10)
ndoverlay = hv.NdOverlay({i: hv.Curve(np.arange(10)*i) for i in range(5)})

selection = hv.streams.Selection1D(source=ndoverlay)
dmap = hv.DynamicMap(lambda index: ndoverlay[index] if index else ndoverlay.clone(),
                     kdims=[], streams=[selection])
ndoverlay + dmap
````

**Comment by philippjfr** [comment]
Apologies for not getting to this sooner. I'd have to play around a bit to confirm but iirc selection of individual points does not work on a ``Curve``. As a workaround you could create a set of invisible points using ``Scatter`` mirroring the ``Curve``, which you can then apply the selection on.

Supporting selection on a curve is something we would have to request and implement at the bokeh level.

**Comment by tomriis** [comment]
Ok thanks for letting me know! Ill be implementing the workaround then. I'll post my solution here for anyone else reading the thread

**Comment by tomriis** [comment]
@philippjfr Just got back to this, here is the workaround I made:

```
n_curves = 5
opts = dict(plot=dict(tools=['box_select','lasso_select']))

class SelectedData():
    def __init__(self):
        self.selected = {}  
selecteddata=SelectedData()

dmaps = []
points = {i:hv.Points(i*np.arange(10)).opts(**opts) for i in range(n_curves)}
curves = {i:hv.Curve(i*np.arange(10)) for i in range(n_curves)}

for i in range(n_curves):
    def callback(index, curve = i):
        selecteddata.selected[curve] = True if index else False
        return curves[curve]*points[curve]
    dmaps.append(hv.DynamicMap(callback, streams=[hv.streams.Selection1D()]))

hv.Overlay(dmaps).collate()
```

![selection_demo1](https://user-images.githubusercontent.com/29220507/32425565-140c3bbc-c282-11e7-8f69-3c7fa3e915bb.png)

Unfortunately, I hit the 'RecursionError: maximum recursion depth exceeded' at about n_curves=200 curves. Please let me know if a more scalable solution exists!

**Comment by philippjfr** [comment]
Here's about the best solution I managed to figure out:

```python
%%opts NdOverlay [batched=False]

from functools import partial

n_curves = 30
curves = hv.NdOverlay({i: hv.Curve(i*np.arange(10)) for i in range(n_curves)})
opts = dict(plot=dict(tools=['box_select','lasso_select']))

def notify_selection(index, key):
    selected[key] = bool(index)

selected = {}
items = {}
for k, el in curves.items():
    items[k] = hv.Scatter(el).opts(**opts)
    stream = hv.streams.Selection1D(source=items[k])
    stream.add_subscriber(partial(notify_selection, key=k))
scatter = hv.NdOverlay(items)
curves * scatter
```

That said none of these solutions will scale very well for hundreds of Curves because it will only work when batching is disabled and bokeh becomes fairly slow once you draw hundreds of individual glyphs.

**Comment by philippjfr** [comment]
This really requires changes in bokeh, so I'm going to close.
