### ISSUE TITLE
streams dont work when redim is applied on a source element later

### ISSUE THREAD

**Issue by suvarchal** [pyviz/holoviews#2105]
it was bizzare to me that streams didnt work when redim.range was applied on a stream source Element later on, ie.., after defining the stream. I wonder if it can be called a bug or a feature request. 

it can be reproduced with a change to last line in  holoviews Tap [example](http://holoviews.org/reference/streams/bokeh/Tap.html)

    %opts HeatMap [width=700 height=500 logz=True fontsize={'xticks': '6pt'}, tools=['hover'] xrotation=90] (cmap='RdBu_r') 
    %opts Curve [width=375 height=500 yaxis='right'] (line_color='black') {+framewise}

    df = pd.read_csv('http://assets.holoviews.org/data/diseases.csv.gz', compression='gzip')
    dataset = hv.Dataset(df, vdims=('measles','Measles Incidence'))

    heatmap = hv.HeatMap(dataset.aggregate(['Year', 'State'], np.mean),
                     label='Measles Incidence').select(Year=(1928, 2002))

    posxy = hv.streams.Tap(source=heatmap, x=1951, y='New York')

    def tap_histogram(x, y):
           return hv.Curve(dataset.select(State=y, Year=int(x)), kdims='Week',
                   label='Year: %s, State: %s' % (x, y))
    heatmap.redim.range(measles=(0,1)) + hv.DynamicMap(tap_histogram, kdims=[], streams=[posxy])  

on tap the Curve plot does not change, it would be nice addition if after defining the stream if we could still apply redim.

**Comment by philippjfr** [comment]
This definitely should work so I've marked this as a bug.

**Comment by suvarchal** [comment]
I wonder if it is because redim creates a clone of an Element which is not source anymore?

**Comment by philippjfr** [comment]
>I wonder if it is because redim creates a clone of an Element which is not source anymore?

Right, it's something like that but we do have mechanisms to handle that kind of thing. Basically applying methods to a DynamicMap builds a graph, which can be traversed to find the sources, seems like in this case something is going wrong there.

**Comment by philippjfr** [comment]
Okay I just went through the example and looking at it again there is really no way this will ever work. HeatMap is a regular element so when you apply ``redim`` or indeed any other method you get a new object which is no longer linked to the stream. I would just make sure you apply redim before using the element as the source.

**Comment by jlstevens** [comment]
Right - that does make sense. In this case, we should have a warning in the docs to explain this behaviour. Generally methods like ``redim`` and ``clone`` generate new elements which means they won't refer to whatever was passed as source.

**Comment by suvarchal** [comment]
just to add not just heatmap any regular element like QuadMesh this would not work? may be a warning in documentation would avoid this pitfall.

**Comment by philippjfr** [comment]
So luckily I was completely wrong here, since 1.11.0 we now link objects with a shared `_plot_id`, which doesn't change unless the data is altered. Additionally, since https://github.com/pyviz/holoviews/pull/3478 we now inherit the plot_id on redim, which means the example above works just fine as is.
