### ISSUE TITLE
streams dont work on Overlay objects as source should atleast raise an error?

### ISSUE THREAD

**Issue by suvarchal** [pyviz/holoviews#2106]
I learnt the hard way that streams dont work when their source is an Overlay object. I think, atleast they should raise an error while defining a stream. 

here is an holoviews tap example modified to overlay a text before declaring the stream.

    %opts HeatMap [width=700 height=500 logz=True fontsize={'xticks': '6pt'}, tools=['hover'] xrotation=90] (cmap='RdBu_r') 
    %opts Curve [width=375 height=500 yaxis='right'] (line_color='black') {+framewise}

    df = pd.read_csv('http://assets.holoviews.org/data/diseases.csv.gz', compression='gzip')
    dataset = hv.Dataset(df, vdims=('measles','Measles Incidence'))

    heatmap = hv.HeatMap(dataset.aggregate(['Year', 'State'], np.mean),
                     label='Measles Incidence').select(Year=(1928, 2002))*hv.Text(1998,'Montana',text='hey')

    posxy = hv.streams.Tap(source=heatmap, x=1951, y='New York')

    def tap_histogram(x, y):
        return hv.Curve(dataset.select(State=y, Year=int(x)), kdims='Week',
                   label='Year: %s, State: %s' % (x, y))

    heatmap + hv.DynamicMap(tap_histogram, kdims=[], streams=[posxy])

I understand currently the right way would be to overlay in the last step and not before defining the stream
`heatmap*hv.Text(1998,'Montana',text='hey') + hv.DynamicMap(tap_histogram, kdims=[], streams=[posxy])`

but I think raising an error when defining the stream if the source is an overlay object will save a user from this pitfall. Holoviews is so flexible sometimes one starts to expect even more.

**Comment by philippjfr** [comment]
Thanks, feedback like this is really helpful and I agree with you, an ``Overlay`` can never be a valid ``source`` so it should definitely warn or error.

**Comment by philippjfr** [comment]
So once again I appear to have been completely wrong here, the example works perfectly in current master.
