### ISSUE TITLE
False update of colorbar / hv.Dimension ?

### ISSUE THREAD

**Issue by LEMUEGGE** [pyviz/holoviews#2123]
I am trying to dynamically change the colormap of an image plot by using a paramnb slider to adjust the min and max  value of vdims in the hv.Image. It works fine, manually changing the plot renders the changes of the colorbar. However, for some values of vdim max, the colorbar does not display the right range of vdim. I am not sure if this is just a visual artefact or if the colormap is not adjusted correclty. I am using the newest version of holoviews.

![screenshot from 2017-11-14 00 28 33](https://user-images.githubusercontent.com/32666129/32754890-0183788c-c8d3-11e7-98ad-9130a72c3d92.png)

Minimal example:

```
import numpy as np
import holoviews as hv
import datashader as ds
import xarray as xr
from holoviews.streams import RangeXY
from bokeh.palettes import Greys
from param import Range
import param
import paramnb
hv.extension('bokeh','matplotlib')

test_array = xr.DataArray(np.random.rand(460,460),dims=['x','y'])
test_opts =  {
    'style': {'cmap': 'Greys'},
    'plot' : {'height':set_height, 'width':set_width, 'colorbar':True, 'interpolation':None,  'aspect':'equal',
              }
}
range_stream = RangeXY(x_range=x_range,y_range=y_range) # stream for HiC plot

def image_plot_f(x_range, y_range):
    x_range = tuple(map(int,x_range))   # we need integer tuples because the axes are discret
    y_range = tuple(map(int,y_range))
    global x_r
    global y_r
    x_r = x_range
    y_r = y_range
    cvs = ds.Canvas(x_range=x_range, y_range=y_range, plot_height=800, plot_width=800)
    agg = cvs.raster(test_array,upsample_method='nearest')

    return hv.Image(agg,vdims=[hv.Dimension('data', range=(Control.Color_Map[0], Control.Color_Map[1]))]).opts(**test_opts)

plot = hv.DynamicMap(image_plot_f, streams=[range_stream])
class Control(param.Parameterized):
    Color_Map = param.Range(default=(0,0.05),bounds=(0, 0.15)) #widget to adjust colorbar
paramnb.Widgets(Control)
plot 
```

**Comment by jbednar** [comment]
Personally, instead of the above approach with a colorbar, I'd just add ``.hist()``  to your ``hv.Image()`` call.  ``.hist()`` already supports using the Box Select tool on the histogram to select the value ranges to map into the color range, even for a static HTML output.  No need for ParamNB at all or even a live Python server in this case!

![image](https://user-images.githubusercontent.com/1695496/32755439-f3488664-c89a-11e7-9532-006fecc217ca.png)

![image](https://user-images.githubusercontent.com/1695496/32755624-d1a08b32-c89b-11e7-8edf-96f242842b27.png)

**Comment by LEMUEGGE** [comment]
Thanks for the quick answer! Actually I looked at this, but the problem is that the value ranges do not seem to be preserved on zoom. Maybe it is contra intuitive but the mapping should be the same for all zoom views.
 I am also aware of the fact that the datashader routine is not needed for the test matrix, but we would like to scale the solution to very big matrices at some point ;-)

**Comment by jbednar** [comment]
Good question.  It might help to supply a fixed range for the z dimension, but if not, then having the histogram-selected color mapping be preserved across zooms is definitely a reasonable feature request (@Philipp?).

**Comment by LEMUEGGE** [comment]
Small update: The issue is fixed if I use param.Number widgets instead.

**Comment by jlstevens** [comment]
If the behavior depends on the parameter type used, does this mean it is a ``paramnb`` issue and not a holoviews issue?

**Comment by philippjfr** [comment]
Can't reproduce any issue here using panel which is the replcement for paramnb.
