### ISSUE TITLE
[Docs] Add a tidbit about Cycles to the docs in 'Customizing Plots'

### ISSUE THREAD

**Issue by tobsecret** [pyviz/holoviews#2126]
I wanted to change the color cycle for a plot, as the default color cycle of `hv.Overlay` only spans 5 colors.
I talked to @jlstevens on gitter and got it resolved very quickly but we figured out that Cycles are only mentioned in the `Customizing Plots.html` docs, however no example of their use is given.

I prepared a minimal example below, with and without Cycle specified in plot opts:

This example shows why the color cycle can be problematic, as [this issue](https://github.com/ioam/holoviews/issues/1591) also details; as soon as you get to more than 5 curves, the color cycle repeats.
```python
xs = np.linspace(-np.pi,np.pi,100)
hv.Overlay([hv.Curve((xs, xs*(i+1))) for i in range(6)])
```

```python
%%opts Curve (color=Cycle('Blues'))
#^ This will change the color cycle to the palette Blues
xs = np.linspace(-np.pi,np.pi,100)
hv.Overlay([hv.Curve((xs, xs*(i+1))) for i in range(6)])
```

**Comment by philippjfr** [comment]
There is now a whole sections on Cycles and Palettes [here](http://holoviews.org/user_guide/Style_Mapping.html).
