### ISSUE TITLE
Not all resources are inlined in notebook

### ISSUE THREAD

**Issue by ceball** [pyviz/holoviews#2168]
My understanding is that holoviews is meant to inline all resources. If that's right, then it seems like some things may have slipped through. E.g. if you run examples/getting_started/1-Introduction.ipynb, on executing the first code cell there are external network accesses.

```
import pandas as pd
import numpy as np
import holoviews as hv
hv.extension('bokeh')
```

<img width="657" alt="screen shot 2017-12-01 at 11 13 24 pm" src="https://user-images.githubusercontent.com/1929/33507558-47e28bec-d6ed-11e7-9bda-27e49eca4abe.png">

**Comment by philippjfr** [comment]
Since switching to panel we no longer have external dependencies, except for the custom models where loading from a CDN is unavoidable.
