### ISSUE TITLE
Improve documentation of file export with %%output

### ISSUE THREAD

**Issue by ceh-creare** [pyviz/holoviews#2175]
Hi there,

I am trying to export an overlay figure as an svg using 
`%%output filename="chlorophyll" fig="svg"`
But I get the following error:
Error: Value 'svg' for key 'fig' not one of ['html', 'json', 'auto', 'png']

I can use `%%output filename="chlorophyll" fig="png"` to successfully export a png. Am I missing something obvious? The export documentation makes it sound like svg is supported.

Thanks for your help!

**Comment by jbednar** [comment]
Sounds like you're using the Bokeh extension.  SVG is supported for the Matplotlib extension, but not yet for Bokeh.  Bokeh itself supports exporting to SVG, but it's only partial support (each subfigure generates a separate SVG), and we haven't yet figured out a good way to get full support of the entire layout.

**Comment by ceh-creare** [comment]
Got it! Thank you for that clarification and quick response!

**Comment by jakirkham** [comment]
Might be worth noting that in [Exporting and Archiving]( http://holoviews.org/user_guide/Exporting_and_Archiving.html ) under "Exporting specific files".

**Comment by jlstevens** [comment]
I'll repurpose this issue as a reminder to improve the docs.

**Comment by philippjfr** [comment]
We've now added ``hv.save`` which is documented in a number of places throughout the docs.
