### ISSUE TITLE
Minor Problems with DynamicMap and HoloMap

### ISSUE THREAD

**Issue by ea42gh** [pyviz/holoviews#2184]
The file
https://github.com/ea42gh/HoloviewsPlayground/blob/master/Philippjr.ipynb

contains 5 simple examples that I thought should work
but didn't. The behavior I see is specified in the code comments

**Comment by jlstevens** [comment]
Thanks for this! A number of these are definite bugs e.g casting a dynamicmap to a holomap should always work.

**Comment by ea42gh** [comment]
added example 6
I was trying to deal with categorical axes,
and could not figure out how to set the colors of hv.Points correctly

**Comment by ea42gh** [comment]
up to 10 examples now.
I am guessing that quite a number of these are my bugs
rather than some issue in holoviews.
When you look at these, would you mind letting me know what I was missing?

**Comment by ea42gh** [comment]
I  lost track of the list of problems in the various examples.
Here is an attempt to provide an overview

[ ] example 1: problems with parameters of DynamicMap
[ ] example 2: problems with titles in a DynamicMap
[ ] example 2: problem with casting DynamicMap to HoloMap
[ ] example 3: problem with casting DynamicMap to HoloMap
[ ] example 4: problem with casting DynamicMap to HoloMap
                      Feature Request: allow legends for hv.Distribution
[ ] example 5: %%opts DynamicMap warning
[ ] example 5: DynamicMap cannot display Adjoined elements
[ ] example 6: inconsistent handling of legends and colorbar positions in bokey and matplotlib
[ ] example 7: xticks=[] handling problems, problem setting color inidices
[ ] example 8: gridmatrix and canonical axes problems
[ ] example 9: strange 'singular matrix' error in GridMatrix
[ ] example 9: Feature Request GridMatrix does not honor xticks, yticks, and cannot display legends
[ ] example 10: Strange bokeh ErrorBars behavior with invert_axes=True.
                        The problem appears to be data dependent
[ ] example 11: Feature Request:
                             HeatMap should not enforce different dimension names: species/Species
                             HeatMap and Image do not honor xticks=[...], yticks=[...]
[ ] example 11: strange interaction of  heatmaps and Text affecting axes in matplotlib

**Comment by philippjfr** [comment]
Thanks for the helpful breakdown @ea42gh. I'm back now and will have a look into these as time permits. I hope you don't mind but I'll edit your list so I can tick off issues.

**Comment by ea42gh** [comment]
of course I don't mind!!!!!

**Comment by philippjfr** [comment]
Sorry @ea42gh I'm closing this. It's far too difficult to work out the precise issues here and each individual bug should have its own issue. Please reopen (atomic) issues if necessary.
