### ISSUE TITLE
Add automatic unit tests ensuring elements can be constructed with empty data

### ISSUE THREAD

**Issue by philippjfr** [pyviz/holoviews#2192]
All Elements should support being constructed with empty data, currently it's easy to forget this when adding a new element so we should add general unit tests which ensures that all concrete Element subclasses should support being constructed with empty data.

**Comment by ceball** [comment]
If holoviews uses the same test framework as param (unittest/nose), maybe it could be useful to see the param test which checks all concrete descendents of Parameter have a valid default? 

https://github.com/ioam/param/blob/master/tests/testdefaults.py

I vaguely recall some problem had to be overcome for nose - dynamically generating test methods early enough for nose to find them, or something like that. Maybe no longer necessary these days? Or if not a good idea, you can say what's wrong with that code and I can fix the param test :)
