### ISSUE TITLE
hv-powered bokeh app crashes with too many big dmaps

### ISSUE THREAD

**Issue by timothydmorton** [pyviz/holoviews#2255]
The following app crashes (loses websocket connection) a few seconds after first loading properly:

https://gist.github.com/timothydmorton/d7accd2c83883ce31853faf114d81c96

There is suspicion it might have something to do with being too much data with the binary websocket.

**Comment by philippjfr** [comment]
Will have a go at creating a pure bokeh version and filing an issue upstream with bokeh. Doubt this is something HoloViews specific.

**Comment by timothydmorton** [comment]
Looks like this might be related to https://github.com/bokeh/bokeh/issues/7374.

**Comment by philippjfr** [comment]
Yes, that seems likely.

**Comment by timothydmorton** [comment]
I can confirm that hacking the bokeh source to sufficiently increase `websocket_max_message_size` solves this issue for me.

**Comment by philippjfr** [comment]
Okay, this is not something we can control at the HoloViews level.
