### ISSUE TITLE
%output holomap='gif' filename='name.gif' creates name.gif.html

### ISSUE THREAD

**Issue by basnijholt** [pyviz/holoviews#2260]
Using `%%output holomap='gif' filename='name.gif' creates name.gif.html` to create a `gif` out of a `HoloMap` results in a file called `name.gif.html` instead of `name.gif`.

**Comment by jlstevens** [comment]
I've not touched the GIF stuff in a very long time, but I agree this is an issue that needs fixing. I've assigned this issue it to myself.

**Comment by basnijholt** [comment]
A colleague just ran into this problem, I had to dig deep into the chat history to find the workaround. For later reference it was: `hv.renderer('matplotlib').save(hm, 'test', fmt='gif')`

**Comment by basnijholt** [comment]
Is this still going to be supported?

**Comment by philippjfr** [comment]
We no longer support saving via output and now have a top-level ``hv.save`` function so I'll close.
