### ISSUE TITLE
Extra white space when using Overlay of two NdOverlay's with matplotlib backend.

### ISSUE THREAD

**Issue by daliu87** [pyviz/holoviews#2358]
When running the following in a Jupyter notebook using a matplotlib backend with aspect ratio set, you end up with a lot of white space:

```python
%%opts Curve [aspect=2]
%%opts ErrorBars [aspect=2]
%%output backend='matplotlib' size=200

arr_a = np.random.rand(10)
arr_b = np.random.rand(10)

nd1 = {}
nd1['one'] = hv.Curve((np.arange(10), arr_a))
nd1['two'] = hv.Curve((np.arange(10)+0.1, arr_b))

nd2 = {}
nd2['one'] = hv.ErrorBars(( np.hstack([np.arange(10)[:,np.newaxis], arr_a[:, np.newaxis], 
 np.random.rand(10,2)])))
nd2['two'] = hv.ErrorBars(( np.hstack([(np.arange(10)+0.1)[:,np.newaxis], arr_b[:, np.newaxis]+0.1, np.random.rand(10,2)])))


ndover1 = hv.NdOverlay(nd1)
ndover2 = hv.NdOverlay(nd2)

ndover1 * ndover2
```

![image](https://user-images.githubusercontent.com/1929125/36456184-766be030-1658-11e8-952a-28d07edd19b9.png)

This only seems to happen with matplotlib and a qtagg backend, I don't see this issue using bokeh or matplotlib's svg, pdf backends.

Is there a way to manually control the borders?

Thanks!

**Comment by jlstevens** [comment]
> This only seems to happen with matplotlib and a qtagg backend, I don't see this issue using bokeh or matplotlib's svg, pdf backends.

Sounds like it might be down to an inconsistency within matplotlib. Still rather annoying though!

**Comment by philippjfr** [comment]
Can't reproduce this anymore, please reopen if this is still an issue now.
