### ISSUE TITLE
Unable to set horizontal errorbars, or both horizontal and vertical at same time

### ISSUE THREAD

**Issue by sghionea** [pyviz/holoviews#2361]
Hello,
The hv.errorbars object does not have any provision to allow both vertical and horizontal errorbars simultaneously.  I also cannot find an option to have the "error" in the errorbar be aligned along the horizontal x-axis. If this was a possibility, dual axis errorbars could be implemented by overlaying two plots.

This appears to be the case regardless of backend. Am I missing something in the documentation? Is this feature intentionally omitted?

Thank you,
-Simon

**Comment by philippjfr** [comment]
I'd be in favor of adding an option to draw the errorbars horizontally which would allow overlaying them to get both horizontal and vertical bars.

**Comment by philippjfr** [comment]
ErrorBars now have a horizontal parameter which is documented.
