### ISSUE TITLE
Xarray DataSet

### ISSUE THREAD

**Issue by GProtoZeroW** [pyviz/holoviews#2412]
Is there a way for Holoviews to pull in and display

 what I am suggesting in the attached notebook or if there currently is not can we make it part of  holoviews 

the prototype notebook showing what I am after and some proto-code is located here: https://github.com/GProtoZeroW/IssueNotebooks/blob/master/HoloviewsXarryDataSetProto.ipynb

**Comment by philippjfr** [comment]
I've had a go at adding some HoloViews plots to the notebook:

https://anaconda.org/philippjfr/holoviewsxarrydatasetproto/notebook

For now I've only made a quick pass over it, so it's not too detailed. I've also had a go at some of the more complex requests you made. They do run into some limitation of the current stack but can be worked around using parambokeh for example, in the future those issues should also become more straightforward.

**Comment by GProtoZeroW** [comment]
Oky let me take a crack at it again later, but first I need to make use of what we have thus far. what are the code requrments for a more redefined prototype that you and the Devs need to take and integrate into the main code?

**Comment by philippjfr** [comment]
[xrviz](https://github.com/intake/xrviz) does most things requested in that notebook and much more so I'll close.
