### ISSUE TITLE
collapse HoloMap of Overlays to Overlay leads to lines with same style opts

### ISSUE THREAD

**Issue by basnijholt** [pyviz/holoviews#2416]
See these beautiful colors (as expected)
```python
xs = np.linspace(-1, 1)
slopes = [-2, -1, 1, 2]
hv.Overlay([hv.Curve(xs / x) * hv.Scatter([]) for x in slopes])
```
<img width="295" alt="screen shot 2018-03-06 at 21 56 32" src="https://user-images.githubusercontent.com/6897215/37075994-4aa6a19c-2189-11e8-85c6-66e34b380d37.png">

This also works:
```python
hv.HoloMap({x: hv.Curve(xs / x) for x in slopes}).overlay()
```
<img width="314" alt="screen shot 2018-03-06 at 21 57 09" src="https://user-images.githubusercontent.com/6897215/37076000-57cdff5a-2189-11e8-8c00-eab8a3572ee9.png">

And now the problem:
```python
hv.HoloMap({x: hv.Curve(xs / x) * hv.Scatter([]) for x in slopes}).overlay()
```
<img width="327" alt="screen shot 2018-03-06 at 21 57 41" src="https://user-images.githubusercontent.com/6897215/37076018-6a122722-2189-11e8-8faf-040dbb7f3f5f.png">

Because of this problem we can't merge in https://github.com/python-adaptive/adaptive/commit/ab6de46da28994aae557f48f8bb78c458b53d5ec yet (more of a personal note.)

**Comment by philippjfr** [comment]
Can't see this getting fixed before 1.10, nesting Overlays inside NdOverlays is not generally recommended. I do think this should be fixed eventually but for the time being I'd suggest nesting NdOverlays inside Overlays rather than the inverse.

**Comment by basnijholt** [comment]
I don't think we can avoid it. This is actually already kind of a hack because of https://github.com/ioam/holoviews/pull/2174#issuecomment-366954186.

**Comment by philippjfr** [comment]
I'm going to try my best to get #2174 in, unfortunately there has been a regression in bokeh that I'll have to resolve before that PR becomes mergeable.

**Comment by philippjfr** [comment]
This was fixed a while ago.
