### ISSUE TITLE
Feature Request: infer hv.Div width when Div is in a columnar layout 

### ISSUE THREAD

**Issue by ea42gh** [pyviz/holoviews#2437]
```
%%opts Curve [width=500]
(hv.Div()+hv.Curve()+hv.Curve()+hv.Curve()).cols(2)
```
Current implementation requires a Div width option to be set by trial and error
to get the second column of plots to align.

**Comment by philippjfr** [comment]
Having trouble figuring out what the issue here is, things do seem aligned now. Please reopen if the problem persists and maybe describe what isn't working.

**Comment by ea42gh** [comment]
seems to be fixed in current holoviews   :)
