### ISSUE TITLE
Redundant legend with two-level Bars

### ISSUE THREAD

**Issue by toddrjen** [pyviz/holoviews#2565]
You can do two-level X-Axis with `Bars` and the Bokeh backend, but by default this gives a legend that just repeats the same thing shown in the inner X-Axis level.

This:

```Python
var1 = ['Arthur', 'Galahad']
var2 = ['duck', 'newt']
var1, var2 = zip(*product(var1, var2))
vals = np.random.random(len(var1))

mybars = hv.Bars(zip(var1,var2, vals), ['var1', 'var2'], 'vals')
mybars
```

Creates the following plot:

![bokeh_plot](https://user-images.githubusercontent.com/2272878/38810326-77de8ed2-4154-11e8-865d-8d15c7dd9ded.png)

Note that "duck" and "newt" are shown on both the X-Axis and the legend.  The legend really doesn't add anything and should probably be hidden by default.

**Comment by jlstevens** [comment]
> Note that "duck" and "newt" are shown on both the X-Axis and the legend. The legend really doesn't add anything and should probably be hidden by default.

Agreed. That does seem sensible and I'm tagging this as a bug.

**Comment by philippjfr** [comment]
This has been fixed.
