### ISSUE TITLE
Move unit tests inside the holoviews package

### ISSUE THREAD

**Issue by philippjfr** [pyviz/holoviews#2580]
Currently we have the test module at the root level, which has a number of drawbacks. The two main reasons ones are:

1. External libraries which HoloViews builds on and that want to run the unit test suite to check for regressions in their code (see https://github.com/bokeh/bokeh/issues/7720 and https://github.com/bokeh/bokeh/pull/7813 for requests to do just that)

2. External libraries that extend HoloViews with plotting code or data interfaces. The HoloViews tests define extensive test suites for data interfaces which can be subclassed to test whether a new data interface conforms with the expected API. If we want to allow extensions to HoloViews which define custom data interfaces then these would currently have to copy these test suites, causing possible divergence and adding additional maintenance burden. Defining these test suites at the HoloViews level in a way that they can be extended ensures that when we change or improve the API, downstream libraries which subclass these tests will automatically be validated with the changes. This will make it much easier to move interfaces like iris to extension libraries like GeoViews.

Therefore I'd propose (and strongly urge) we move the tests inside the holoviews module.

**Comment by jlstevens** [comment]
Sounds good to me.

I would like to go further, splitting up the tests up into the subpackages. In particular, split the tests between core and plotting to reflect however we decide to split the repo post 1.10.1.

**Comment by philippjfr** [comment]
>I would like to go further, splitting up the tests up into the subpackages. In particular, split the tests between core and plotting to reflect however we decide to split the repo post 1.10.1.

This has already happened.

**Comment by jlstevens** [comment]
I meant in terms of directories e.g ``holoviews/plotting/bokeh/tests``, ``holoviews/plotting/mpl/tests``. The fact that the tests have been split up in the root ``tests`` directory helps so now the question is how to distribute those tests around.

**Comment by philippjfr** [comment]
Ah, yes, I've suggested that in the past - I'd be very happy about that.

**Comment by philippjfr** [comment]
This was done.
