### ISSUE TITLE
Incorrect use of .opts method can cause plotting to hang

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#2631]
While updating ``lorenz_attractor_example.ipynb``, I ran the following which is an *incorrect* use of ``.opts`` (should be ``.options``):

```
lorenzian.opts('Path', color=hv.Palette('Blues'))
```

But instead of either resulting in incorrect output or issuing an error...it just hangs. This kind of behavior is worrying as there is no feedback about what is going wrong.

**Comment by philippjfr** [comment]
This was fixed somehow.
