### ISSUE TITLE
Document xticks and yticks plot options

### ISSUE THREAD

**Issue by Forander** [pyviz/holoviews#2640]
Hi,

Is it possible to rename the axes tick labels such as in Bokeh? Ex: `p.xaxis.major_label_overrides = {0: "zero", 5: "five", 10: "ten"}` would replace given x axis integer tick labels with strings.

I could not find anything in the documentation. Thanks,
Derek

**Comment by jlstevens** [comment]
If I remember right, you can use a similar format for the ``xticks`` plot option, but it might be a list of tuples to keep the order. One example of using ``xticks`` (without custom labels) can be found [on this page](http://holoviews.org/reference/elements/matplotlib/QuadMesh.html).

**Comment by ea42gh** [comment]
There is at least one exception to this:
the matplotlib backend with projection=polar does not conform.

**Comment by Forander** [comment]
Thanks guys for the feedback!

**Comment by Forander** [comment]
Follow up question @philippjfr : are xticks controls compatible with Bars?

`hv.Bars(range(10)).options(xticks=[(0, 'zero'), (5, 'five'), (8, 'eight')])` 

Gives me:
'Javascript error adding output!
TypeError: a.mids is undefined
See your browser Javascript console for more details.'

**Comment by philippjfr** [comment]
This is documented here: http://holoviews.org/user_guide/Customizing_Plots.html#Axis-ticks
