### ISSUE TITLE
PolyDraw stream addition to allow setting an additional variable to color polygon

### ISSUE THREAD

**Issue by ayoungs** [pyviz/holoviews#2694]
Allow for assigning each Polygon an additional variable to color by.
For instance allow use the example gallery/demos/bokeh/box_draw_roi_editor.ipynb
and have each ROI have it's own line_color at the very least.

**Comment by philippjfr** [comment]
@ayoungs Finally working on this, what I've done initially is allow specifying ``style_cycles`` on the ``PolyDraw`` stream. For example here we define a cycle for the ``fill_color``:

```python
poly = hv.Polygons([[(2, 2), (5, 8), (8, 2)]])

poly_stream = streams.PolyDraw(source=poly, drag=True, show_vertices=True,
                               style_cycles={'fill_color': ['red', 'green', 'blue']})

poly
```

which will be applied whenever we draw a new polygon. Is this sufficient for your purposes or do you need something more complex?
