### ISSUE TITLE
Add support for cftime types

### ISSUE THREAD

**Issue by philippjfr** [pyviz/holoviews#2709]
As outlined in this xarray issue (https://github.com/pydata/xarray/issues/2164) we currently do not have support for the new cftime types they introduced. It might be as simple as adding them to the ``holoviews.core.util.datetime_types`` at the HoloViews level but probably also requires some work at the bokeh level.

**Comment by rabernat** [comment]
If you have questions about this new type, @spencerkclark is probably the person to ask.
