### ISSUE TITLE
Strange HoloMaps Axis behavior

### ISSUE THREAD

**Issue by ea42gh** [pyviz/holoviews#2779]
holoviews version 1.10.5
```
%%opts Curve {+framewise +axiswise}
def mk_data(n):
    return pd.DataFrame( dict(x = [k for k in range(n)], y1 = [0.1*n*k for k in range(n)], y2 = [0.5*n*k for k in range(n)]  )).reset_index()

some_data = { str(i) : mk_data(k) for i,k in enumerate([18, 13, 16, 18, 19, 18, 19, 18, 18, 95]) }

def plot(i):
    h=\
    hv.Overlay([hv.Curve( some_data[i], 'index', hv.Dimension(v,label='y'), label=v) for v in some_data[i].filter(like='y').columns ]).options(width=720)
    return h.options(legend_position='left')

hv.HoloMap({ i : plot(i) for i in some_data.keys()})
```
Problem: Select plot 9, followed by plot 8:
the x axis range is not reset?!

Wishlist: an easy way to stop the axes from changing location as tick labels change lengths (e.g., the transition from 0 to 1)

**Comment by philippjfr** [comment]
Same issue as https://github.com/ioam/holoviews/issues/2753 I believe. This is a tricky issue that arose from the way we handle bokeh update messages. We might need to add some code to ensure that for non-dynamic plots all the data is embedded for each frame.

**Comment by philippjfr** [comment]
Appears to be fixed.
