### ISSUE TITLE
Accept Parameterized objects for DynamicMap streams?

### ISSUE THREAD

**Issue by jbednar** [pyviz/holoviews#2781]
The NYCTaxiExplorer example at the end of the [PyViz Workflow Introduction](http://pyviz.org/tutorial/01_Workflow_Introduction.html) is currently defined as a HoloViews Stream, at least in part because it is later passed to DynamicMap's streams argument, which requires Streams.  A Stream is a subclass of param.Parameterized, and the NYCTaxiExplorer class itself is only ever using the Parameterized methods and functions, so it would be greatly preferable to define it as a Parameterized instead of a Stream.

There is actually already a ParamValues class that accepts a Parameterized class or instance and creates the corresponding Stream.  It would be awkward to use that by hand each time, so can we instead have DynamicMap accept either Parameterized or Stream objects for its streams argument, promoting the Parameterized to a Stream automatically?

I'm not certain this will be sufficient, though, because if you look at NYCTaxiExplorer its `.event` method (presumably from Stream, not Parameterized) is being passed to ParamBokeh, not just DynamicMap. @philippjfr?

**Comment by philippjfr** [comment]
This won't be possible until we've added the ``.watch`` mechanism to param.

**Comment by jbednar** [comment]
Ok, that's what I was suspecting, i.e. that Parameterized isn't yet sufficient.

**Comment by philippjfr** [comment]
We now have support for this via the Params stream, you can even pass in parameter instances directly.
