### ISSUE TITLE
how to use datashader to generate html file without Jupyter Notebook

### ISSUE THREAD

**Issue by gandroz** [pyviz/holoviews#2804]
How can I use the datashader to output in a html file ?
I managed to output an holoviews image into a file:

    img = generate_image()  # generate a 600x1000 image
    hv_image = hv.Image(img.astype('float64'))
    rg = regrid(hv_image)
  
    renderer = hv.renderer('bokeh')
    plot = renderer.get_plot(hv_image).state
    output_file("graph.html")
    show(plot)
    --or--
    renderer = hv.renderer('bokeh').save(hv_image, 'graph')

however, when I use the datashader, it does not work

    img = generate_image()  # generate a 600x1000 image
    hv_image = hv.Image(img.astype('float64'))
    rg = regrid(hv_image)
    shaded = shade(rg, cmap=viridis, normalization='linear')
    layout = shaded.opts(plot=dict(width=1000,
                                   height=600,
                                   xaxis=None,
                                   yaxis=None))

    renderer = hv.renderer('bokeh')
    plot = renderer.get_plot(layout).state  # neither  plot = renderer.get_plot(datashade(hv_image)).state
    output_file("graph.html")
    show(plot)
    --or--
    renderer = hv.renderer('bokeh').save(layout, 'graph')

This works perfectly in a notebook, but how to output in a html file ?

**[EDIT]**
I got an error when opening the file graph.html:

> Uncaught TypeError: Cannot read property 'get_client_comm' of undefined
    at eval (eval at get (bokeh-0.12.16.min.js:1), <anonymous>:57:38)
    at i.execute (bokeh-0.12.16.min.js:1)
    at e.<anonymous> (bokeh-0.12.16.min.js:1)
    at e.t.emit (bokeh-0.12.16.min.js:1)
    at e.emit (bokeh-0.12.16.min.js:1)
    at e._setv (bokeh-0.12.16.min.js:1)
    at e.setv (bokeh-0.12.16.min.js:1)
    at e._layout (bokeh-0.12.16.min.js:1)
    at e._layout (bokeh-0.12.16.min.js:1)
    at e._do_layout (bokeh-0.12.16.min.js:1)

the image is displayed when I open the console in Chrome for example, but I cannot zoom in or use any bokeh feature due to this error

**Comment by gandroz** [comment]
Juste read this in the doc:

> Unfortunately, a static approach like this cannot support any HoloViews object that uses DynamicMap (either directly or via operations that return DynamicMaps like decimate , datashade , and rasterize ). Anything with DynamicMap requires a live, running Python server to dynamically select and provide the data for the various parameters that can be selected by the user. Luckily, when you need a live Python process during the visualization, the Bokeh server provides a very convenient way of deploying HoloViews plots and interactive dashboards in a scalable and flexible manner. 

[Documentation](http://holoviews.org/user_guide/Deploying_Bokeh_Apps.html)

**Comment by philippjfr** [comment]
This is definitely a bug, the note you pasted refers to interactive features that require a server but the JS code should not error when those features are not available.

**Comment by philippjfr** [comment]
For now I'd just recommend ``rg = regrid(hv_image)`` with ``rg = regrid(hv_image, dynamic=False)``.

**Comment by gandroz** [comment]
Thanks ! the image is well displayed now.

**Comment by philippjfr** [comment]
This was fixed.
