### ISSUE TITLE
Bokeh Widget and AdjointLayout integration

### ISSUE THREAD

**Issue by seanytak** [pyviz/holoviews#2846]
I am trying to append an AdjointLayout of a Scatter plot with two supporting histograms to a Bokeh dashboard. However, whenever trying to incorporate the two in a single row, the Bokeh widgets encounter display issues and the AdjointLayout never scales. Is this the current expected behavior or is here a different approach I need to take to currently accomplish this?

Minimal Example of the problem:
```
import numpy as np
import pandas as pd

import holoviews as hv
from bokeh.layouts import layout
from bokeh.models import Select
from bokeh.io import curdoc

renderer = hv.renderer('bokeh').instance(mode='server')

np.random.seed(10)
data = np.random.rand(100,4)

opts = {}
opts['color_index'] = 2
opts['size_index'] = 3
opts['scaling_factor'] = 50
points = hv.Points(data, vdims=['z', 'size']).opts(plot=opts)

fields = ['berry', 'cherry', 'dairy']
x = Select(title='X-Axis:', value=fields[0], options=fields)
y = Select(title='Y-Axis:', value=fields[1], options=fields)

dashboard = points + points[0.3:0.7, 0.3:0.7].hist()

app = renderer.get_plot(dashboard).state

dashboard = layout([
    [[x, y], app],
])

curdoc().add_root(dashboard)
```
Using Bokeh 0.13.0 and Holoviews 1.10.5

![image](https://user-images.githubusercontent.com/23182629/42067143-6e469bc4-7ae0-11e8-972f-ab9b8b82c4da.png)

**Comment by philippjfr** [comment]
I already asked this on StackOverflow but could you elaborate on what is going wrong for you? When I try the code both the widgets and the plots render correctly, although they don't do anything since the widgets and plots are not linked in any way.

**Comment by seanytak** [comment]
So I'd like to use the 'scale_width' option that Boekh offers to dynamically resize the content. However the layout I'm trying to produce here appears to only work with 'fixed'. The layout I'm trying to achieve would look like this:

![image](https://user-images.githubusercontent.com/23182629/42069527-0671e202-7aee-11e8-9d5f-78ee6b8a0ca7.png)

This appears to only be a problem when I try to include the AdjointLayout of the Scatter + Histogram whereas the standalone Scatter plot works fine.

**Comment by philippjfr** [comment]
Mostly a usage question. Also we now support responsive sizing options in bokeh. Generally I'd recommend using Panel for this kind of thing now though.
