### ISSUE TITLE
Broken logo?

### ISSUE THREAD

**Issue by jbednar** [pyviz/holoviews#2862]
I'm very confused by the file doc/_static/holoviews_logo.png.  It appears to be used in doc/conf.py and thus somewhere in the website:

```
./doc/conf.py:92:html_logo = '_static/holoviews_logo.png'
```
Yet it's a very outdated image that I don't see anywhere on holoviews.org:

![image](https://user-images.githubusercontent.com/1695496/42399531-bcb4cf02-8133-11e8-9edb-bde55b4fa50a.png)

Presumably it should be deleted, but as I'm confused about why it's not causing problems, I haven't done so.

**Comment by jbednar** [comment]
In any case I think our sites should just use "logo.png" so that all sites can share the same setup; no need to update conf.py every time we make a new project...

**Comment by philippjfr** [comment]
This was fixed.
