### ISSUE TITLE
Confliction with the BeakerX library in JupyterLab

### ISSUE THREAD

**Issue by dclong** [pyviz/holoviews#2876]
I found that the HoloViews library (for visualization) doesn't work as expected (plots are floating over the notebook rather embedded in the notebook) after installation of BeakerX. I tried to reinstall HoloViews after installation of BeakerX, but still came across the same issue. Below are details of related packages. 

Details:
OS: Ubuntu 16.04
JupyterLab: 0.32   (install by conda)
BeakerX: 1.0.0   (install by conda)
HoloViews: 1.10.7   (install by conda)

Perhaps the HoloView dev can talk to the BeakerX dev to figure what happened?

**Comment by philippjfr** [comment]
I imagine this has something to do with the precedence of mime renderers. Do you know if BeakerX register a mime renderer for JS code? If so BeakerX is also likely to break once JupyterLab 0.33 is released.

**Comment by philippjfr** [comment]
@dclong I have just published jupyterlab_pyviz 0.5.3, would you mind trying that with BeakerX?

**Comment by dclong** [comment]
@philippjfr Thank you! I tried but still came across the same issue.

**Comment by dclong** [comment]
@philippjfr This issue is appearing again in JLab 0.34.8. Would you help reopen this issue? I don't have permission to reopen it.

**Comment by philippjfr** [comment]
Could you also report your `jupyterlab_pyviz` extension version?

**Comment by dclong** [comment]
@philippjfr How do I check the version of `jupyterlab_pyviz`? I think I'm using the latest version.

**Comment by philippjfr** [comment]
The output of this would help:

```
jupyter labextension list
```

**Comment by dclong** [comment]
```
chdu@cc9abefa5cd3:~$ jupyter labextension list
JupyterLab v0.35.0
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        @mflevine/jupyterlab_html v0.1.4  enabled  OK
        @pyviz/jupyterlab_pyviz v0.6.3  enabled  OK
        beakerx-jupyterlab v1.1.0  enabled  OK
        nbdime-jupyterlab v0.4.0  enabled   X

   The following extension are outdated:
        nbdime-jupyterlab

   Consider running "jupyter labextension update --all" to check for updates.

chdu@cc9abefa5cd3:~$
```

**Comment by dclong** [comment]
@philippjfr How did you fix the issue in the release jupyterlab_pyviz 0.5.3? Any thing I can help to fixe this issue?

**Comment by philippjfr** [comment]
>How did you fix the issue in the release jupyterlab_pyviz 0.5.3?

Could you clarify, what issue are you referring to? If you mean the problem with displaying plots at all, the problem was that JupyterLab added support for JS mime types which meant that we had to give our custom MIME type a lower (i.e. effectively higher) precedence of -1.

>Anything I can help to fix this issue?

I have pretty much zero bandwidth to debug issues with interactions other jupyterlab extensions, particularly because beakerx is seemingly a huge thing to compile and has caused me nothing but problems even disregarding the poor interaction with our extension. Therefore any investigation you can do on this front would be hugely appreciated, but unfortunately I have no pointers to figure out how to even start debugging the problem.

**Comment by falconair** [comment]
I just came across the issue of floating plots. I don't have BeakerX so the title of this issue is too specific for the bug.

I'm seeing this on my PC so I upgraded all packages (via conda).

Here is some detail:
```
jupyter labextension list
JupyterLab v0.34.9
No installed extensions
```

Here are the relevant versions: 
```
conda list|egrep -e "holoviews|bokeh|jupyter"
bokeh                     1.0.1                 py36_1000    conda-forge
holoviews                 1.10.9                     py_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0                    py36_1
jupyter_core              4.4.0                    py36_0
jupyterlab                0.34.9                   py36_0
jupyterlab_launcher       0.13.1                   py36_0
```

**Comment by philippjfr** [comment]
The issues here should be resolved, please reopen if they reappear.
