### ISSUE TITLE
Groupby for hv.Dataset().to.distribution errors

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoviews#2886]
But works with hvplot
```
import numpy as np
import hvplot.pandas
import holoviews as hv
hv.extension('bokeh')

from bokeh.sampledata.autompg import autompg as df

title = "MPG by Cylinders and Data Source, Colored by Cylinders"
df.hvplot.kde('mpg', 'cyl')
hv.Dataset(df).to.distribution('mpg', ['cyl'])
```

```
~/anaconda3/envs/bokeh-dev/lib/python3.6/site-packages/param/__init__.py in _check_bounds(self, val)
   1171             if min_length is not None and max_length is not None:
   1172                 if not (min_length <= l <= max_length):
-> 1173                     raise ValueError("%s: list length must be between %s and %s (inclusive)"%(self._attrib_name,min_length,max_length))
   1174             elif min_length is not None:
   1175                 if not min_length <= l:

ValueError: kdims: list length must be between 1 and 1 (inclusive)
```

**Comment by marcbernot** [comment]
It is not an error, you need to conform to the syntax of the .to() method.
You operate a groupby on 'cyl' with this line :  
`df.hvplot.kde('mpg','cyl')`
To do the same in holoviews you can use this syntax : 
`hv.Dataset(df).to(hv.Distribution,'mpg', None,'cyl').overlay()`
or
`hv.Dataset(df).to(hv.Distribution,kdims='mpg',groupby='cyl').overlay()`
Check [gridded datasets groupby section](http://holoviews.org/user_guide/Gridded_Datasets.html#) to   learn more about the .to() method.

**Comment by ahuang11** [comment]
Ah okay; I guess I'm used to `hv.Dataset(df).to.curve('mpg', 'cyl', [])` and `hv.Dataset(df).to.bars('mpg', 'cyl', [])` instead of `hv.Dataset(df).to(hv.Curve, 'mpg', 'cyl', [])` so I expected hv.Distribution would work similarly. Thanks!
