### ISSUE TITLE
HV to use Bokeh sources directly

### ISSUE THREAD

**Issue by gherka** [pyviz/holoviews#2978]
Since there is such a tight integration between Holoviews and Bokeh, is it possible to use Bokeh ColumnDataSource (and by extension AjaxDataSource) to feed the HV plots? A trivial example would be:

```
xs = range(-10,11)
ys = [100-x**2 for x in xs]
source = ColumnDataSource({'xs':xs, 'ys':ys})

#Bokeh
p = figure(plot_width=400, plot_height=400)
p.line('xs', 'ys', source=source)
show(p)

#Current Holoviews
curve = hv.Curve((xs, ys))
curve

#Proposed Holoviews
curve = hv.Curve(('xs', 'ys'), source=source)
curve
```

**Comment by ahuang11** [comment]
You could call the source data like this:

```
curve = hv.Curve(source.data, 'xs', 'ys')
curve
```

**Comment by gherka** [comment]
@ahuang11
Thanks! It works fine for vanilla CDS, but when I tried the same with AjaxDataSource, there is nothing in source.data (yet - my guess is that it's populated later in the runtime?) Here's a slightly less trivial example of where I hoped to use HV with Bokeh's AjaxDataSource:

```
source = AjaxDataSource(data_url='http://gherka.pythonanywhere.com/data', method='GET')

p = figure(plot_height=300, plot_width=800, background_fill_color="lightgrey",
           title="Data delivered via Ajax from a RESTful API")
p.circle('x', 'y', source=source)
show(p)
```
The advantage (to my limited understanding) is that you can have a static HTML showing the visualisation and the data for it delivered remotely (in JSON), rather than it being embedded in the HTML. It would be nice to extend Bokeh with HV's functionality, like widgets for unused dimensions, rather than coding them in manually in Bokeh with CustomCS callbacks.

**Comment by ahuang11** [comment]
I'm not entirely sure what CDS/AjaxDataSource is, but here's a potential workaround?
![image](https://user-images.githubusercontent.com/15331990/45000560-cd4c4a00-af7a-11e8-9a1e-c0e62414ecd0.png)

```
import pandas as pd
import holoviews as hv

df = pd.read_json('http://gherka.pythonanywhere.com/data')
hv.Scatter(df)
```

**Comment by gherka** [comment]
Well...if you provide data to the plot this way, it'll still get embedded in the output HTML inside the Bokeh plot script tag, all 1000 points. 

```
from bokeh.plotting import figure, show, output_file
from bokeh.models.sources import AjaxDataSource, ColumnDataSource
import pandas as pd
import holoviews as hv

output_file('scatter.html')
df = pd.read_json('http://gherka.pythonanywhere.com/data')
source = ColumnDataSource(df)
p = figure(plot_height=300, plot_width=800)
p.circle('x', 'y', source=source)
show(p)
```

However, if instead you use AjaxDataSource, then you're not including any actual data in the HTML, just a reference to the URL where to pick it up from. 

```
output_file("ajax_scatter.html")
source = AjaxDataSource(data_url='http://gherka.pythonanywhere.com/data', method='GET')
p = figure(plot_height=300, plot_width=800)
p.circle('x', 'y', source=source)
show(p)
```

It then has a number of advantages, like updating data for the graph remotely, small file size to transfer over email, etc.

**Comment by ahuang11** [comment]
Ah, that makes a lot of sense; thanks for introducing me to that! I'm not sure if there's a HoloViews equivalent to that, but probably related http://holoviews.org/user_guide/Streaming_Data.html

**Comment by philippjfr** [comment]
In theory you could do something like @ahuang11 suggested to initialize the plot and then swap out the data source using a hook:

```python
from bokeh.plotting import figure, show, output_file
from bokeh.models.sources import AjaxDataSource, ColumnDataSource
import pandas as pd
import holoviews as hv

df = pd.read_json('http://gherka.pythonanywhere.com/data')

def cds_swap_hook(plot, element):
    source = AjaxDataSource(data_url='http://gherka.pythonanywhere.com/data', method='GET')
    renderer = plot.handles['glyph_renderer']
    renderer.data_source = source
    renderer.view.source = source

hv.Scatter(df).options(finalize_hooks=[cds_swap_hook])
```

Bit hacky but I'd have to think about it a bit more to suggest something better.

**Comment by gherka** [comment]
Thanks a lot for comments and suggestions. In the end I decided to go with pure Bokeh as exporting Holoviews' HoloMap into a static HTML didn't work. Rather than that, I tweaked the API to accept parameters so that the API call would return the filtered data:

```
initial_state = r'http://gherka.pythonanywhere.com/data/HB=NHS Tree&Sex=Male&Measure=Big Count'
source = AjaxDataSource(data_url=initial_state, method='GET')

p = figure(plot_width=800, plot_height=300)

p.line('Year', 'Value', source=source)
p.grid.visible = False
p.title.align='center'

select_hb = Select(title="Select Health Board:", value="NHS Tree",
                options=["NHS Tree", "NHS Rock", "NHS Train"])

select_measure = Select(title="Select measure:", value="Big Count",
                       options=["Big Count", "Small Rate"])

callback_hb = CustomJS(args=dict(source=source), code="""
    if (typeof measure === 'undefined'){
    measure = 'Big Count'; //default value
    };

    hb = cb_obj.value;
    var new_url = `http://gherka.pythonanywhere.com/data/HB=${hb}&Sex=Male&Measure=${measure}`;

    fetch(new_url).then(function(response) { return response.json(); })
    .then(function(result) {source.data = result;})
    
    source.change.emit();
""")

callback_measure = CustomJS(args=dict(source=source), code="""
    if (typeof hb === "undefined"){
    hb = 'NHS Tree'; //default value
    };

    measure = cb_obj.value;
    var new_url = `http://gherka.pythonanywhere.com/data/HB=${hb}&Sex=Male&Measure=${measure}`;

    fetch(new_url).then(function(response) { return response.json(); })
    .then(function(result) {source.data = result;})

    source.change.emit();
""")

select_measure.js_on_change('value', callback_measure)
select_hb.js_on_change('value', callback_hb)

layout = column(row(select_hb, select_measure),p)
show(layout)
```
![ajax filters](https://user-images.githubusercontent.com/4526926/45166681-7e5b1a80-b1ef-11e8-896f-5edfa51a5455.png)
