### ISSUE TITLE
Plot a line by specifying slope and intercept?

### ISSUE THREAD

**Issue by dclong** [pyviz/holoviews#2988]
Is there an simple way to plot a line by specifying slope and intercept? VLine and HLine are extreme cases. In R there's a function named abline which can do this easily. 

https://www.rdocumentation.org/packages/graphics/versions/3.5.1/topics/abline

**Comment by philippjfr** [comment]
There isn't currently but I'd be in favor of implementing something like it. May not be simple though since I don't think provides such a primitive so you'd have to make one yourself with a finite extent line.

**Comment by rjp23** [comment]
This might be relevant

https://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html#slopes
