### ISSUE TITLE
GridSpace shared_xaxis/shared_yaxis with non-default height/width

### ISSUE THREAD

**Issue by wabu** [pyviz/holoviews#2992]
GridSpaces don't show correctly when shared_axis is used in combination with non-default height/weight (in bokeh backend, mathplotlib does not apply width/height at all)

```
import numpy as np
import holoviews as hv
hv.extension('bokeh')

hv.HoloMap({(x,y): hv.Curve(np.random.rand(10))
                     .options(width=100, height=50)
            for x in [1,2,3] 
            for y in [1,2,3]}, 
           kdims=['x', 'y']).grid().options(shared_xaxis=True, 
                                            shared_yaxis=True)
```

holoviews: 1.10.7
bokeh: 0.13.0

![grid-shared-axis-width-height](https://user-images.githubusercontent.com/39164/45355648-2f333200-b5c1-11e8-8876-cb7f76ec23fc.png)

**Comment by philippjfr** [comment]
This will soon be fixed by specifying a frame_height and frame_width.
