### ISSUE TITLE
Handling non-orthogonal key dimensions

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#301]
Implicit in the idea of showing multiple sliders at once, say _A_,_B_,_C_ is that for any setting of slider _A_ (say)  you can choose any setting you want for _B_ and _C_. In other words, this assumes the sliders can be independent and there are no constraints between the sliders e.g if the value of a particular slider is some function of the other slider positions.

This is true of many applications but is not the most general case. If you have data where this assumption doesn't hold, it is tricky to explore the full dataset as you have no guide to what particular slider positions have data available and which do not. Furthermore you can move the sliders and get 'stuck' without knowing which slider to change in order to explore the rest of the data.

One proposal we have is to detect this condition (keys that are not on a grid) and warn the user to use one of the widgets that serializes the data into a single slider (e.g scrubber). A different proposal that we have just discussed is to detect this condition and automatically show a single 'index' slider instead.

This is a fairly quick job but the idea can be extended. In future, you could have the index slider shown together with all the normal sliders per key dimension. Moving the index slider along (the serialization) would set the position of the other sliders to the appropriate values. Then you could still move the independent sliders around (useful if the keys are _nearly_ on a grid). The index slider makes sure you always have a way to scrub through all the available data. 

Moving the independent sliders would not move the index slider (unlike the converse). Note that this more advanced proposal would need to be implemented in JavaScript and would take more time whereas the simple proposal can be done entirely in Python relatively quickly.

**Comment by jbednar** [comment]
I've been struggling with this problem myself, and I vote for doing the simple proposal right away, but also doing the more advanced proposal.  Part of the whole raison d'etre of HoloViews is to be able to explore large, multidimensional spaces, and the thing about such spaces is that they are often quite sparse, with meaningful things happening only in relatively local region of that space.  Providing good ways to explore sparsely (but potentially locally densely) populated spaces is very important.

**Comment by philippjfr** [comment]
Good summary of our discussion. One minor quibble:

> Furthermore you can move the sliders and get 'stuck' without knowing which slider to change in order to explore the rest of the data.

This was true of our original prototype but isn't the case anymore. Doing it that way turned out to be completely useless for precisely the reason you mentioned.

I've got one more alternative proposal just to throw it all out there. Instead of providing one useless Index widget it would also be possible, to format each key (i.e. multiple dimension values) into a string and use that as the index instead. That would require a dropdown menu though, which is probably not as useful.

The basic index suggestion is what I can get working very quickly and would be feasible before the next release.

**Comment by jbednar** [comment]
Why would the reformatted-key option require a dropdown menu?  Can't it be
a slider, with the value of the slider showing up as a string, but still
slidable (because whatever it is, it can be slid)?

**Comment by philippjfr** [comment]
Sure, it could be but the slider text field is often too small to handle even a single float value, a long string of multiple would be mostly obscured.

**Comment by jlstevens** [comment]
> It would also be possible to format each key (i.e. multiple dimension values) into a string and use that as the index instead.

Interesting suggestion although couldn't this end up being quite long (unless you use a tuple only) and be redundant with the title?  I think a dropdown would be unusable if you have lots of keys.

I was wondering if maybe you could hover over the slider and show a tooltip with the dimension values (which would be cool!) but I get the impression it isn't so easy. This seems the [closest example](http://www.jqwidgets.com/slider-with-tooltip/) I could find.

All in all, I think an index number isn't so bad as the dimensions are generally shown in the title.

**Comment by jbednar** [comment]
Will the positions of the other sliders show the value of the index slider?

**Comment by philippjfr** [comment]
In the more complex proposal they would, but that's probably a days work, so for this release it would just be the index.

**Comment by jbednar** [comment]
Sounds like it would make sense just to show the index in this release, and
then do the more complicated one.

**Comment by jlstevens** [comment]
Having had a very long discussion with Philipp, it is clear this issue is much thornier than we've made out in this issue so far!

Essentially, the cartesian is both a very special case (though people do use it a lot deliberately) *and* the only case when independent sliders make sense. If as soon as it isn't a cartesian product, you always switch to the index slider, then that will happen in almost every case a cartesian product hasn't been deliberately used (not helpful!).

We now think there are three cases:

* Cartesian product (easy - an all-to-all relationship).

* Contiguous subspaces: given the other values of the other sliders, there is a single small portion of the space that needs to be accessible. This is more general than hierarchical sliders which impose an ordering to say which values are more 'important' than others (so you select the subspace according to the more 'important' dimensions). Each level of the hierarchy has a one-to-many relationship with the level below it.

* The general case: lots of disconnected 'islands' that are conditional on the state of all the other sliders. This is the many-to-many relationship (or some-to-some if it is sparse!) which is awkward to work with (and people prefer to avoid even if real data is often like this!).

We've come up with the following proposal:

* We can automatically detect if the keys imply a hierarchical relationship, working in the declared order of the key dimensions. If this happens, we can use a contiguous subspace approach and also know the precedence of the sliders. One possible future idea is to allow the user to 'lock' sliders to decide precedence, allowing the more general contiguous subspace approach.

* If it isn't hierarchical, we use independent sliders. Cartesian works nicely but if values are missing, we have a blank frame. In future, it would be nice to give a hint about valid and invalid spaces when dragging the slider. E.g the slider bar could go red when dragged over regions with no data. This is a completely general approach but only works well with the cartesian case because it gets hard to find any data at all if the dataset is sparse (the index slider is really just a way of handling sparsity).

The hope here is that the hierarchical/contiguous subspace case is common enough to help tackle sparse data in a useful way.

**Comment by philippjfr** [comment]
Okay after our discussion last night I've now implemented the hierarchical suggestion. The widget code now detects if a dimension has a one-to-many mapping to the following dimension and if that's the case then it updates the following slider/dropdown with just the values that are available in that subspace. This should solve all our current issues with the widgets but some of the other suggestions could definitely still be useful at a later stage.

Note the solution I've implemented isn't fully general, the hierarchical dimensions need to appear consecutively for this to work, i.e. if your key dimensions are Country and Continent (rather than Continent and Country) it will not detect the hierarchical relationship between them.

**Comment by philippjfr** [comment]
Here is a nice little example that will demonstrate this:

```python
af_countries = ['Gambia', 'Uganda', 'Zimbabwe']
eu_countries = ['Germany', 'UK', 'Ireland']
countries = zip(['Africa']*3, af_countries)+zip(['Europe']*3, eu_countries)
years = range(1960, 1990)
hmap = hv.HoloMap({(cont, country, y): hv.Image(np.random.rand(10, 10))
                   for cont, country in countries for y in years}, kdims=['Continent', 'Country', 'Year'])
hmap
```

**Comment by philippjfr** [comment]
There should be something visual to indicate the relationship between the dimensions. While it's pretty obvious in the continents/countries example it might not be as clear in other cases. Not sure what best expresses the relationship though.

I also don't want to sink too much work into the current widgets, if we're eventually switching to PhosphorJS anyway.

**Comment by jlstevens** [comment]
> Okay after our discussion last night I've now implemented the hierarchical suggestion.

Great! I am very happy we can improve the behavior substantially in an automatic way without introducing any new interface for the user to learn. We do need to document this feature though..something like "you can toggle hierarchical widgets (when applicable) by ordering the key dimensions according to their position in the hierarchy" (then follow up with a concrete example).

> I also don't want to sink too much work into the current widgets, if we're eventually switching to PhosphorJS anyway.

I totally agree. As for showing the relationship visually, that would be nice but I can't think of any quick and trivial way  to do that. Maybe file an issue and we can address this at a later time, hopefully after we've integrated with Phosphor JS!

**Comment by jbednar** [comment]
I'm ok with removing the current code for hierarchical dimension handling from HoloViews, at least for now while reimplementing widgets, but I still think that giving users ways to explore multidimensional spaces easily is very much a core function of HoloViews.  So we'll have to revisit it at some point, preferably automatically in HoloViews from a user's perspective, but in any case at least laying out clearly how a PyViz user would handle this (common) case with any available tool.

**Comment by philippjfr** [comment]
I had a discussion with Jean-Luc recently where I pointed out that since the Panel refactor the entire cross-product of the parameter space is now exported. This fixed various issues where sparse parameter spaces would not appropriately hide elements. Overall supporting non-orthogonal parameter spaces automatically is not really feasible and resulted in *a lot* of complexity, which was quite brittle and had many bugs. Since we now have parameter dependencies and Panel widgets non-orthogonal parameter spaces can now be expressed in various ways and we are no longer going to support them in HoloViews.
