### ISSUE TITLE
Setting y_range on datashader plots with large spikes causes jupyter kernel to crash

### ISSUE THREAD

**Issue by miksch** [pyviz/holoviews#3012]
## Description

When trying to plot data with very large spikes (values >100x higher than the average) in datashader + holoviews, setting y_range causes the kernel to shut down either when the plot is being produced or after zooming in once or twice. No errors are thrown in the console before the kernel dies. I thought it was an issue with datashader itself that has been recently merged to the main branch https://github.com/pyviz/datashader/pull/644, but I tried the most recent branch of both holoviews and datashader and it still didn't work.

I've also tried:
* dask and pandas dataframes
  * same result
* plotting one variable at a time 
  * kernel dies when plotting variables with large spikes
* using hv.Curve without datashade 
  * works fine, very slow with ~1.7 million points though
* using hv.Scatter with datashade 
  * also works fine, but isn't useful for my application

For now I've filtered the data values to a smaller range (0-1,500), but if I zoom in/out too quickly or too much it still crashes the kernel. Here's what the graph looks like before zooming in.

![screen shot 2018-09-22 at 6 22 14 pm](https://user-images.githubusercontent.com/7525469/45922863-888a4380-be94-11e8-8ee0-71a32dc10168.png)

## Errors and warnings

![screen shot 2018-09-22 at 3 07 02 pm](https://user-images.githubusercontent.com/7525469/45921761-3be53f00-be79-11e8-8b55-4b37abe07eb9.png)

Additional error in console when using dask after restarting kernel:
```
/Users/miksch/anaconda3/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 48 leaked semaphores to clean up at shutdown
  len(cache))
```

## How to reproduce

Minimal test example, with last snippet being run in a separate cell:

```python
import pandas as pd
import dask.dataframe as dd
import numpy as np
import multiprocessing

from holoviews.operation.datashader import datashade
import holoviews as hv

hv.extension('bokeh')

npart = multiprocessing.cpu_count()
num_obs = 1728000
start_date = '2018-05-04T00:00'
test_df = pd.DataFrame(data = {'no_spikes':np.random.uniform(-1,1,num_obs)*1e1,
                              'spikes':np.random.uniform(-1,1,num_obs)*1e15},
                      index = pd.DatetimeIndex(start=start_date,periods=num_obs,freq='50ms',name='TIMESTAMP')
                      )
dask_df = dd.from_pandas(test_df, npartitions=npart-2)
```

```python
%%opts RGB [width=800]

def create_curve(data,var,color,lim=None):
    ts_var = 'TIMESTAMP'
    curve = hv.Curve((data.index,data[var]),ts_var,var)
    if lim:
        ds = datashade(curve,min_alpha=100,cmap=color,y_range=lim)
    else:
        ds = datashade(curve,min_alpha=100,cmap=color)
    return ds

test_vars = {'no_spikes':{'color':'#9aae07','lim':(-15,15)},
             'spikes':{'color':'#0b8b87','lim':(-20,20)}, #'lim':None
            }

lines = [create_curve(dask_df,v,test_vars[v]['color'],test_vars[v]['lim']) for v in test_vars]

hv.Layout(lines).cols(1)
```

If I set ```'lim':None``` in spikes I don't have any issues, but setting a smaller y_range (e.g. -20,20) will kill the kernel after zooming in once or twice.

## Your environment

Note: I also tested this with the current master branch of holoviews (holoviews-1.11.0a5.post8+g85bb3dad) and datashader (datashader-0.6.8.post5+g8f6e5ba).

#### Packages

``` 
Name                    Version                   Build  Channel
dask                      0.19.1                   py36_0  
datashader                0.6.6                         0    conda-forge
jupyter                   1.0.0                    py36_6  
holoviews                 1.10.7                   py36_0   
numpy                     1.15.1          py36_blas_openblashd3ea46f_1  [blas_openblas]  conda-forge
pandas                    0.23.4           py36h6440ff4_0 
python                    3.6.6                hc167b69_0  
```

#### OS version

```
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
```

#### Chrome version

```
Version 69.0.3497.100 (Official Build) (64-bit)
```

**Comment by philippjfr** [comment]
This sounds like this issue in datashader: https://github.com/pyviz/datashader/issues/570

This was recently fixed, could you try updating to datashader 0.6.8 using:

```
conda install -c pyviz datashader
```

**Comment by philippjfr** [comment]
Ping @jbednar, how extensively did you test it after merging the fix?

**Comment by jbednar** [comment]
Unfortunately, due to the nature of the original problem, it was not possible to test exhaustively -- we were able to find specific cases that were problematic and capture them in the test suite, but the original observations were from interactive zooming events that we could only approximate.  So although I was unable to find a problem after applying the fix, that doesn't mean that there *aren't* other fixes needed, which is something @ceball was also concerned about.

**Comment by ceball** [comment]
Oh, I've just seen there's a test example above too (I'm reading backwards from when I got mentioned!). I'd be happy try that out over the next few days.

**Comment by philippjfr** [comment]
This is a datashader issue which was resolved in https://github.com/pyviz/datashader/pull/683
