### ISSUE TITLE
holoviews dynamicmap widgets don't show sliders

### ISSUE THREAD

**Issue by rabernat** [pyviz/holoviews#3027]
Since our latest update on pangeo.pydata.org, holoviews dynamicmap widgets have been broken.

```
import holoviews as hv
import numpy as np
hv.extension('bokeh', width=100)

def fm_modulation(f_carrier=220, f_mod=220, mod_index=1, length=0.1, sampleRate=2000):
    sampleInc = 1.0/sampleRate
    x = np.arange(0,length, sampleInc)
    y = np.sin(2*np.pi*f_carrier*x + mod_index*np.sin(2*np.pi*f_mod*x))
    return hv.Curve((x, y), 'Time', 'Amplitude')

%%opts Curve [width=600]
f_carrier = np.linspace(20, 60, 3)
f_mod = np.linspace(20, 100, 5)

curve_dict = {(fc, fm): fm_modulation(fc, fm) for fc in f_carrier for fm in f_mod}

kdims = [hv.Dimension(('f_carrier', 'Carrier frequency'), default=40),
         hv.Dimension(('f_mod', 'Modulation frequency'), default=60)]
holomap = hv.HoloMap(curve_dict, kdims=kdims)
holomap
```

![image](https://user-images.githubusercontent.com/1197350/46259755-048f1780-c4a3-11e8-9431-7c198a560484.png)

We are using holoviews version 1.10.7.

Any idea what is going on here?

**Comment by rabernat** [comment]
I discovered almost by accident that I can drag on the area to the right of the text boxes and manipulate the slider. The slider itself is invisible however.

**Comment by rabernat** [comment]
Also bokeh version 0.12.16

**Comment by rabernat** [comment]
Jupyterlab version is '0.34.2'. @pyviz/jupyterlab_pyviz v0.6.1

**Comment by philippjfr** [comment]
Thanks, I'll try to reproduce the exact setup.
