### ISSUE TITLE
Rasterize stutter on zoom

### ISSUE THREAD

**Issue by jsignell** [pyviz/holoviews#3038]
I have seen this issue a bunch of times and think it is related to many values being rasterized and the output showing up more than once in a notebook. 

![rasterize_stutter](https://user-images.githubusercontent.com/4806877/46378247-00145b80-c669-11e8-9d73-1c3d41e5c76a.gif)

sorry this gif is so slow

### To Repoduce
```python
import xarray as xr
import hvplot.xarray

path = 14
row = 32
pid = 'LC08_L1TP_014032_20160727_20170222_01_T1'
band = 8

url = f'https://storage.googleapis.com/gcp-public-data-landsat/LC08/01/{path:03d}/{row:03d}/{pid}/{pid}_B{band}.TIF'
da = xr.open_rasterio(url, chunks={'band': 1, 'x': 256, 'y':256})

ROI = da[0, 7000:8000, 7000:8000]
ROI.hvplot('x', 'y', width=400, rasterize=True) + ROI.hvplot('x', 'y', width=400, rasterize=True, cmap='viridis')
```

**Comment by jbednar** [comment]
If you are reusing the same rasterized or datashaded plot in two different cells in a notebook, they will share the same automatically-added `RangeXY()` stream that listens to Bokeh events in the plot(s) in which they are embedded. The two notebook cells will thus interact in very confusing ways.  The easiest solution is usually to create a *different* instance (call `rasterize()` or `datashade()` again) for each time you need such a plot.  Does that address your issue?

**Comment by philippjfr** [comment]
Yeah, this looks like there's some issue with the code that avoids events bouncing between plots.

**Comment by jsignell** [comment]
This has been fixed by now I think. Right @philippjfr?

**Comment by philippjfr** [comment]
Yes, this is fixed.
