### ISSUE TITLE
Holoviews plots not appearing in Internet Explorer 

### ISSUE THREAD

**Issue by Forander** [pyviz/holoviews#3103]
Hi,

my Holoviews plots are not appearing when opening a Jupyter Notebook saved HTML in Internet Explorer (works with Firefox and Chrome). I am using holoviews 1.10.7, IE 11 and Windows 7. 

Does anyone have any experience trying to resolve this issue?

Thanks.

**Comment by philippjfr** [comment]
Any chance you could look at the browser's development console and see if there are any errors?

**Comment by xavArtley** [comment]
https://docs.microsoft.com/en-us/scripting/javascript/misc/invalid-character-javascript

``` htmlObject.innerHTML = `<div class="hololayout row row-fluid"> ```

**Comment by philippjfr** [comment]
Thanks, that makes sense, template strings are not supported by older browsers. Will try to come up with a workaround.

**Comment by Forander** [comment]
Thanks Philipp and Xav for the replies. Yes it does seem to be the invalid character javascript error. I got a `SCRIPT1014: Invalid character` error in Internet Explorer console for each of my Holoviews plots.  

To clarify, should I insert the above code in holoviews/plotting/bokeh/renderer.py? I'm not sure how to proceed. Thanks,

Derek

**Comment by philippjfr** [comment]
I'll try to come up with a fix and include it as part of the 1.10.8 release we're planning to get out today.

**Comment by philippjfr** [comment]
Looks like the fix will have to be in ``pyviz_comms`` as that's where this error originates.
