### ISSUE TITLE
Slider in DynamicMap doesn't use the right step value?

### ISSUE THREAD

**Issue by flothesof** [pyviz/holoviews#3185]
Hey there,

I am trying to explore the values taken by a function depending on a parameter using a DynamicMap.
I have the impression that the discrete values taken by the slider don't really do what I expect. 
As a demonstration case, consider the following:
```python
hv.DynamicMap(lambda r: hv.Curve(([0, 1], [0, 1]), vdims=str(r)), kdims=['r']).redim.range(r=(0, 1)).redim.step(r=.0001)
```
*Note: I am using the value returned by the slider as a label in the vdims to quickly display the raw value given by the slider.*

What I expect in this case, since the step for my variable **r** is set to .0001, is to see values passed to the function that change in the fourth decimal. Instead the values I see only change in the second decimal.
![image](https://user-images.githubusercontent.com/2360669/48717241-49206f00-ec19-11e8-89b8-599f46bb8407.png)

Am I doing something wrong or is this the expected behaviour due to some rounding of values supplied by the slider?

Thanks for your help.

Florian

**Comment by xavArtley** [comment]
For your example you can do this:
`hv.DynamicMap(lambda r: hv.Curve(([0, 1], [0, 1]), vdims=str(r)), kdims=['r']).redim.values(r=np.arange(0,1,1e-4))`

**Comment by flothesof** [comment]
Thanks @xavArtley, that's a nice workaround for my case.

**Comment by philippjfr** [comment]
This is fixed on master, the formatter still formats to 2 decimal places by default but the slider does allow stepping correctly.
