### ISSUE TITLE
options for (hv.Distribution()*hv.Distribution())

### ISSUE THREAD

**Issue by ea42gh** [pyviz/holoviews#3282]
```
data=np.sort( np.random.normal(size=200))
(hv.Curve(        data)*hv.Curve(         data+1)).options(width=500)
(hv.Distribution(data)*hv.Distribution(data+1)).options(width=500)
```
The width setting is honored for the Curves (line 2)
but not for the Distributions (line 3)

**Comment by philippjfr** [comment]
This might explain some issues I've been seeing, the issue here is that the Distribution elements are converted to Area elements by a compositor operation during plotting which seemingly drops any options applied to the Overlay they were in.

**Comment by philippjfr** [comment]
Seems like this was fixed.
