### ISSUE TITLE
RGB and xarray/dask

### ISSUE THREAD

**Issue by jsignell** [pyviz/holoviews#3311]
I was working with an `xarray.DataArray` with shape MxNx3 stored as a `dask.array`: 

```python
>>> im
<xarray.DataArray 'getitem-5f1ebf179271ce04f7cbd4e90ec207be' (y: 256, x: 256, band: 3)>
dask.array<shape=(256, 256, 3), dtype=uint8, chunksize=(256, 256, 3)>
Coordinates:
  * y        (y) int64 0 1 2 3 4 5 6 7 8 ... 247 248 249 250 251 252 253 254 255
  * x        (x) int64 0 1 2 3 4 5 6 7 8 ... 247 248 249 250 251 252 253 254 255
  * band     (band) int64 0 1 2
```

When displaying the image using:

1) the plain dask array - `hv.RGB(im.data)` - the process hangs. 
2) the plain xarray object - `hv.RGB(im)` - the process fails because holoviews expects each channel (R, G, B) to be contained in its own data variable - `hv.RGB((im.x, im.y, im.sel(band=0), im.sel(band=1), im.sel(band=2))).options(invert_yaxis=True)`

For a comparison with matplotlib and full traceback:
https://gist.github.com/jsignell/4eeef0850708625e0b444db34600ea98

**Comment by philippjfr** [comment]
I'd be okay with allowing the ``ImageInterface`` which accepts ``NxMx3/4`` numpy arrays to accept dask arrays and DataArrays, but in the last case the coordinates would be ignored and would instead be generated from the RGB ``bounds``.

**Comment by philippjfr** [comment]
That said, the constructor could simply extract bounds from the coordinates.

**Comment by philippjfr** [comment]
Because the ImageInterface has no concept of coordinates on an array, it reads standard arrays, but as I said the constructor can extract ``bounds`` from the coordinates ahead of time.
