### ISSUE TITLE
Separating options to set figure vs. data aspect ratio

### ISSUE THREAD

**Issue by maxalbert** [pyviz/holoviews#335]
(Following up on a discussion on Gitter.)

Currently Holoviews has an option called `aspect` which, when given a numerical argument, controls the aspect ratio of the overall figure (e.g., `aspect=1` yields a square-shaped plot). It is also possible to set `aspect='equal'`, but this operates on the level of the actual data axis ranges and ensures that the data itself isn't distorted (similarly to matplotlib's `aspect='equal'`). Typically, setting `aspect=equal` does **not** lead to a square-shaped plot (if the x-axis range is different from the y-axis range).

Thus `aspect=1` and `aspect='equal'` do two conceptually very different things and are effectively orthogonal to each other. You could even consider applying both to the same plot, e.g. to ensure that a subplot in a grid has a well-defined shape (say 3:1) but it still displays its data in a non-distorted way.

Moreover, given that many people will come to Holoview from matplotlib background I believe it is confusing that Holoview's `aspect` option has the same name as matplotlib's  option but works very differently. This breaks user expectations and can lead to frustration.

I suggest introducing a new option called `fig_aspect` which works on the figure level (and which would thus take over the role of the existing aspect option), and to make `aspect` work on the data level instead, as it is the case in matplotlib. This would allow something like the following:

```
%%opts Curve [fig_aspect=3 aspect='equal']
```

to achieve a 3:1 plot with non-distorted data.

One might even consider renaming the `aspect` option to `data_aspect` to be super clear about its meaning, but again this will lead to broken expectations for people coming from matplotlib so it's probably not a good idea. (Unless `aspect` and `data_aspect` are both allowed and simply aliases of each other?)

**Comment by philippjfr** [comment]
The ship on renaming aspect has sailed unfortunately so now there are ``aspect`` and ``data_aspect`` options, the former retains the semantics of scaling the size of the frame while the latter conforms to the semantics you've described here.
