### ISSUE TITLE
nteract/VScode plots rendering at the bottom of the window

### ISSUE THREAD

**Issue by StevenLi-DS** [pyviz/holoviews#3353]
Versions:
`nteract` : `0.12.3`
`holoviews` : `1.11.0`

Plots gernerated by `holoviews` rendered at the bottom of the window in `nteract` instead of right under each cell. 
![snipaste_184](https://user-images.githubusercontent.com/33796896/50466498-f2225e00-096b-11e9-9c95-d1f53c14530c.png)

![snipaste_839](https://user-images.githubusercontent.com/33796896/50466502-f77fa880-096b-11e9-9d0d-64fe56a5093e.png)

It does seem like a `holoviews` issue since `bokeh` behaves normally. 
![snipaste_583](https://user-images.githubusercontent.com/33796896/50466503-fb132f80-096b-11e9-9797-ebce565a813a.png)

**Comment by StevenLi-DS** [comment]
This also affects vscode python extension interactive tab:
![hv](https://user-images.githubusercontent.com/33796896/52482446-46ca1300-2b7f-11e9-9868-785c0e433fe4.gif)

**Comment by philippjfr** [comment]
Not that there is a workaround, you can get it working by setting the ``HV_DOC_HTML`` to True:

```python
import os
os.environ['HV_DOC_HTML'] = 'True'

import holoviews as hv

hv.extension('bokeh')

hv.renderer('bokeh').theme = 'dark_minimal'

hv.Curve([1, 2, 3])
```

![screen shot 2019-02-09 at 7 30 42 pm](https://user-images.githubusercontent.com/1550771/52525418-52155f80-2ca1-11e9-9632-36d7d521a364.png)

**Comment by philippjfr** [comment]
That env var also works for VS Code:

![screen shot 2019-02-09 at 8 03 28 pm](https://user-images.githubusercontent.com/1550771/52525738-e386d080-2ca5-11e9-94ec-9d5f2e96ba7e.png)

**Comment by philippjfr** [comment]
One solution here would be to make the type of the MIME bundles dependent on whether the frontend sends back an acknowledgement when the extension is loaded. If we did that then the custom mime type would only be published in JupyterLab and classic notebook and any other frontends would receive all the components as a single 'text/html' component.

**Comment by MarcSkovMadsen** [comment]
Just for the record. The code showcased by @philippjfr for holoviews in VS Code does not work for me.

I get

![image](https://user-images.githubusercontent.com/42288570/78777590-1b68d100-799a-11ea-9c18-06c972453547.png)

```python
import os
os.environ['HV_DOC_HTML'] = 'True'

import holoviews as hv

hv.extension('bokeh')

hv.renderer('bokeh').theme = 'dark_minimal'

hv.Curve([1, 2, 3])
```

**Comment by MarcSkovMadsen** [comment]
Bokeh code works though

```python
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
output_notebook()
plot = figure(plot_width=300, plot_height=300)
plot.line(x=[1,2,3], y=[1,2,3])
show(plot)
```

![image](https://user-images.githubusercontent.com/42288570/78777662-3d625380-799a-11ea-9efd-1d6d0ab9c733.png)

**Comment by philippjfr** [comment]
@MarcSkovMadsen Could you open a new issue in Panel?
