### ISSUE TITLE
slicing bar plot using values?

### ISSUE THREAD

**Issue by reckoner** [pyviz/holoviews#3359]
I have a simple bar chart with the horizontal labels as names `['john','alice','bob','mark']`. If I do

    b = Bars(...)
    b['alice':]

then, well I get the bars corresponding to `['alice','bob','mark']`? BTW, when I do this with

    b['a':]

it doesn't produce an error even though there is no labelled `a` bar.

Thanks!

**Comment by philippjfr** [comment]
To be honest I think this is expected, both `'alice'` and `'a'` are less than or equal to all the other strings.

**Comment by philippjfr** [comment]
Even during vectorized indexing I would expect an error here since it's simply checking if the value matches one of the supplied values.
