### ISSUE TITLE
Setting axis range does not work when subset of data is selected/sliced.

### ISSUE THREAD

**Issue by gregmuellegger** [pyviz/holoviews#3363]
Setting the range of the axis in the example below does not work as all data available is shown. This only appears if the data shown is sliced before. Setting the range on the full plot works as expected.

Below I would expect to see the x axis limitted from 2 to 5 (as set by redim), but be able to pan from 0 to 10 as this is the sliced area. However the redim change does not set the viewable area as it seems.

![image](https://user-images.githubusercontent.com/88278/50602062-85045080-0eb6-11e9-9e99-6396d63f4421.png)

copy & pasteable code:
```python
hv.Curve(range(100))[0:10].redim.range(x=(2, 5))
```

**Comment by philippjfr** [comment]
This is related to: https://github.com/ioam/holoviews/issues/566

**Comment by philippjfr** [comment]
This was fixed recently.
