### ISSUE TITLE
Launching a dynamic map leads to blank screen

### ISSUE THREAD

**Issue by williamma12** [pyviz/holoviews#3375]
Hi,

I am on Mac OS X 10.14 with python 3.6 with the latest version of holoviews from pip installed. When I create a dynamic map and launch it as a boken app with `renderer.app` if I have the option `sizing_mode` then I end up with a blank screen. This does not show up when I remove the option. 

A temporary workaround that I am using is just defining `height` and `width` attributes for the options.

Thanks!

**Comment by philippjfr** [comment]
Thanks for the bug report, bokeh is about to merge a major overhaul in the way layouts work and we'll be overhauling the code related to sizing modes, width/height and aspects once that is done.

**Comment by philippjfr** [comment]
We've now added support for responsive plots so there should be no need to use sizing_mode directly.
