### ISSUE TITLE
how to stop heatmap from ordering the axis labels | correlation matrix

### ISSUE THREAD

**Issue by ZiyadMoraished** [pyviz/holoviews#3386]
Hi,

whenever I plot a heatmap with unordered axises, the output gets ordered. 

I tried to change the data after creating the heatmap but it didn't work. any solution?

here is a reproducible code:
```
df= pd.DataFrame(
{'1':range(5), 
'0':range(5,10),
 '2':range(3,8),}
)
df_corr = df.corr()

print (df_corr )
```

1 | 0 | 2
-- | -- | --
1.000000 | 1.000000 | 0.558488
1.000000 | 1.000000 | 0.558488
0.558488 | 0.558488 | 1.000000

`hv.HeatMap((df_corr .columns.tolist(),df_corr .columns.tolist(), df_corr ))`

<img width="287" alt="heatmap" src="https://user-images.githubusercontent.com/9587667/51085228-4472c580-1747-11e9-8a99-376d096a51d4.PNG">
====

I tried the following:

```
data_edited = df_corr.to_dict(orient='split')

heatmap.data['x'] = np.array(data_edited['columns'])
heatmap.data['y'] = np.array(data_edited['index'])
heatmap.data['z'] = np.array(data_edited['data'])
```

and when plotting the heatmap, it gives the same result.

<img width="287" alt="heatmap" src="https://user-images.githubusercontent.com/9587667/51085244-93205f80-1747-11e9-8e81-8b43536eddce.PNG">

**Comment by ahuang11** [comment]
```
import pandas as pd
import hvplot.pandas

hv.extension('bokeh')
df = pd.DataFrame(
    {'1': range(5),
     '0': range(5, 10),
     '2': range(3, 8)}
)
df_corr = df.corr()
tst = df_corr.reset_index().melt(id_vars='index')
tst.hvplot.heatmap('index', 'variable', 'value').opts(colorbar=False)
```

![image](https://user-images.githubusercontent.com/15331990/51089277-7a9c4f00-171f-11e9-96b4-f590686e2696.png)

**Comment by philippjfr** [comment]
No longer sorted by default.
