### ISSUE TITLE
hover col for datetime.date is not formatted

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoviews#3393]
![image](https://user-images.githubusercontent.com/15331990/51162153-07dbc280-184a-11e9-8cf6-c780b66be04a.png)

`datetime.date(2020, 1, 1)`

maybe related to https://github.com/ioam/holoviews/issues/1261?

**Comment by philippjfr** [comment]
@ahuang11 This is not reproducible for me, at minimum I'd have to know the element type. I've encountered no issues with Curve or Scatter.
