### ISSUE TITLE
Move map tiles element gv.WMTS to hv.WMTS?

### ISSUE THREAD

**Issue by jbednar** [pyviz/holoviews#3404]
Together, HoloViews and GeoViews offer a great way to work with geo-located data, with powerful automatic projections to transform data as needed for display, various pre-defined geographic shapes, and so on.  Separating GeoViews from HoloViews is important because GV depends on a deep stack of often-problematic compiled dependencies (GDAL, Fiona, proj4, etc.). Drawing the line between the two packages based on geo/not-geo also makes sense semantically, making it simple for users to decide whether they need GeoViews.  (Do I ever want to reproject anything or plot it on a map? Then I need GeoViews.)

However, I'd like to propose making a less semantically clear but more pragmatic split: to move the implementation of gv.WMTS from GeoViews into HoloViews. At least in principle, gv.WMTS need not depend on the large geo stack, because it builds on Bokeh's standalone tile source support, and so it could be provided independently of the other GeoViews functionality. I think there is a very large class of users who want to plot their data on a map (e.g. the NYC taxi data) without thinking of themselves as "geo" users, without knowing or caring much about projections, and content with Web Mercator tile sources.  E.g. nearly all of the PyViz.org tutorial could be run without any of the geo stack, if gv.WMTS were available as hv.WMTS, making a much more practical and efficient starting point for nearly all users. That way only people who need the geo stack would ever have to install or debug it.

Can we consider moving tile server support into HoloViews, exposing it in GeoViews too (of course) but not requiring GeoViews?  Datashader already includes a lightweight utility (`datashader.utils.lnglat_to_meters`) for projecting data (ahead of time) into Web Mercator, and then we could push GeoViews into being for only those users who really do need the geo stack.

**Comment by jbednar** [comment]
I believe Jean-Luc would like to change the name of WMTS if we do that, to be something more meaningful, but I don't have any immediate suggestions.  hv.TileSource is also quite obscure, and hv.Tiles is confusing because of HexTiles.  Maybe hv.ImageTiles?  It's annoying that WMTS is tied specifically to the WebMercator projection, but I don't know if that needs to be in the name.

**Comment by poplarShift** [comment]
Just my two cents as a user: I like this idea, especially given that those tiles can't be reprojected using the `projection=` plot option (unless I'm missing something) and hence don't integrate super well with the rest of the geoviews Elements anyway.
For the name, wouldn't just spelling it out work? `WebMercatorTileSource`? Using something like `MapTileSource` may give people the idea that these are more flexible in use than they ar,e but would also work for me personally.

**Comment by philippjfr** [comment]
We've added Tiles to HoloViews a while ago.
