### ISSUE TITLE
cmap for Surfaces not working with plotly

### ISSUE THREAD

**Issue by neighthan** [pyviz/holoviews#3414]
You can see this in the documentation on [this page][docs]. The second example sets `cmap='fire'` but the image still uses the default "viridis" cmap. In a test of my own, I also get the viridis cmap regardless of what option I use (though there's still an error if I pass in a name that isn't a cmap at all). Any idea what's happening here? (changing cmaps for matplotlib still works)

Here's an example, pulled from that page, to test on:

```python
import numpy as np
import holoviews as hv
from holoviews import opts

hv.extension('plotly')

surface = hv.Surface(np.sin(np.linspace(0,100*np.pi*2,10000)).reshape(100,100))
surface.opts(cmap='fire', height=500, width=500)
```

I'm using `plotly` version 3.5.0 and `holoviews` 1.11.0.

[docs]: http://holoviews.org/reference/elements/plotly/Surface.html#plotly-gallery-surface

**Comment by philippjfr** [comment]
It appears that the surface graph in plotly does not accept a proper colormap, which means that the usual colormap handling code doesn't work. There holoviews code therefore seems to override the colorscale which sets the colormap to viridis whatever you do.

**Comment by jonmmease** [comment]
I think this is related to https://github.com/plotly/plotly.js/issues/3699.  It seems that the plotly.js surface trace is having trouble with length >= 256 colorscale specifications.

Plotly.js performs its own colorscale interpolation so I think we could safely sub-sample the HoloViews determined colorscales from 256 to 128 without ill effects.  How does that sound?
