### ISSUE TITLE
shared_axes docstring possibly wrong?

### ISSUE THREAD

**Issue by michaelaye** [pyviz/holoviews#3418]
Here's what the docstring for Curve(shared_axes) says at https://github.com/ioam/holoviews/blob/497035d6d9f7932aaba7dbcf2c6781e15bad93ee/holoviews/plotting/bokeh/element.py#L102-L104

but I presume that this is about sharing not inverting something?

**Comment by philippjfr** [comment]
Definitely wrong, will fix it in https://github.com/ioam/holoviews/pull/3410.
