### ISSUE TITLE
Range Limits for a Datetime Axis don't work with Datetime

### ISSUE THREAD

**Issue by magonreal** [pyviz/holoviews#3441]
When setting the x-limits of my datetime axis with 
`xlim = (datetime.datetime(2002, 1, 1), datetime.datetime(2004, 1, 1))`, 
I get the error message 
`ValueError: xlim: tuple element is not numeric: 2002-01-01 00:00:00.` 
The x-axis data comes from xarray and has `dtype='datetime64[ns]`

My workaround for entering the x-limits is
`xlim = (datetime.datetime(2002, 1, 1).timestamp() * 1000, datetime.datetime(2004, 1, 1).timestamp() * 1000)`

**Comment by philippjfr** [comment]
Should implement this in https://github.com/ioam/holoviews/issues/3441 and also allow date strings at the same time.

**Comment by philippjfr** [comment]
I believe this was fixed in https://github.com/pyviz/holoviews/pull/3491
