### ISSUE TITLE
Is it possible to put a newline in a figure title?

### ISSUE THREAD

**Issue by wmayner** [pyviz/holoviews#3449]
It seems that newlines are converted to spaces:
```python
hv.Curve([]).opts(title="This\nDoesn't\nWork")
```
How can I put newlines in the figure title?

Ideally, I'd like to make a subtitle for some of my figures (with a slightly smaller font).

**Comment by philippjfr** [comment]
Afaik this is not currently possible in the bokeh backend and may require a feature request in bokeh itself.

**Comment by philippjfr** [comment]
Yeah, this will be supported automatically when/if bokeh supports it so I'll close as there is no action we can take.
