### ISSUE TITLE
Asynchronous update in Holoviews not working (when using bokeh serve)

### ISSUE THREAD

**Issue by GregEndeavour** [pyviz/holoviews#3454]
I would like to create a program that continuously reads a csv file and updates the holoviews plot with the latest data. 

So, I tried to follow one of the examples taken from the pyviz tutorials ("Asynchronous updates using the tornado IOLoop": [ http://pyviz.org/tutorial/11_Streaming_Data.html ]), where synthetic data is created in a dataframe, and the graph is updated with the latest data. This seemed to be the closest example that I could find that was similar to my requirements, except that I don't want an upper limit on the number of updates possible. I simply want the plot to continuously be updated.

However, all that happens is that a new web browser page is opened, but no plot with updating data appears.

`from tornado.ioloop import PeriodicCallback`
`count = 0`
`buffer = Buffer(np.zeros((0, 2)), length=50)`

`def f():`
    `global count`
    `count += 1`
    `buffer.send(np.array([[count, np.random.rand()]]))`
    
`cb = PeriodicCallback(f, 100)`
`cb.start()`

`app = hv.DynamicMap(hv.Curve, streams=[buffer]).redim.range(y=(0, 1))`

`from bokeh.server.server import Server`
`server = Server({'/': app}, port=0)`
`server.start()`
`server.show('/')`

`from tornado.ioloop import IOLoop`
`loop = IOLoop.current()`
`loop.start()`

Could you let me know if there is a bug when running this from outside the Jupyter notebook, or whether there is another problem with the code above (incorrect implementation of the `bokeh serve` instance?).

**Comment by limx0** [comment]
I'm also having issues with a similar problem.

btw @GregEndeavour i think you want 

```python
plot = hv.DynamicMap(hv.Curve, streams=[buffer]).redim.range(y=(0, 1))

renderer = hv.renderer('bokeh')
renderer = renderer.instance(mode='server')
app = renderer.app(plot)

```

**Comment by limx0** [comment]
The following code, using `curdoc().add_periodic_callback(update, 500)`, works fine for me:

```python
import numpy as np
import panel as pn
import holoviews as hv

from bokeh.io import curdoc
from holoviews.streams import Pipe

hv.extension('bokeh')

class StreamingPlot:

    def __init__(self):
        self.pipe = Pipe(data=[])
        self.figure = hv.DynamicMap(hv.Scatter, streams=[self.pipe]).opts(framewise=True)

    def update(self, points):
        self.pipe.send(points)

plot = StreamingPlot()

def update():
    plot.update(np.random.randn(100).cumsum(axis=0))

pn.panel(plot.figure).servable()
curdoc().add_periodic_callback(update, 500)
```

However, like @GregEndeavour, I would like to use `loop.add_callback` (as I am using streamz). Can anyone provide any more insight here?

**Comment by GregEndeavour** [comment]
@limx0 thanks for your response. I indeed would like to have a loop that refreshes figures for the plot based on new data that is being saved in csv files, so `streamz` appeared to be the best way to feed this into live updatable graphs. Like you, I am also using an IDE (Spyder), rather than Jupyter Notebook.

The code that you described doesn't work on my side either. I am using exactly the above code, starting with line `import numpy as np` until `curdoc().add_periodic_callback(update, 500)`.

Please excuse my ignorance/level of understanding, however, shouldn't the server be called at the end of the code (i.e. like below):
`renderer = hv.renderer('bokeh')`
`renderer = renderer.instance(mode='server')`
`app = renderer.app(doc)`

`from bokeh.server.server import Server`
`server = Server({'/': app}, port=0)`
`server.start()`
`server.show('/')`

`from tornado.ioloop import IOLoop`
`loop = IOLoop.current()`
`loop.start()`

**Comment by philippjfr** [comment]
@GregEndeavour Panel sets of a server for you when you run ``.servable()`` so no need to set one up yourself. Just to double check how were you running the example above? You will want to launch it with ``panel serve script.py`` or ``bokeh serve script.py``.

**Comment by philippjfr** [comment]
It's not quite clear to me why you want to use a separate IOLoop, the main bokeh IOLoop should work just the same but correctly guards against improper modifications of the bokeh Document.

**Comment by GregEndeavour** [comment]
@philippjfr Thanks for your response (& sorry for the late response). I took your advice, and with the help of a colleague who is a lot more programming savvy, we were able to implement something that worked using: `pn.panel(plots).servable()`  , where `plots` is a list of `StreamingPlot` s. 
Many thanks for explaining the functionality of this part of Holoviews.
