### ISSUE TITLE
No plot when using Path with timeseries dataset

### ISSUE THREAD

**Issue by henriqueribeiro** [pyviz/holoviews#3464]
Hey, I'm trying to create a Path plot with a timeseries dataset but the output plot is totally empty.

For non timeseries data it works fine
```python
import holoviews as hv
import pandas as pd
hv.extension('bokeh')

ds = hv.Dataset([(0, 1), (1, 2), (2, 2), (3, 4)], ['x', 'y'])
hv.Path(ds, kdims=['x','y'])
```
![bokeh_plot 9](https://user-images.githubusercontent.com/3909112/52271547-df705100-293b-11e9-89c5-ce9b4dc2b817.png)

For timeseries
```python
ds = hv.Dataset([(pd.Timestamp('2018-01-01'), 1), (pd.Timestamp('2018-01-02'), 2), (pd.Timestamp('2018-01-03'), 2), (pd.Timestamp('2018-01-04'), 4)], ['x', 'y'])
hv.Path(ds, kdims=['x','y'])
```
![bokeh_plot 10](https://user-images.githubusercontent.com/3909112/52271622-10508600-293c-11e9-8253-351c2def6342.png)

Am I doing something wrong?

**Comment by philippjfr** [comment]
Definitely looks like a bug to me.

**Comment by gdk-gagan** [comment]
Hi, I am facing a similar issue with .to on Dataset. (trying to run the examples in scipy-holoviews-2017 tutorial notebook 04-working-with-tabular-data)

<img width="1680" alt="04-working-with-tabular-data-issue" src="https://user-images.githubusercontent.com/35355725/54631632-cab2cd00-4a52-11e9-98da-ef039f9d6ed4.png">

**Comment by philippjfr** [comment]
@gdk-gagan I doubt those are the same issue, could you try running the [PyViz](https://github.com/pyviz/pyviz) tutorial instead, it's a much more recent version of the same content.

**Comment by gdk-gagan** [comment]
Yep, got it, thanks @philippjfr
