### ISSUE TITLE
hv.Image warns about rtol

### ISSUE THREAD

**Issue by flothesof** [pyviz/holoviews#3465]
Hey there,
I'm trying to plot functions using the hv.Image element. I keep getting this warning:
```python traceback
WARNING:root:Image01077: Image dimension(s) x and y are not evenly sampled to relative tolerance of 0.001. Please use the QuadMesh element for irregularly sampled data or set a higher tolerance on hv.config.image_rtol or the rtol parameter in the Image constructor.
```

Here's my sample code:
```python
import numpy as np
import holoviews as hv
hv.extension('bokeh')

x = np.arange(-1, 1, 0.1)
y = np.arange(-1, 1, 0.1)
X, Y = np.meshgrid(x, y)
Z = np.sqrt(X**2 + Y**2) * np.cos(X)

hv.Image((X, Y, Z))
```
I tried following the recommandations about rtol. But even something like `hv.Image((X, Y, Z), rtol=1.)` will still give the warning, which I don't understand since my data is equally spaced.

As a side note, this works nicely with QuadMesh (hat-tip to the good warning!), but QuadMesh with the Bokeh backend displays gray cell borders which I don't want.

Thanks for your help.

Regards,
Florian

**Comment by philippjfr** [comment]
Oh, the warning is actually wrong in this case, Image is not meant to support 2D coordinate arrays at all. So the reason for the warning is because it's trying to find the sampling on a flattened version of the 2D coordinate arrays which are obviously not equally spaced.

**Comment by jbednar** [comment]
`arr.hvplot.image()` (which appears to be the default hvplot selectshere) checks to see if the coordinates explicitly encoded match the implicit coordinates computed by assuming equally spaced bins over the x and y ranges as Image rendering requires. If they match to within rtol, great!; otherwise you get a warning. If rtol is _nearly_ ok and just needs to be a little more relaxed, feel free to increase rtol, but usually what it means is that an Image is inappropriate and you should use `arr.hvplot.quadmesh()` instead.

**Comment by swawa** [comment]
hvplot.quadmesh() is **NOT** an adequad solution. It results in a ugly aliasing; see multiple comments:
[https://stackoverflow.com/questions/72448687/python-using-hvplot-quadmesh-for-xarray-data-shows-blended-colors-in-a-plot](url)
[https://discourse.holoviz.org/t/how-to-stop-param-image-warning/2934](url)
[https://discourse.holoviz.org/t/hvplot-reporting-inconsistent-chunks-on-xarray-dataarray/1690](url)

**Comment by michaelaye** [comment]
> hvplot.quadmesh() is **NOT** an adequad solution. It results in a ugly aliasing; see multiple comments: [https://stackoverflow.com/questions/72448687/python-using-hvplot-quadmesh-for-xarray-data-shows-blended-colors-in-a-plot](url) [https://discourse.holoviz.org/t/how-to-stop-param-image-warning/2934](url) [https://discourse.holoviz.org/t/hvplot-reporting-inconsistent-chunks-on-xarray-dataarray/1690](url)

your links are broken?

**Comment by swawa** [comment]
> 

now the links should work. I edited the post
