### ISSUE TITLE
hv.notebook_extension change the root logger setting

### ISSUE THREAD

**Issue by celliern** [pyviz/holoviews#3468]
When using the function `hv.notebook_extension`, the root logger settings change. As side effect, the log from other libraries are displayed, which is an annoying side effect.

Additional info for reproductibility:

```python
>>> import logging

>>> root_log = logging.getLogger()
>>> log = logging.getLogger("test_log")
>>> log.handlers = []
>>> log.addHandler(logging.NullHandler())

>>> print(root_log)
<RootLogger root (WARNING)>
>>> print(root_log.handlers)
[]

>>> import holoviews as hv
>>> hv.notebook_extension()

>>> print(root_log)
<RootLogger root (INFO)>
>>> print(root_log.handlers)
[<StreamHandler stderr (NOTSET)>]

>>> log.info("test")
INFO:test_log:test
```

**Comment by philippjfr** [comment]
This should be high-priority to fix. I'm assuming it's param doing this but in any case that should create a custom logger and not mess with the root logger.

**Comment by philippjfr** [comment]
Fixed in https://github.com/pyviz/param/pull/330
