### ISSUE TITLE
Missing FAQ entry

### ISSUE THREAD

**Issue by michaelaye** [pyviz/holoviews#3470]
On here: http://holoviews.org/FAQ.html
there is a Q and A that seem to miss the actual code to implement the suggestion?

>Q: Why don’t you let me pass matplotlib_option as a style through to matplotlib?

>A: We have selected a subset of default allowable style options that are most commonly useful in order to hide the more arcane matplotlib options. If you do need such an option to be passed to the plotting system, you are welcome to declare that this is allowed. For instance, say you may want the 'filternorm' option to be passed to matplotlib’s imshow command when displaying an Image element:

>Now you can freely use 'filternorm' in .options() and in the %opts line/cell magic, including tab-completion! 
```

**Comment by jbednar** [comment]
Thanks.  The code is in the .rst file but gets skipped due to bad syntax somewhere:
```
.. code:: python
  import holoviews as hv
  from holoviews import Store

  hv.extension('matplotlib')
  Store.add_style_opts(hv.Image, ['filternorm'], backend='matplotlib')
```

**Comment by jbednar** [comment]
I *think* it's a line missing after code::; I'll try that.

**Comment by jbednar** [comment]
There was another bit with the same issue; I pushed fixes for both to https://github.com/pyviz/holoviews/pull/3471 which should get merged sometime soon.
