### ISSUE TITLE
Install warning for pyviz/jupyterlab_pyviz: "Multiple versions of d3-array found"

### ISSUE THREAD

**Issue by CatChenal** [pyviz/holoviews#3493]
I have successfully installed holoviews with the configuration for Jupyter Lab as per [this official page](http://holoviews.org/user_guide/Installing_and_Configuring.html).

*This post is to inform you of an installer warning about a duplicate library.*

After I ran this command:
```> jupyter labextension install @pyviz/jupyterlab_pyviz```

The installation log ends with this information:
```
WARNING in d3-array
  Multiple versions of d3-array found:
    1.2.4 ./~/d3-scale/~/d3-array from ./~/d3-scale/~/d3-array\src\index.js
    2.0.3 ./~/d3-array from ./~/d3-array\src\index.js

Check how you can resolve duplicate packages:
https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle

Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [KTNU] ./node_modules/html-loader!./templates/partial.html 567 bytes {0} [built]
    [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
    [aS2v] ./node_modules/html-webpack-plugin/lib/loader.js!./templates/template.html 1.22 KiB {0} [built]
    [yLpj] (webpack)/buildin/global.js 489 bytes {0} [built]
        + 1 hidden module
Done in 35.56s.
```
The website referenced in the second paragraph suggests installing this package:
 `duplicate-package-checker-webpack-plugin`.
But that would be useful on YOUR side (before publishing the package), correct?
Thanks for clarifying.

___
My info:
```
python   : 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)]
jupyterlab: 0.34.3   [jupyter_nbextensions_configurator] enabled 0.4.0
holoviews: 1.11.2
param    : 1.8.2
bokeh    : 1.0.4
```

**Comment by philippjfr** [comment]
@CatChenal I don't think this has anything to do with the pyviz jupyterlab extension since we do not in any way depend on it. I suspect some other jupyterlab extensions must be conflicting in some way.
