### ISSUE TITLE
Custom Slider Starting Position for DynamicMaps

### ISSUE THREAD

**Issue by christopherbuhtz** [pyviz/holoviews#3497]
I am wondering if there is a way to set the initial position of slider values when showing a plot. Right now I am doing something like

``dmap = hv.DynamicMap(function, kdims=['x','y'])``

``plot = dmap.redim.values(x=np.arange(10,1000,5),``
``                                         y=np.arange(0,2,0.05)``

When showing the plot, all the sliders are intitialized with their lowest value on the left. Is there a way to set the first position to a specific value? I am asking because I want to start with a certain 'default' view of a plot which is not always with all sliders on the left but maybe in the center. Thanks!

**Comment by philippjfr** [comment]
Dimensions allow defining a default value:

```python
plot = dmap.redim.values(x=np.arange(10,1000,5), y=np.arange(0,2,0.05).redim.default(x=100, y=0.25)
```
