### ISSUE TITLE
Either misaligned overlay or linked brushing failure when datasource is shared but all axes are not

### ISSUE THREAD

**Issue by eburling** [pyviz/holoviews#3503]
I am overlaying a `Scatter` object onto a `BoxWhisker` object using `kdim='cyl'` and `vdim='mpg'` and coloring the scatter points and box using `dim('cyl').str()`. I would now like to add another `Scatter` object to the layout using the same datasource and color based on `cyl`, but use different variables for the _x_ and _y_ axes. 

The code below behaves as desired (linked brushing, different _x_ and _y_ axes between `Scatter` objects), with the noted exception that the second `Scatter` object is not colored by `cyl`.

```python
import holoviews as hv
from holoviews import dim,opts
from holoviews.plotting.links import DataLink

from bokeh.models import HoverTool
from bokeh.sampledata.autompg import autompg as df

hv.extension('bokeh')

df = df.sort_values(by=['cyl'])

tooltips = [
    ('cyl', '@cyl'),
    ('mpg', '@mpg'),
    ('accel', '@accel'),
    ('displ', '@displ')
]

hover = HoverTool(tooltips=tooltips)

boxwhisker = hv.BoxWhisker(df, 'cyl', 'mpg').opts(show_legend=False, 
                                                  box_fill_color=dim('cyl').str(),
                                                  cmap='Set2',
                                                  outlier_alpha=0.0,
                                                  box_fill_alpha=0.1)

scatter1 = hv.Scatter(df, 'cyl', ['mpg','displ','accel','origin'])
scatter2 = hv.Scatter(df, 'displ', ['accel'])

overlay = scatter1.opts(jitter=0.6) * boxwhisker

dlink = DataLink(overlay, scatter2)

((overlay + scatter2).opts(
    opts.Scatter(tools=['box_select', 'lasso_select','tap',hover],
                 color=dim('cyl').str(),
                 cmap='Set2',
                 alpha=0.5,
                 selection_fill_alpha=1.0,
                 nonselection_fill_alpha=0.1,
                 size=5,
                 line_color='k',
                 show_legend=False), 
    opts.Layout(shared_datasource=True)))
```

However, if I change `scatter2` to include `cyl` in its `vdims`, i.e. `scatter2 = hv.Scatter(df, 'displ', ['accel','cyl'])`, the colors match between `Scatter` objects, but the `scatter1` points become misaligned with the boxplots. If I try sorting the `Scatter` objects, e.g. `scatter1.sort(['cyl'])`, the colors and alignment are as desired, but linked brushing is then broken.

Thanks for your consideration and you contributions on this beautiful library.

**Comment by eburling** [comment]
Additionally, I notice that "live" brushing works for `Lasso Select` but not `Box Select`. Is there a setting or configuration that I'm missing?

**Comment by philippjfr** [comment]
This issue is the same as #3935, I realize this one came earlier but that one has a more precise title.

>Additionally, I notice that "live" brushing works for Lasso Select but not Box Select. Is there a setting or configuration that I'm missing?

That's odd, can't reproduce this.
