### ISSUE TITLE
Triangle markers (<, >, v, ^) all point upwards in bokeh legend

### ISSUE THREAD

**Issue by poplarShift** [pyviz/holoviews#3514]
In the bokeh backend, all of the four following triangles are printed in the legend as pointing upwards (it's fine in the figure itself). The mpl backend is fine.

```import holoviews as hv
hv.extension('bokeh')
hv.Dataset(([0, 1, 0, 0, 1], [0, 1, 2, 1, 0], ['foo', 'bar', 'baz', 'blah', 'meh']), ['x', 'y', 'z']
          ).to(hv.Points, ['x', 'y'], groupby='z').overlay(
).opts(hv.opts.Points(size=10, marker=hv.Cycle(['v', 's', '^', '<', '>']))
      ).redim.range(x=(-1, 3), y=(-.5, 2.5))
```

**Comment by philippjfr** [comment]
I suspect this may be an issue upstream in bokeh and may have to be filed there, but worth investigating first.

**Comment by poplarShift** [comment]
You were right, see #8891

**Comment by philippjfr** [comment]
Will close, can't do anything about this and there is an existing bokeh issue.
