### ISSUE TITLE
Trouble using BokehFigure.py to encapsulate a bokeh figure in holoviews

### ISSUE THREAD

**Issue by Jacob-Barhak** [pyviz/holoviews#3538]
When using [BokehFigure.py](https://gist.github.com/philippjfr/cfc310b54c639f1f5b7accf6e5d29c59]) to encapsulate a bokeh figure within holoviews there are several issues:

* A bokeh toolbar does not print well. to reproduce, try and print the following [poster](https://jacob-barhak.github.io/InteractivePoster_MSM_IMAG_2019.html)  using wither chrome or edge on a windows machine. The result replaces the bokeh toolbar with text. Here is a [link](https://msmmeeting.nibib.nih.gov/sites/default/files/MSM_IMAG_2019_Poster_ForPrint_2019_03_04.pdf) to a pdf that demonstrates this problem in the interactive plots.

* It is not possible to store the bokeh object encapsulated. The main issue is that pickle does not work on bokeh, and holoviews uses pickle to store objects. I also tried cloudpickle and dill without success. This means it is not possible to archive objects to be used in different programs. The ability to serialize objects is important so if Holoviews should have the capability to encapsulate bokeh objects, its important that serialization is allowed.  Specifically for the poster above, I was trying to create a poster in a single file yet since I could not pass the object to the poster creation program I ended up with links.

**Comment by philippjfr** [comment]
Thanks for filing this but neither issue is something we can do anything about at the HoloViews level, if you think these are important fixes that bokeh should be making please re-raise these as individual issues with reproducible examples on the bokeh issue tracker.

**Comment by Jacob-Barhak** [comment]
So @philippjfr  - Since BokehFigure.py is code that is not part of Bokeh, I am not sure if the cause of the problem is bokeh or BokehFigure.py . Bokeh folk might point me back here. Can you at least confirm that these are both Bokeh issues?

The first problem is easily reproducible by printing the poster created by [this code](https://github.com/Jacob-Barhak/Presentations)

The second one is a feature request to allow saving a bokeh model rather than a bokeh document. 

I certainly want to be able to print a document and to export figures using some sort of serialization. 

Your guidance will help here.
