### ISSUE TITLE
thick datashader lines

### ISSUE THREAD

**Issue by pjvalla** [pyviz/holoviews#3549]
Working with a large dataset and using holoviews with datashader.  

The code below is taking a holoviews curve and then datashading followed by dynamic spreading.

```
dynspread(datashade(real_curve, cmap='blue', normalization='linear', min_alpha=100), max_px=1)
```

It results in the plot below.  Is there a way to effectively control the line thickness.  I understand that after datashading it is effectively an image.  Just trying to make the plot a bit more pleasing to the eye.

![Selection_011](https://user-images.githubusercontent.com/10789547/54065957-c803dc80-41f5-11e9-89d3-56f9dfb626b6.png)

**Comment by jbednar** [comment]
In this particular case you might try reducing the maximum spreading, but in general we'd have to implement something like https://github.com/pyviz/datashader/issues/623 , which will be a good bit of work and is not currently funded or planned soon.

**Comment by pjvalla** [comment]
Thanks for the quick response.

**Comment by philippjfr** [comment]
Usage question and any improvement here wouldn't happen in HoloViews.
