### ISSUE TITLE
Rendering Holoviews + Bokeh objects in Bokeh server application

### ISSUE THREAD

**Issue by hickman-santini** [pyviz/holoviews#3552]
I posted a too-niche question on SO ([here](https://stackoverflow.com/questions/55079454/bokeh-server-app-needs-callback-to-alter-geoviews-element-in-holoviews-overlay)), then realized there is probably something fundamental missing from my understanding of rendering holoviews and bokeh objects together. I hope you'll forgive me if I'm breaking issue-raising etiquette by asking for help both on SO and here.

The only way I have been able to get both a bokeh `circle` plot and a holoviews container (`EsriImagery` map * geoviews `polygons` * text) to show up in the same application has been to render the former using `curdoc.add_root(layout(grid, data_table, dropdown))` (`grid` is a gridplot object, `data_table` a bokeh DataTable) and the latter with `doc = hv.renderer('bokeh').server_doc(plot)`. **Is this hair-brained? Is there an alternative?** It seems you can't put an hv `Overlay` object in with `curdoc.add_root()` because it only wants `LayoutDOM` objects?

I want for the two plots to share information, so to speak - e.g. lassoed points from the bokeh plot inform which polygons are displayed. I haven't been able to figure out how you're meant to bridge the divide between objects rendered in different ways - been trying `CSDView` and CustomJS callbacks without success.

Any guidance will be greatly appreciated. I'm using Bokeh 0.13.0, Python 3.6.7, Holoviews 1.10.7, and Geoviews 1.5.1.

**Comment by philippjfr** [comment]
Sorry for not replying earlier, I'll reply on StackOverflow since this is a usage question.

**Comment by hickman-santini** [comment]
Thanks @philippjfr look forward to hearing any advice you may have!

**Comment by hickman-santini** [comment]
@philippjfr just a ping - I could still use your advice if you have the time.

**Comment by philippjfr** [comment]
Sorry, was away at a conference last week. This is still on my stack of things to go over but sadly that has grown over the past week. My immediate advice would be to use either bokeh or holoviews and avoid mixing in most cases. It should be reasonable easy to replace your circle glyph using gv.Points and using a [Selection1D stream](http://holoviews.org/reference/streams/bokeh/Selection1D_points.html) to access the selection in Python to select your polygons.

**Comment by hickman-santini** [comment]
The end goal has changed a bit since my OP, but my road-block is still making holoviews and bokeh objects live together in peace. Right now I've got it so when you click on a row in the bokeh `DataTable`, a new plot (holoviews `Overlay` obj) is rendered with just that `Polygon`. Great! Except that the table is overlaid on the original plot. Can you suggest a hack to separate the table from the plot?

Below `plot` is a class `holoviews.core.overlay.Overlay` and `table` is class `bokeh.models.widgets.tables.DataTable`
```
doc = renderer.server_doc(plot)

items.children.extend([table])
```

Screenshot, maps not shown:
![image](https://user-images.githubusercontent.com/26146505/57461341-d3e73b80-7244-11e9-95da-96b8cdaec664.png)

FWIW, here's the callback I wrote to create a plot `subplot` of just one polygon. Shout out to [this SO answer](https://stackoverflow.com/questions/41746902/how-to-get-bokeh-datatable-cell-content-on-click/47886047#47886047) for getting me on the right path.

```
    def callback(attrname, old, new):
        selectionIndex=source.selected.indices[0]
        print("you have selected "+str(selectionIndex))
        print(dataset.loc[selectionIndex, 'geometry'])
        subplot = EsriImagery.opts(width=800, height=400) * gv.Polygons(dataset.loc[selectionIndex, 'geometry'], index=['time'], vdims=['time', 'dttime']).opts(style=dict(alpha=0.4,line_color='red')).redim.range(Longitude=(minlon, maxlon))
        doc = renderer.server_doc(subplot)

    source.selected.on_change('indices', callback)
```

**Comment by philippjfr** [comment]
@hickman-santini Which version of holoviews and bokeh are you using?

**Comment by hickman-santini** [comment]
Holoviews 1.11.3
Bokeh 1.0.2
Geoviews 1.6.3a I think (1.6.2.post8+g79a79fe), but 1.6.2 gave same result

**Comment by philippjfr** [comment]
The latest versions of HoloViews and Bokeh are 1.12.2 and 1.1.0 respectively.

**Comment by hickman-santini** [comment]
I'll be darned; that fixed it. I'm so sorry...I thought I had tried upgrading Bokeh and HoloViews and it required downgrading Geoviews, but that wasn't the case. This is great! Thank you @philippjfr !
