### ISSUE TITLE
Using .redim.defaults overrides other Dimension attributes

### ISSUE THREAD

**Issue by rsignell-usgs** [pyviz/holoviews#3561]
As [discussed on StackOverflow](https://stackoverflow.com/questions/55092912/specifying-the-default-value-in-widgets-generated-by-pyviz-hvplot), it would be nice to be able to specify the default values for widgets created automatically by `hvplot`. 

I've got a 4D dataset and `hvplot` is nicely generating widgets for the dimensions I've specified in the `groupby`:
```python
import xarray as xr

ds = xr.open_dataset('http://gamone.whoi.edu/thredds/dodsC/coawst_4/use/fmrc/coawst_4_use_best.ncd')

rho_vars = ['salt','temp']

from cartopy import crs as ccrs
import hvplot.xarray
import holoviews as hv
from geoviews import tile_sources as gvts
import panel as pn

var_select = pn.widgets.Select(name='Variables:', options=rho_vars, 
                               value='temp')

crs = ccrs.PlateCarree()

def plot(var=None):
    base_map = gvts.OSM
    var = var or var_select.value
    mesh = ds[var][-24:,:,:].hvplot.quadmesh(x='lon_rho', y='lat_rho', rasterize=True, title=var,
                                    width=600, height=400, crs=crs,
                                    groupby=list(ds[var].dims[:-2]), cmap='jet')
    overlay = (base_map * mesh.opts(alpha=0.7)).opts(active_tools=['wheel_zoom', 'pan'])
    widgets = {dim: pn.widgets.Select for dim in ds[var].dims[:-2]}
    return pn.holoviews.HoloViews(overlay, widgets=widgets).layout

def on_var_select(event):
    var = event.obj.value
    dashboard[-1] = plot(var=var)

var_select.param.watch(on_var_select, parameter_names=['value']);

dashboard = pn.Column(var_select, plot(var_select.value))
```
which produces:
![one](https://user-images.githubusercontent.com/1872600/54302289-fafff480-4596-11e9-9ad4-bd1f9a3fd4de.png)

However, while `hvplot` defaults to the *first* value of the `options` in the `OrderedDict`, I would like to default to the *last* value.

If I look at the dashboard elements:
```python
    print(dashboard)

    Column
        [0] Select(name='Variables:', options=OrderedDict([('salt', ...]), value='temp')
        [1] Row
            [0] HoloViews(DynamicMap, widgets={'time': <class 'panel.wid...})
            [1] Column
                [0] Select(name='Forecast time f..., options=OrderedDict([('2019-03-09 ...]), value=numpy.datetime64('2019-03-...)
                [1] Select(name='S-coordinate a..., options=OrderedDict([('-0.96875', ...]), value=-0.96875)
```
I see that I can specify the `Select` widget value *post facto* like:
```python
dashboard[1][1][1].value = next(reversed(dashboard[1][1][1].options.values())) 
```
and that indeed works:
![two](https://user-images.githubusercontent.com/1872600/54302450-40242680-4597-11e9-8eae-e2db19192df5.png)

I would like to make a stand alone dashboard, however, that defaults to a last value when the user selects a new variable.  With the current code, when a new variable is selected, the default value is unfortunately again set to the first value. 

Is there a way to embed my *post facto* code to select the last value into my plot function, or is there another better approach to accomplish this?

The full notebook is here: https://nbviewer.jupyter.org/gist/rsignell-usgs/edb9eb572058c4fdee6708359d24539d

**Comment by philippjfr** [comment]
Once #3580 is merged this will work:

```python
import xarray as xr
import hvplot.xarray
import panel as pn

ds = xr.tutorial.open_dataset('air_temperature').load()
var = 'air'
atemp = ds[var][:10,:,:]
mesh = atemp.hvplot(groupby='time')

mesh.redim.default(**{d: atemp[d].values.max() for d in ds[var].dims[:-2]})
```

**Comment by rsignell-usgs** [comment]
@philippjfr , the example above works, but I can't get my real example to work:
https://nbviewer.jupyter.org/gist/rsignell-usgs/bca07fbcee937cda0c62ac490e647461

I'm probably doing something simple wrong?   

You should be able to run that notebook without modification, as it loads data via OPeNDAP.   
I used [this environment](https://github.com/reproducible-notebooks/COAWST-ROMS_Dashboards/blob/master/environment.yml).

**Comment by rsignell-usgs** [comment]
@philippjfr seems like `value` is expecting a string only?

**Comment by rsignell-usgs** [comment]
Post anacondacon ping.  😊

**Comment by philippjfr** [comment]
Taking a look shortly.

**Comment by philippjfr** [comment]
>@philippjfr seems like value is expecting a string only?

Could you clarify which value you are referring to here? I just tried your notebook and am not quite clear which part isn't working. So far everything I've tried worked okay.

**Comment by philippjfr** [comment]
Also, separate quick tip, I'd separate the base map selection from the plot redraw since that can be done in a DynamicMap without a full rerender. For now I'd use something like this:

```python
base_map = hv.DynamicMap(lambda value: value(), streams=[hv.streams.Params(base_map_select, ['value'])])
```

but I'm going to make a PR to improve that spelling to at least allow:

```python
base_map = hv.DynamicMap(lambda value: value(), streams=[base_map_select.param.value])
```

**Comment by rsignell-usgs** [comment]
Indeed, @philippjfr , I rebuilt the environment and it seems to be working fine now!   Sorry for the distraction.  This is awesome!
