### ISSUE TITLE
dm.event() is broken

### ISSUE THREAD

**Issue by basnijholt** [pyviz/holoviews#3564]
Run in one cell
```python
def plot_generator():
    while True:
        yield hv.Curve(np.random.rand(10))

dm = hv.DynamicMap(plot_generator(),
                   streams=[hv.streams.Stream.define('Next')()])
dm
```

then `dm.event()` has no effect and nothing appears in the JS console.

For now calling `hv.streams.Stream.trigger(dm.streams)` works.

Related: https://github.com/python-adaptive/adaptive/issues/166

**Comment by philippjfr** [comment]
Note that I suspect this happens only when none of the streams define any actual parameters.

**Comment by douglasmacdonald** [comment]
https://github.com/pyviz/holoviews/blob/52548a6732881ed5c2cad1ad5b3ea2a163e092a3/holoviews/core/spaces.py#L1031

In the tutorial, http://holoviews.org/user_guide/Responding_to_Events.html, I could not get this to work for hv.__version__ '1.12.0'

```
for i in range(40):
    dmap.event()
```

However, the periodic example did work

`dmap.periodic(0.1, 1000, timeout=3)`

I had a snoop around the code and, when I tried the loop like this it worked

```
for i in range(40):
    #dmap.event
    hv.streams.Stream.trigger(dmap.streams) # I got this line from periodic call.
```
