### ISSUE TITLE
First event on Pipe not received by all subscribers

### ISSUE THREAD

**Issue by simonschellaert** [pyviz/holoviews#3579]
I've been using HoloViews for a few days now and recently stumbled upon a problem of which I'm not sure whether it is a bug or just a gap in my understanding, so any help would be very much appreciated.

Specifically, I'm posting data to a Pipe in the _SelectionGeometry_ callback of Bokeh. That Pipe is then used as a stream in a DynamicMap to display information based upon the selection. While this seems to work fine most of the time, the event doesn't seem to arrive at the DynamicMap the first time a selection is made (and the event is thus posted in the callback). I've also noticed that the DynamicMap sometimes got out of sync with the active selection but I'm not sure whether that issue is related or not.  The exact details of the scenario can be found below.

Thanks in advance for looking into this.

__Steps to reproduce__
1.  Run snippet as `python3 xyz.py`
2. Make a selection using the Bokeh lasso tool
3. Check lines printed in terminal

__Expected behavior__
The three lines below are printed. These lines indicate that the event was received in both the manual subscriber and in the dynamic map.
```
Push to pipe
Received new data in manual subscriber: data-82
Received new data in dynamic map: data-82
```

__Actual behavior__
Only the two lines below are printed. Notice how the output of the print statement in the function associated with the DynamicMap is missing. On subsequent selection, all three lines are printed as expected.
```
Push to pipe
Received new data in manual subscriber: data-82
```

__Code__
```
import holoviews as hv

from holoviews.streams import Pipe

from bokeh.events import SelectionGeometry
from bokeh.io import show
from bokeh.server.server import Server

import random

hv.extension('bokeh')
renderer = hv.renderer('bokeh').instance(mode='server')


def modify_doc(doc):
    # Create an empty list of points to be able to use the lasso tool
    points = hv.Points([]).opts(tools=['lasso_select'])

    # Create an empty pipe and add a subscriber that prints new data
    pipe = Pipe([])
    pipe.add_subscriber(lambda data: print('Received new data in manual subscriber:', data))

    # Add a dynamic map that makes use of the data produced by the pipe
    def render_selection(data):
        print('Received new data in dynamic map:', data)
        return points
    dmap = hv.DynamicMap(render_selection, streams=[pipe])

    def selection_event(event):
        if not event.final:
            return

        print('Push to pipe')
        pipe.send('data-' + str(random.randint(0, 100)))

    # Create HoloViews plot and attach the document
    hvplot = renderer.get_plot(dmap, doc)
    hvplot.state.on_event(SelectionGeometry, selection_event)
    doc.add_root(hvplot.state)

server = Server({'/': modify_doc}, num_procs=1)
server.start()
server.show('/')
server.run_until_shutdown()
```

__Additional details__
Tested on Bokeh 1.0.4 & HoloViews 1.11.3.

**Comment by philippjfr** [comment]
Definitely looks like a bug to me, the first DynamicMap event is getting swallowed somewhere.

**Comment by philippjfr** [comment]
Got a fix now.
