### ISSUE TITLE
Bokeh tools appear and then disappear when applying selection to datashade

### ISSUE THREAD

**Issue by Minyall** [pyviz/holoviews#3582]
I'm not entirely sure how to describe or demonstrate this issue. When I run...

```
from holoviews.operation.datashader import datashade, bundle_graph
bundled = bundle_graph(hvG).opts(opts.Nodes(color='celeb',cmap=colors, size=1),
                                 opts.Graph(width=800, height=800, tools=['tap','hover']))
```

I get the expected output and Bokeh tools

![Screenshot 2019-03-27 at 12 42 46](https://user-images.githubusercontent.com/14132122/55076876-67e2b680-508e-11e9-8b13-ce1a2016b181.png)

However when I then run 

```
(datashade(bundled,  width=400, height=400, normalization='log') * bundled.nodes).opts(
    opts.Nodes(size=1, color='celeb',width=800, cmap=colors, legend_position='right')) *\
bundled.select(screen_name='wrathofgnon').opts(opts.Graph(tools=['hover','zoom_in']),
                                               opts.Nodes(fill_color='white'))
```

The graph renders fine and the bokeh tools briefly appear in the top right, but then disappear.

![Screenshot 2019-03-27 at 12 53 17](https://user-images.githubusercontent.com/14132122/55077309-5221c100-508f-11e9-82f8-9cf29ba974e7.png)

Is this an issue with the code I've written, or perhaps how it is being rendered in Jupyter Notebooks?

**Comment by philippjfr** [comment]
This will be fixed in the next release by fixes that were made upstream in bokeh. Thanks for filing an issue though.

**Comment by Minyall** [comment]
Ok great, thanks for the very swift response!
