### ISSUE TITLE
User Guide: some pages are not correctly rendered

### ISSUE THREAD

**Issue by zertrin** [pyviz/holoviews#3589]
In the user guide the following sections have problems:

  - *Creating interactive network graphs*
  - *Working with large data using datashader*

On the built website, the pages are rendered with an error: 

- http://build.holoviews.org/user_guide/Network_Graphs.html
- http://build.holoviews.org/user_guide/Large_Data.html

**Comment by zertrin** [comment]
Ah for some reason after googling I found myself on the `build.holoviews.org` instead of `holoviews.org`, the pages are ok on `holoviews.org`.

**Comment by philippjfr** [comment]
Thanks for reporting this in any case. We need to ensure that google does not index build.holoviews.org and dev.holoviews.org and the fact that these aren't rendering is also worrying.

**Comment by zertrin** [comment]
Small precision, I said googling by habit, but I was actually duckduckgoing 😉 🦆  I suppose the usual `robots.txt` should be honoured by both anyway. holoviews.org has one, but build.holoview.org returns 404 on robots.txt.
