### ISSUE TITLE
Overlay violin doesn't cycle colors

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoviews#3592]
```
groups = [chr(65+g) for g in np.random.randint(0, 3, 200)]
vio_df = pd.DataFrame({'groups': groups,
                       'value': np.random.randn(200),
                       'category': np.random.randint(0, 3, 200)})
vio_df.hvplot.violin('value', by='groups', groupby='category').overlay('category')
```
![image](https://user-images.githubusercontent.com/15331990/55294317-8bbb3a80-53b5-11e9-9a8e-071a11292cc0.png)

**Comment by jbednar** [comment]
As written, this would go on https://github.com/pyviz/hvplot/ rather than this repo, as it's hvplot code, but maybe you know the same thing happens with regular HoloViews?

**Comment by ahuang11** [comment]
I assumed correctly :P 

I believe it has to do with `color` not existing for Violin type?
```
violin.opts(color='red')

ValueError: Unexpected option 'color' for Violin type across all extensions. Similar options for current extension ('bokeh') are: ['bgcolor', 'box_color', 'colorbar'].
```

```
hv.Violin(vio_df.loc[vio_df['category'] == 0], 'groups', 'value') * hv.Violin(vio_df.loc[vio_df['category'] == 1], 'groups', 'value')
```
![image](https://user-images.githubusercontent.com/15331990/55303204-b62ee700-53f9-11e9-912f-63bfa7ec5e01.png)

**Comment by philippjfr** [comment]
I think it's to do with the fact that you hardcoded the value as lightgray :smile:

**Comment by philippjfr** [comment]
Fixed in https://github.com/pyviz/holoviews/pull/3593
