### ISSUE TITLE
hv.operation.timeseries.rolling() fails on HoloMap if no window_type is specified

### ISSUE THREAD

**Issue by zertrin** [pyviz/holoviews#3597]
Trying to use `hv.operation.timeseries.rolling` on a HoloMap fails when no `window_type` is given with the following error.

```
TypeError: cannot handle this type -> object
```

See minimal working example here for full stacktrace: https://anaconda.org/zertrin/2019-04-03-holoview-reproduce-bug-timeseries_rolling_no_window_type/notebook?version=2019.04.03.1545

Notice that cell `In [6]:` fails, while adding the `window_type` in cell `In [7]:` works.

This might have to do with the fact that the rolling transformation is applied differently depending on whether `window_type is None` or not:

From https://github.com/pyviz/holoviews/blob/v1.11.3/holoviews/operation/timeseries.py#L54

```python
def _process_layer(self, element, key=None):
    xdim = element.kdims[0].name
    df = PandasInterface.as_dframe(element)
    df = df.set_index(xdim).rolling(win_type=self.p.window_type,
                                    **self._roll_kwargs())
    if self.p.window_type is None:
        kwargs = {'raw': True} if pandas_version >= '0.23.0' else {}
        rolled = df.apply(self.p.function, **kwargs)         # <---- error happens here
    else:
        if self.p.function is np.mean:
            rolled = df.mean()                        # <---- if we go here, no problem
        elif self.p.function is np.sum:
            rolled = df.sum()
        else:
            raise ValueError("Rolling window function only supports "
                             "mean and sum when custom window_type is supplied")
    return element.clone(rolled.reset_index())
```

**Comment by philippjfr** [comment]
Can't reproduce this error with more recent pandas.

**Comment by zertrin** [comment]
Indeed, 

When I opened the issue, my versions were:

```
Versions:
--------------------------------
python			3.6.7
numpy			1.16.2
pandas			0.24.2
matplotlib		3.0.3
holoviews		1.11.3
IPython			7.1.1
notebook		5.7.7
```

I just retested with:

```
Versions:
--------------------------------
python			3.7.3
numpy			1.17.1
pandas			0.24.2
matplotlib		3.0.3
holoviews		1.12.5
IPython			7.1.1
notebook		6.0.0
```

and it also didn't work, so I recreated a new fresh environment:

```
Versions:
--------------------------------
python			3.7.4
numpy			1.16.5
pandas			0.25.1
matplotlib		3.1.1
holoviews		1.12.3
IPython			7.8.0
notebook		6.0.1
```

and it worked.

It seems that it suddenly works with `pandas >= 0.25`, but not with `pandas <= 0.24`
