### ISSUE TITLE
Overlaying HoloMaps

### ISSUE THREAD

**Issue by lsdR94** [pyviz/holoviews#3605]
I've read the user guides but I haven't found any way to overlay multiple HoloMaps. I made two different functions hence HoloMaps to make two different lines that represent the axis of a Seismic Survey. What I have in mind, is to use this HoloMaps to explore the survey and to overlay them in the point of interest that's the interception of the lines mentioned above. Whatever I try, I still get this Exception: "One set of keys needs to be a strict subset of the other.". 

I have no experience programming in this environment so I appreciate any advice that helps me to get experience in this matter.

**Comment by jbednar** [comment]
HoloMaps should overlay just fine in normal cases.  Here the message indicates that your two holomaps have two different sets of key-dimension values, with neither one a subset of the other, so neither holomap's keys can be used as "the" set of keys for the overall holomap.  E.g. if one holomap has values for the keys 1, 5, and 9 and the other has values for 5, 7, and 11, the keys for the combined holomap would need to be 1, 5, 7, 9, 11, and it's not (currently) smart enough to figure that out.  Usually if this happens it's an error, in that you are overlaying two commensurate things, but it can happen when there is missing data, so it may be something that we could handle better if we saw a good motivating use case.  Meanwhile, you should be able to make one of the holomaps have values for all of the keys of the other.

**Comment by philippjfr** [comment]
>if one holomap has values for the keys 1, 5, and 9 and the other has values for 5, 7, and 11, the keys for the combined holomap would need to be 1, 5, 7, 9, 11, and HoloViews is not (currently) smart enough to figure that out.

I don't think that is the case, what you describe should work fine. What I think the error is indicating is that the key **dimensions** are not overlapping, i.e. that you have one HoloMap which varies by time and another that varies by some other dimension, e.g. let's say by country. It therefore cannot figure out how combine these two things into a single HoloMap.

**Comment by jbednar** [comment]
Ah, in that case the error message should be reworded to talk about key dimensions, and there's no limitation in HoloViews itself. Much better! :-)

**Comment by lsdR94** [comment]
> > if one holomap has values for the keys 1, 5, and 9 and the other has values for 5, 7, and 11, the keys for the combined holomap would need to be 1, 5, 7, 9, 11, and HoloViews is not (currently) smart enough to figure that out.
> 
> I don't think that is the case, what you describe should work fine. What I think the error is indicating is that the key **dimensions** are not overlapping, i.e. that you have one HoloMap which varies by time and another that varies by some other dimension, e.g. let's say by country. It therefore cannot figure out how combine these two things into a single HoloMap.

Yes, the two HoloMaps uses different key Dimensions. These are related to the axis of the seismic survey which not coincide with the XY axis of the plot. For you to imagine it, my key Dimensions are the height and width of a rectangle where each one of these were calculated using a function and a DataFrame of the seismic data.

**Comment by jbednar** [comment]
If that's the case, I'm not sure what you are trying to achieve with overlaying them.  If two holomaps A and B share a key dimension, e.g. time, then overlaying them will overlay the frames from A and B that have the same time value.   But if holomap A is indexed over time, and holomap B is indexed over height; overlaying them doesn't mean anything -- there is no value for A that could ever match one in B.  Sounds like they should just be next to each other, as a layout not an overlay, as these are two independent things.
