### ISSUE TITLE
Datashader alpha not in Holoviews

### ISSUE THREAD

**Issue by zertrin** [pyviz/holoviews#3611]
Similar to issue #2108, `min_alpha` is exposed, but not `alpha` for `datashade()`

    WARNING:root:datashade: 'alpha' will be ignored (not a Parameter).

**Comment by jbednar** [comment]
What were you hoping `alpha` would do, as an argument to `datashade()`?  Datashader already uses the alpha channel in its own computations, returning RGBA images.
