### ISSUE TITLE
Changes in plot size can cause range events to loop

### ISSUE THREAD

**Issue by philippjfr** [pyviz/holoviews#3614]
When using a dynamic downsampling or aggregation operation with both RangeXY and PlotSize streams such as the ``rasterize`` operation it is possible to get in a state where events end up bouncing back and forth. While there is logic to prevent this happening already it does not account for the fact that if ``framewise=True`` a change in the ``PlotSize`` can trigger a range event. If the plot size is changing because the tick labels are getting longer plot size and range events will continuously bounce back and forth.

**Comment by jbednar** [comment]
Yes, I have seen that, though I've never been able to capture it reproducibly.  Probably there's some case where tick labels get enormous that would make it reliable to reproduce.

**Comment by philippjfr** [comment]
@jsignell gave me such an example, which is how I was able to figure it out. Will try to think of a fix today.

**Comment by youngsaj** [comment]
This is highly likely the issue I'm seeing as well.  @philippjfr I sent you an email with details, and potentially another way to duplicate this.
