### ISSUE TITLE
IPKernelApp No such comm: hv-extension-comm / Datashader not displaying visual

### ISSUE THREAD

**Issue by Minyall** [pyviz/holoviews#3617]
I believe that since upgrading to 1.12.0 I'm now getting a warning thrown in the terminal running Jupyter notebook 

```[IPKernelApp] ERROR | No such comm target registered: hv-extension-comm```
```[IPKernelApp] WARNING | No such comm: hv-extension-comm```

I noticed this because I'm having another issue when I run the same code referenced in #3582.  Prior to 1.12.0 the Datashader portion of the code ran and displayed but the tools did not, something I believe fixed in this update. However now I've upgraded the code... 

`(datashade(bundled,  width=400, height=400, normalization='log') * bundled.nodes).opts(
    opts.Nodes(size=1, color='celeb',width=800, cmap=colors, legend_position='right')) *\
bundled.select(screen_name='REDACTED').opts(opts.Graph(tools=['hover','zoom_in']),
                                               opts.Nodes(fill_color='white'))`

....completes without error but does not display the visual. The prior code to display the bundled graph does display properly so it appears related specifically to the datashade function.

I wondered if these could be related and how I might resolve the missing comm.

Many thanks,

**Comment by philippjfr** [comment]
@Minyall Could you report whether you're using classic notebook or JupyterLab and what version of pyviz_comms you have? You should have pyviz_comms 0.7.2 and if you're using JupyterLab you should update to jupyterlab_pyviz 0.7.1.

The errors and warnings you are seeing are annoying but inconsequential.

**Comment by Minyall** [comment]
I'm using classic notebook in this case.

`conda list`
`> pyviz_comms               0.7.2                      py_0    pyviz`

I've just run the example Network_Graphs.ipynb from examples in the repo using the same env and that appears to all work fine so perhaps something in my notebook, though it worked before the update and I have mimicked the example notebook fairly closely.

Thanks for the quick response!

**Comment by philippjfr** [comment]
>I've just run the example Network_Graphs.ipynb from examples in the repo using the same env and that appears to all work fine so perhaps something in my notebook, though it worked before the update and I have mimicked the example notebook fairly closely.

I think this is our fault actually, the problem is that old JS state in the notebook may be sticking around, you could try clearing your notebook, reloading the page and trying again. I'll think about a fix for that as well because it makes for a rather painful transition.

**Comment by Minyall** [comment]
> you could try clearing your notebook, reloading the page and trying again

I've run Cell > All output > clear, saved the notebook and then refreshed the page and re-run but the issue persists. Is this what you meant by clearing the notebook?

Will browser have an impact? I'm using safari but can switch to Firefox/Chrome.

**Comment by philippjfr** [comment]
>I've run Cell > All output > clear, saved the notebook and then refreshed the page and re-run but the issue persists. Is this what you meant by clearing the notebook?

That's exactly what I meant. Is this notebook something you could share or does it have proprietary code/data? I'd love to get to the bottom of this before we release again later today.

**Comment by Minyall** [comment]
Yes, let me just clean the data out a little to anonymise.

**Comment by Minyall** [comment]
All set. Is there a way to share data privately?

**Comment by Minyall** [comment]
Ah, hang on. It now works.... it must have been something with my data. I'm not sure what, but it now works since cleaning out my nx.Graph of attributes.

**Comment by stonebig** [comment]
just hit by that in an exiting notebook, in notebook mode. the notebook clearing is really not enough.

**Comment by bascrezee** [comment]
I also ran into this error running a Jupyter notebook, from the start everything works fine. Suddenly this error pops up. Clearing all output does not help, even restarting my machine did not solve it. Starting a new notebook from a freshly created directory works fine for the moment. 

`conda list`

```
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
pyviz_comms               0.7.2                      py_0    conda-forge
```

**Comment by ray798** [comment]
I had the similar issue 'IPKernelApp No such comm'. In my case, when I downgraded matplotlib to 3.3.1 (instead of 3.3.2), it was solved.

Hope this is helpful!

**Comment by jlstevens** [comment]
@philippjfr An interaction between matplotlib minor versions and comms sounds worrying!

**Comment by philippjfr** [comment]
I don't think that's anything to do with HoloViews. Just that other
extensions can also raise the same comm error.
