### ISSUE TITLE
jupyterlab multiple notebook view doesn't display the plots in the second view

### ISSUE THREAD

**Issue by cocoaaa** [pyviz/holoviews#3623]
Hi, thank you for developing this amazing library.
I've started to explore pyviz recently using jupyterlab, and while going through the tutorials, I noticed the plots don't appear correctly when I have multiple views of the same notebook. Please see the screenshot below:
![image](https://user-images.githubusercontent.com/8037983/56085963-8ae8c680-5e01-11e9-8faf-175599602e12.png)

The left column is the first view and I created another view of this same notebook via "New Veiw for Notebook" in Jupyterlab.  When I "shift+enter" the cells such as 

![image](https://user-images.githubusercontent.com/8037983/56085976-b370c080-5e01-11e9-80b0-c8480b391976.png)

another plot is generated in the first view's cell, not on the second view's cell.

Is this an expected/intended behavior?  
If not, how should I resolve the issue to have another plot to appear on the second view?

Thanks!

**Comment by philippjfr** [comment]
Thanks for reporting this. Unfortunately this is not entirely surprising to me, bokeh does not allow rendering the same model twice on a page so I don't see any immediate workaround. This is the same issue as https://github.com/pyviz/pyviz_comms/issues/3, so I'll close.

**Comment by mtkilic** [comment]
> bokeh does not allow rendering the same model twice on a page
is there a way to disable('hide') cell output, but able to show plot only on "output view"? When you create "output view" most of the time you don't care about default cell output.
