### ISSUE TITLE
Cannot import name 'GridBox' from 'bokeh.models'

### ISSUE THREAD

**Issue by Gerenuk** [pyviz/holoviews#3626]
With Holoviews as installed from Anaconda (Holoviews 1.12.1, Bokeh 1.0.4) there is an error in the notebook

	hv.notebook_extension("bokeh")

	WARNING:root:notebook_extension: Holoviews bokeh extension could not be imported, it raised the following exception: ImportError('cannot import name 'GridBox' from 'bokeh.models' (~/Anaconda/lib/python3.7/site-packages/bokeh/models/__init__.py)')
	---------------------------------------------------------------------------
	ImportError                               Traceback (most recent call last)
	<ipython-input-2-8a9e76a8c3eb> in <module>
	----> 1 hv.notebook_extension("bokeh")

	~/Anaconda/lib/python3.7/site-packages/param/parameterized.py in __new__(class_, *args, **params)
	   2540         inst = class_.instance()
	   2541         inst.param._set_name(class_.__name__)
	-> 2542         return inst.__call__(*args,**params)
	   2543 
	   2544     def __call__(self,*args,**kw):

	~/Anaconda/lib/python3.7/site-packages/holoviews/ipython/__init__.py in __call__(self, *args, **params)
		113 
		114     def __call__(self, *args, **params):
	--> 115         super(notebook_extension, self).__call__(*args, **params)
		116         # Abort if IPython not found
		117         try:

	~/Anaconda/lib/python3.7/site-packages/holoviews/util/__init__.py in __call__(self, *args, **params)
		698 
		699         if selected_backend is None:
	--> 700             raise ImportError('None of the backends could be imported')
		701         Store.set_current_backend(selected_backend)
		702 

	ImportError: None of the backends could be imported

**Comment by philippjfr** [comment]
You will have to update bokeh to 1.1.0. I believe a broken version of HoloViews was uploaded to conda defaults which pins the wrong versions but this will hopefully be resolved very soon.
