### ISSUE TITLE
Request:Sankey plot node relabeling

### ISSUE THREAD

**Issue by geekonloose** [pyviz/holoviews#3630]
I am a newbie, who stumbled upon holoviews while browsing bokeh. 
I am using the Sankey plot to show chemical reaction products of different element mixtures. 
You might know, in chemistry,
Na + I --> NaI
one mole of sodium will react with iodine and produce one-mole only. However, holoviews automatically generates a summed labels and gives incorrect values (for the above example 'NaI-2'. )
Is there a way to relabel these values??
Please check image.
Below is my test code
```
import holoviews as hv
from holoviews import opts, renderer, render
from holoviews import dim
import pandas as pd
hv.extension('bokeh')

df = pd.DataFrame(data={'elements':['Na', 'Na', 'Cs', 'Cs', 'I', 'I'], 'species':['NaI', 'NaCs', 'CsI', 'NaCs', 'CsI', 'NaI'], 'values':[10, 20, 30, 20, 30, 10]})

sankey = hv.Sankey(df)

sankey.opts(label_position='right', edge_color='species', node_color='elements', cmap='flag')
hv.save(sankey, 'curve.html', backend='bokeh')

```
![Inkedbokeh_plot(2)_LI](https://user-images.githubusercontent.com/30520900/56195503-badad880-6052-11e9-8954-4b5a8d3b5282.jpg)

**Comment by poplarShift** [comment]
There's nothing wrong with the Sankey plot (it conserves the height of each chord from left to right, so to say), it's just not the right visualization type for your problem. I don't know whether what you're after has a specific name, Google hasn't turned up much for me.

**Comment by geekonloose** [comment]
Yes I know nothing wrong with Sankey plot. But user should have flexibility for modify the lables.

**Comment by poplarShift** [comment]
Is this what you're looking for?

Try toying around with `show_values` and `labels` until you're satisfied.

(`hv.help(hv.Sankey)` shows all available options.)

```
 import holoviews as hv
from holoviews import opts, renderer, render
from holoviews import dim
import pandas as pd
hv.extension('bokeh')

df = pd.DataFrame(data={'elements':['Na', 'Na', 'Cs', 'Cs', 'I', 'I'], 'species':['NaI', 'NaCs', 'CsI', 'NaCs', 'CsI', 'NaI'], 'values':[10, 20, 30, 20, 30, 10]})

sankey = hv.Sankey(df)

sankey.opts(label_position='right', edge_color='species', node_color='elements', cmap='flag', show_values=False, labels=dim('elements')+' foo bar baz '+dim('species'))
sankey
```

**Comment by geekonloose** [comment]
Thank you @poplarShift , It was super helpful. I just turned off value labels. This was the final outcome. 
![bokeh_plot(3)](https://user-images.githubusercontent.com/30520900/56261220-ce8c4a80-60f7-11e9-8bc5-4589f00683c5.png)
