### ISSUE TITLE
Add plotly server 

### ISSUE THREAD

**Issue by GdMacmillan** [pyviz/holoviews#3633]
I am done building and testing a plot and I encountered a problem trying to serve it outside the context of a Jupyter notebook. See the screenshot I posted here:

[https://imgur.com/a/x6DLIRB](https://imgur.com/a/x6DLIRB)

I couldn't find any documentation on this so i figured i would try to see if I could get it started as an issue. 

The library i used to generate the plot is holoviews with the plotly extension. I am working with plotly because of it's 3D paths and scatter capabilities. I'm using it as a 3D model basically.

**Comment by jbednar** [comment]
I can't spot the problem, but you might have more luck with [Panel](http://panel.pyviz.org), which is set up to serve lots of different types of plots already.

**Comment by philippjfr** [comment]
Yes, the suggested workflow for this is definitely using Panel. I believe this might be sufficient for your usecase:

```python
...
import panel as pn
pn.panel(plot_obj).show()
```

but you can also look at the [panel deployment documentation](http://panel.pyviz.org/user_guide/Deploy_and_Export.html) if you need other functionality.
