### ISSUE TITLE
Pending document writes error on bokeh server

### ISSUE THREAD

**Issue by rtmatx** [pyviz/holoviews#3641]
Hi,

I created a dashboard with panel. The dashboard uses datashader to plot big data. I used panel's `show` method to host it on a port and shared the port with others. 

What I noticed is if someone reloads the address or sometimes make any changes, I get these errors. The dashboard still works but with out any zooming capability of datashader/holoviews/bokeh. Is there any way to mitigate while plotting the tag or some things to avoid while creating dashboard with the datashader plots

`holoviews.core.options.AbbreviatedException: RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes`

**Comment by philippjfr** [comment]
Corresponding PR has been merged, we'll cut a release asap.
