### ISSUE TITLE
Support plotly >=3.8.0

### ISSUE THREAD

**Issue by jonmmease** [pyviz/holoviews#3643]
According to https://github.com/plotly/plotly.py/pull/1476#issuecomment-485344080, plotly.py 3.8.0 broke the HoloViews backend.

> FYI I believe this refactor broke holoviews integration (It imports plotly.offline.offline.utils, which has moved to _plotly_utils.utils).

It should just be a matter of changing `plotly.offline.offline.utils` to `plotly.offline.utils`.  These double nested packages  (`offline.offline`) were an implementation detail that changed in the version 3.8 refactor.

I'll take a look soon...

**Comment by philippjfr** [comment]
Thanks, let's try to get this into a 1.12.2 release later this week?

**Comment by jonmmease** [comment]
Yeah, sounds good.
