### ISSUE TITLE
hv.Dataset can't handle xarray MultiIndex

### ISSUE THREAD

**Issue by arabidopsis** [pyviz/holoviews#3645]
First: awesome stuff guys. Really love this!

Problem:
2D data from xarray works.. fantastic!
```
import xarray as xr
import numpy as np
import holoviews as hv
hv.extension('bokeh')

data = np.random.randn(4, 300)
# 300 samples from 4 experiments a b c d
da = xr.DataArray(
    data,
    name='value',
    dims=['exp', 'sample'],
    coords=dict(
        exp=['a', 'b', 'c', 'd'], sample=list(range(300))))

ds= hv.Dataset(da)
ds.to(hv.Curve, kdims='sample', vdims='value').overlay()

```
Now with 3 replicates with 100 samples for each experiment `a b c d.`
i.e. 3d data.
We use `xarray.stack` to combine replicates and rsamples -> 2d data. But now holoviews fails
with `ValueError: dimensions () must have the same length as the number of data dimensions, ndim=1`
```
data2 = np.random.randn(3,100, 4)
da2 = xr.DataArray(
    data2,
    name='value',
    dims=['replicate', 'rsample', 'exp'],
    coords=dict(replicate=[0,1,2],
        exp=['a', 'b', 'c', 'd'], rsample=list(range(100))))

# combine replicate and rsample -> back to (exp, sample) 2d data
da2 = da2.stack(sample=('replicate', 'rsample'))
ds2= hv.Dataset(da2)
ds2.to(hv.Curve, kdims='sample', vdims='value').overlay()
```
Fix problem by replacing MultiIndex on 'sample'
Nice plot again!

```
da2['sample'] = list(range(len(da2.sample)))
ds2= hv.Dataset(da2)
ds2.to(hv.Curve, kdims='sample', vdims='value').overlay()
```
`hv.__version__, xr.__version__, np.__version__ == ('1.12.1', '0.12.1', '1.15.4')`

**Comment by philippjfr** [comment]
It would definitely be nice to support multi-indexes, our support for them is lacking both in the pandas and xarray interfaces.

**Comment by arabidopsis** [comment]
This looks like a problem in xarray not on holoviews... you can't call max on a stacked dimension.
Given the example above
`da2.sample.max()` throws the exception (which is what holoviews is trying to do....)

**Comment by arabidopsis** [comment]
I've created an issue (https://github.com/pydata/xarray/issues/2923) with xarray
