### ISSUE TITLE
using a stream as a kdim fails in certain -- simple -- configurations of DynamicMap

### ISSUE THREAD

**Issue by arabidopsis** [pyviz/holoviews#3649]
A seemingly innocuous change in DynamicMap layout produces an Exception.

I was trying to get Holoviews to update the title based on a streams current value...
It works if you don't return a Layout object. Otherwise I get `Exception: DynamicMaps in unbounded mode must be displayed alongside a HoloMap to define the sampling`.

Here's a simple example: `(hv.__version__, np.__version__, bokeh.__version__) == ('1.12.1', '1.15.4', '1.1.0')`

```
import holoviews as hv
import numpy as np
from holoviews.streams import Stream
import bokeh
hv.extension('bokeh')

aname = Stream.define('aname', aname='a')()


def cb(aname, with_histogram):
    x = np.linspace(0, 1, 100)
    y = np.random.randn(100)
    curve = hv.Curve((x, y))
    hist = hv.Histogram(y)
    return (curve + hist).opts(shared_axes=False) if with_histogram else curve


def cb1(aname):
    return cb(aname, with_histogram=False)


def cb2(aname):
    return cb(aname, with_histogram=True)


m = hv.DynamicMap(cb1, kdims=[], streams=[aname])  # ok but no title
m = hv.DynamicMap(cb1, kdims=['aname'], streams=[aname])  # ok now with title
m = hv.DynamicMap(cb2, kdims=[], streams=[aname])  # ok but no title
# Exception: DynamicMaps in unbounded mode must be displayed alongside a HoloMap to define the sampling
m = hv.DynamicMap(cb2, kdims=['aname'], streams=[aname])
m
```

**Comment by philippjfr** [comment]
While it is possible it is generally not recommended to return a Layout from a DynamicMap, returning a changing numbers of items in a layout is absolutely not supported however. If you need dynamic layouts I'd recommend using [panel](http://panel.pyviz.org/) with holoviews.
