### ISSUE TITLE
overlapping stream and key dimensions breaks DynamicMap

### ISSUE THREAD

**Issue by arabidopsis** [pyviz/holoviews#3651]
My issue #3649 was -- I think -- closed a little too prematurely :)

I think there still is a problem with overlapping stream and key dimensions.

Here's the lissajous example adapted from the documentation http://holoviews.org/user_guide/Responding_to_Events.html

```
import numpy as np
import holoviews as hv
from holoviews.streams import Stream, param

time = Stream.define('Time', time=-3.0)()
lin = np.linspace(-np.pi,np.pi,300)

def lissajous(t, a=3, b=5, delta=np.pi/2.):
    return (np.sin(a * t + delta), np.sin(b * t))

def lissajous_crosshair(time):
    (x,y) = lissajous(time)
    return hv.VLine(x) * hv.HLine(y)

crosshair = hv.DynamicMap(lissajous_crosshair, kdims='time',streams=[time])

path = hv.Path(lissajous(lin))
```
So far so good but `path + crosshair` works while `path * crosshair` doesn't. (error: `DynamicMap cannot be displayed without explicit indexing as 'time' dimension(s) are unbounded. 
Set dimensions bounds with the DynamicMap redim.range or redim.values methods.`)

This *only* happens when you have, as the documentation says,  'dimensioned streams'. i.e.
with `kdim='time'` *and* `streams=[time]`. The error seems to indicate that it hasn't
found that the stream is handling the kdims='time' dimension.

I don't think the composability of a DymamicMap should depend on whether you
have a dimensioned stream or not... no?

The documentation doesn't have any caveats about this (and actually works for the example following).

**Comment by philippjfr** [comment]
Appears to have been fixed.
