### ISSUE TITLE
No (safe) render could be found for output

### ISSUE THREAD

**Issue by dclong** [pyviz/holoviews#3655]
When I close (without closing the Python 3 kernel) a JupyterLab notebook and reopen it, the HoloViews plots do not show up and the following error message is displayed.

No (safe) renderer could be found for output. It has the following MIME types: application/javascript, application/vnd.holoviews_load.v0+json

**Comment by philippjfr** [comment]
This is not something we have control over, you need to trust the notebook via the Jupyter menu.

**Comment by dclong** [comment]
@philippjfr It doesn't help to trust the notebook. The same issue still happens after trusting the notebook.

**Comment by philippjfr** [comment]
That sounds like a Jupyter bug then, definitely not something holoviews has control over.

**Comment by dclong** [comment]
@philippjfr Thank you! I've open an issue in the JupyterLab repository. 

https://github.com/jupyterlab/jupyterlab/issues/6251

**Comment by dclong** [comment]
@philippjfr 
vidartf says that there might be a pyviz issue of re-establishment of connectivity in the issue https://github.com/jupyterlab/jupyterlab/issues/6251. Would you help clarify there?
