### ISSUE TITLE
Figures appear on top of notebook in chrome

### ISSUE THREAD

**Issue by cocoaaa** [pyviz/holoviews#3657]
Hi,
When I open a notebook that contains holoview objects,
the figures appear strangely on Chrome:

<img src="https://user-images.githubusercontent.com/8037983/56829805-94b6f480-6819-11e9-8b90-7ae8910b98ba.png" height=500 />

If I scroll down, the figures stay on top of the page:
![image](https://media.giphy.com/media/Rlq5pDo2Kq1REme5dp/giphy.gif)

Please note that it's only the figures generated while I followed the holoview's guide document that are appearing like this. Other objects in the notebook that I created with my own dataset are not appearing like so.  These figures float around even after I close the notebook and kill the corresponding kernel. It's only after I refresh the browser, they go away.  
Please also note that the bokeh toolbar is somehow appearing inside Jupyterlab's toolbar line on the top (right below the Chrome's search window). I think this may be related to the problem. 

Here are the package versions I'm using:
![image](https://user-images.githubusercontent.com/8037983/56830823-4eaf6000-681c-11e9-8c1b-7ab90147806e.png)

Could you help me remove these figures? Any idea what is causing them to appear like this?

**Comment by jbednar** [comment]
I'm not a JupyterLab user, but I believe those are caused by not installing the JupyterLab extension as described at http://holoviews.org.

**Comment by poplarShift** [comment]
I've also had these issues a few times and it was always due to a missing/incomplete setup of the jlab extension.

**Comment by philippjfr** [comment]
Quite surprised by this, I thought it was no longer possible for this to happen with latest holoviews/pyviz_comms.

**Comment by philippjfr** [comment]
Did you load a notebook that had not been cleared after updating holoviews maybe? I've confirmed that latest holoviews does not have this problem.

**Comment by cocoaaa** [comment]
@philippjfr: I was using the master version of jupyterlab (1.0). Do you think that may have been the cause? I installed a clean environment, and now the problem disappeared. Thanks!
