### ISSUE TITLE
`responsive=True` and `plot={...}` work separately, but fail together

### ISSUE THREAD

**Issue by lsorber** [pyviz/holoviews#3660]
With Holoviews 1.12.1, the following minimal example shows that if you combine `responsive=True` with `plot={...}` the plot fails with a `ValueError`. Using just one of these two options does not raise an error.

```python
import numpy as np
import holoviews as hv

hv.extension('bokeh')

hv.Scatter((np.random.randn(10), np.random.randn(10))).opts(
    responsive=True,
    plot={'legend_position': 'top_left'}  # Comment this line and no error is raised.
)
# ValueError: Unexpected option 'plot' for Scatter type across all extensions. No similar options found.
```

**Comment by philippjfr** [comment]
You are mixing two different syntaxes for specifying options. Supplying ``plot`` or ``style`` is deprecated at this point you should simply define them in a flat spec:

``.opts(legend_position='top_left', responsive=True)``

**Comment by lsorber** [comment]
Thanks for the quick response!

May I suggest to return a more helpful error message that explains that `plot` and `style` are deprecated?
