### ISSUE TITLE
Alpha blending for mulidimensional images

### ISSUE THREAD

**Issue by pollackscience** [pyviz/holoviews#3669]
I have a bunch of 3D and 4D medical image data that I would like to overlay on top of one another, and adjust both the slice of the image I'm looking at and the relative transparency of the overlaid image.  However, when I try to vary the alpha parameter, I get the following error:
```
No plotting class for HoloMap found
:DynamicMap   [alpha]
   :HoloMap   [z]
      :Overlay
         .Image.I  :Image   [y,x]   (img1)
         .Image.II :Image   [y,x]   (img2)
```

Here's a minimal example where I can reproduce this issue:

```
img1 = hv.Dataset(
    xr.DataArray(np.random.uniform(0, 100, size=(100,100,10)),
                 coords={'z': range(10), 'y': range(100), 'x': range(100)},
                 dims=('x', 'y', 'z'), name='img1'))
img2 = hv.Dataset(
    xr.DataArray(np.random.uniform(0, 100, size=(100,100,10)),
                 coords={'z': range(10), 'y': range(100), 'x': range(100)},
                 dims=('x', 'y', 'z'), name='img2'))
```

Overlaying two images with a static alpha value (works fine):
```
img1.to(hv.Image, groupby=['z'], dynamic=False).opts(width=500, height=500) *\
img2.to(hv.Image, groupby=['z'], dynamic=False).opts(cmap='blues', alpha=0.5)
```
![image](https://user-images.githubusercontent.com/5065341/56906584-87477780-6a70-11e9-81a1-03cd034dd1f5.png)

Trying to alpha-blend those images (does not work):
```
def alpha_blend(alpha):
    return (
        img1.to(hv.Image, groupby=['z'], dynamic=False).opts(width=500, height=500) *\
        img2.to(hv.Image, groupby=['z'], dynamic=False).opts(cmap='blues', alpha=alpha)
    )

hv.DynamicMap(alpha_blend, kdims=['alpha']).redim.range(alpha=(0.0, 1.0))

No plotting class for HoloMap found
:DynamicMap   [alpha]
   :HoloMap   [z]
      :Overlay
         .Image.I  :Image   [y,x]   (img1)
         .Image.II :Image   [y,x]   (img2)
```

Not sure if I'm just specifying wrong or if this operation is not currently possible.  Any suggestions are greatly appreciated!

**Comment by philippjfr** [comment]
The problem here is that you are returning a HoloMap from a DynamicMap which is not supported. It would be nice if it was easier to chain a DynamicMap and add some key dimensions easily. For now you'd have to do something like this:

```python
dmap1 = img1.to(hv.Image, groupby=['z'], dynamic=True).opts(width=500, height=500)
dmap2 = img2.to(hv.Image, groupby=['z'], dynamic=True).opts(cmap='blues')

def apply_alpha(z, alpha):
    return dmap2[z].opts(alpha=alpha)

dmap1 * dmap2.clone(callback=apply_alpha, kdims=dmap2.kdims+[hv.Dimension('alpha', default=0.5, range=(0., 1))])
```

Alternatively you could also make use of [panel](http://panel.pyviz.org/) to add a widget explicitly:

```python
dmap1 = img1.to(hv.Image, groupby=['z']).opts(width=500, height=500)
dmap2 = img2.to(hv.Image, groupby=['z']).opts(cmap='blues')

import panel as pn
slider = pn.widgets.FloatSlider(start=0, end=1, value=0.5)

pn.Column(slider, dmap1 * dmap2.apply.opts(alpha=slider.param.value))
```

**Comment by pollackscience** [comment]
Thanks! I figured the procedure was possible, I was just screwing up the implementation.  The whole pyviz ecosystem has been excellent for interactive visualizations.
