### ISSUE TITLE
Linking plot axis across multiple plots

### ISSUE THREAD

**Issue by papahabla** [pyviz/holoviews#3678]
I am trying to create an audio time signal plot combined with a time-frequency spectrogram that are linked in time x-axis, but not in the y-axis. This is so that when zooming in on one of the plots, the same range of time is displayed in the other plot. I have searched through the examples, and all examples seem to be linked in both x, and y axis. In my example below, the two plots worked correctly when shown separately, but when combined, the y-axis range for the time signal plot is forced to follow the spectrogram. 

I think this is an important feature that should be possible, and documented and/or have a clean example for reference.

**My example notebook code:**
```python
import numpy as np
import holoviews as hv
from scipy.fftpack import fft
from holoviews import opts, Curve, Image

hv.extension('bokeh')
plot_width = 900
plot_height = plot_width // 2
opts.defaults(
    opts.Curve(
        height=plot_height,
        width=plot_width,
        line_width=1.0,
        line_alpha=.5,
        show_grid=True,
    ),
    opts.Image(
        height=plot_height,
        width=plot_width,
    ),
)
```
**Time signal generation and plot:**
```python
FS = 48000
T = 2
N = int(FS * T)
FZ = 5000  # Hz
t = np.linspace(0, T, N)
x = np.sin(2*np.pi*FZ*np.linspace(0,N-1,N) / FS) * .5
x += np.random.rand(N) * .5 
x_plt = Curve((t, x)).opts(title='Time Signal')
x_plt
```
![bokeh_plot](https://user-images.githubusercontent.com/10580407/56981239-36e51e00-6b33-11e9-96ba-fba5023c06e9.png)

**Spectrogram plot:**
```python
FFT_LEN = 1024
K = int(FFT_LEN // 2 + 1)
FFT_SHIFT = 512
FFT_WIN = np.hanning(FFT_LEN)
M = N // FFT_SHIFT - 1
X = np.zeros((M, K))
for m in range(M):
    x_idx = m * FFT_SHIFT
    xx = x[x_idx:x_idx+FFT_LEN] * FFT_WIN
    X[m, :] = np.log10(np.abs(fft(xx)[:K])+1e-21)
X_plt = Image(np.flipud(X.T), bounds=(0, 0, T, FS/2.)).opts(title='Spectrogram')
X_plt
```
![bokeh_plot (1)](https://user-images.githubusercontent.com/10580407/56981476-d1ddf800-6b33-11e9-81b0-2946c7f208f5.png)

**Combining time and spectrogram plots:**
`(x_plt + X_plt).cols(1)`
![bokeh_plot (2)](https://user-images.githubusercontent.com/10580407/56981559-03ef5a00-6b34-11e9-8b52-4caad4a8aa4a.png)
![bokeh_plot (3)](https://user-images.githubusercontent.com/10580407/56981587-110c4900-6b34-11e9-8c22-3435db620121.png)

**Comment by jbednar** [comment]
By default, HoloViews assumes that multiple plots with the same dimensions should be scaled together and linked to more easily show the relationship between the data in each one. But it won't do that if the dimensions are different, and here the problem is that you haven't told HoloViews that the dimensions are different.  Just label each dimension properly (not just x and y, but "time", "frequency", amplitude", etc., and then it should behave the way you expect:

```
x_plt = Curve((t, x),"time","amplitude").opts(title='Time Signal')
...
X_plt = Image(np.flipud(X.T),['time','frequency'], bounds=(0, 0, T, FS/2.)).opts(title='Spectrogram')
...

 I think there are already examples like that, but please open a PR clarifying this issue in the docs if you can see a good place for it!
