### ISSUE TITLE
Stream.trigger does not handle unhashable types

### ISSUE THREAD

**Issue by philippjfr** [pyviz/holoviews#3681]
In https://github.com/pyviz/holoviews/pull/3648 the Stream.trigger method was changed to try to deduplicate clashes by the value. This approach does not work for unhashable types like dictionaries which are quite common. The change should be reverted or the value comparison should be done by identity. I'm not actually convinced the change was necessary now as I believe taking the set of streams as I suggested in the PR should be sufficient to address the issue that originally led to the PR.

**Comment by jlstevens** [comment]
Ok. I am happy to revert that commit and I think I did test it with just the use of `set` and that was sufficient as you say...

**Comment by philippjfr** [comment]
Fixed in #3684
