### ISSUE TITLE
Broken "Getting Started" link on homepage

### ISSUE THREAD

**Issue by dolorsitatem** [pyviz/holoviews#3682]
The "Getting Started" link on the homepage is broken.  

![image](https://user-images.githubusercontent.com/31748559/57081383-9291e180-6cc2-11e9-98df-43dcc903e486.png)

It directs to 

```
http://holoviews.org/getting_started/index  
```

when it should be

```
http://holoviews.org/getting_started/index.html
```

**Comment by philippjfr** [comment]
Fixed in 040b7cac7d99c68b95cf71c18b8f8baf0bf24014
