### ISSUE TITLE
DataLink fails if NaN present

### ISSUE THREAD

**Issue by poplarShift** [pyviz/holoviews#3690]
When there is a NaN present in the column shared by the two objects passed to DataLink, it fails, claiming `ValueError: DataLink can only be applied if overlapping dimension values are equal`

```
import holoviews as hv
import numpy as np
hv.extension('bokeh')
from holoviews.plotting.links import DataLink

x = np.random.rand(100,3)

# no problem:
x[0,1] = np.nan

# makes it fail:
# x[0,0] = np.nan

df = pd.DataFrame(x, columns=['x', 'y', 'z'])

a = hv.Scatter(df, 'x', 'z')
b = hv.Scatter(df, 'x', 'y')
DataLink(a,b)
l=a+b
l
```

**Comment by philippjfr** [comment]
Thanks, should be an easy fix, the array comparison simply needs to use equal_nan=True.
