### ISSUE TITLE
streams.py still has several instances of .params()

### ISSUE THREAD

**Issue by sdc50** [pyviz/holoviews#3702]
The `holoviews.streams` module still has several usages of .params(), the old-style API of param, which causes warnings when using holoviews (see https://github.com/pyviz/panel/issues/420).

**Comment by jbednar** [comment]
@jlstevens, I thought you had eliminated all those?  Sounds like it's time to do a deeper search.

**Comment by philippjfr** [comment]
Don't think @jlstevens was involved in any of these updates. Would be happy to have help on that front of course.
