### ISSUE TITLE
heatmap plot empty

### ISSUE THREAD

**Issue by fedario** [pyviz/holoviews#3703]
When I try to plot a simple heatmap ([inspired by this](http://holoviews.org/reference/elements/bokeh/HeatMap.html#bokeh-gallery-heatmap)) like the following I get an empty heatmap.

```Python
import holoviews as hv
hv.extension('bokeh')

data = [(chr(65+i), chr(97+j),  i*j) for i in range(5) for j in range(5) if i!=j]
hv.HeatMap(data).sort()
```

This issue also seems to affect the example in the documentation. In the [reference gallery overview](http://holoviews.org/reference/index.html) the heatmap image is empty like the one in my example above.

#### Bonus weirdness
When I download the notebook from [the example](http://holoviews.org/reference/elements/bokeh/HeatMap.html#bokeh-gallery-heatmap) I get this error:

```
File Load Error for HeatMap.ipynb
NetworkError when attempting to fetch resource.
```
I can't even delete the file from within jupyter-lab. I never had this issue with any other file before.

#### pyviz package versions
```
colorcet                  2.0.1                      py_0    pyviz
datashader                0.7.0                      py_0    pyviz
holoviews                 1.12.2                     py_0    pyviz
hvplot                    0.4.0                      py_0    pyviz
panel                     0.5.1                      py_0    pyviz
param                     1.9.0                      py_0    pyviz
pyct                      0.4.6                      py_0    pyviz
pyct-core                 0.4.6                      py_0    pyviz
pyviz_comms               0.7.2                      py_0    pyviz
```

**Comment by philippjfr** [comment]
Seems to be an issue with the size of the plot, which appears to be responsive by default for some reason and then collapses to zero height.
