### ISSUE TITLE
hv.Cycle does not cycle through markers for bokeh backend

### ISSUE THREAD

**Issue by poplarShift** [pyviz/holoviews#3706]
In the bokeh backend, only the first marker of the list seems to be used:
```
import holoviews as hv
import numpy as np
hv.extension('bokeh')
s1 = hv.Dataset(np.random.rand(100,3), ['x', 'y'], 'z'
          ).to(hv.Scatter).overlay().opts(hv.opts.Scatter(size=hv.Cycle([8,15,30]), marker='<'))
s2 = hv.Dataset(np.random.rand(100,3), ['x', 'y'], 'z'
          ).to(hv.Scatter).overlay().opts(hv.opts.Scatter(size=10, marker=hv.Cycle(['cross', 'square', '<'])))

s1+s2
```
![Screen Shot 2019-05-13 at 11 26 05 AM](https://user-images.githubusercontent.com/38992106/57633746-fa251800-7571-11e9-9b16-2dc705bd5199.png)

Compare to mpl where everything seems ok:
```
import holoviews as hv
import numpy as np
hv.extension('bokeh')
s1 = hv.Dataset(np.random.rand(100,3), ['x', 'y'], 'z'
          ).to(hv.Scatter).overlay().opts(hv.opts.Scatter(size=hv.Cycle([8,15,30]), marker='<'))
s2 = hv.Dataset(np.random.rand(100,3), ['x', 'y'], 'z'
          ).to(hv.Scatter).overlay().opts(hv.opts.Scatter(size=10, marker=hv.Cycle(['cross', 'square', '<'])))

s1+s2
```
![Screen Shot 2019-05-13 at 11 26 16 AM](https://user-images.githubusercontent.com/38992106/57633806-1d4fc780-7572-11e9-91cb-8ef9272b985b.png)

**Comment by philippjfr** [comment]
This is related to the batching optimization in the bokeh backend which merges multiple overlays into a single glyph because it is very inefficient to draw a lot of individual glyphs. When this optimization was first introduced it was not possible to cycle markers but since then this has become possible so we should be able to fix this pretty easily.

**Comment by poplarShift** [comment]
Where does the application of Cycle live?

**Comment by philippjfr** [comment]
Got a fix in https://github.com/pyviz/holoviews/pull/3707

**Comment by poplarShift** [comment]
Even better, thanks a lot!
