### ISSUE TITLE
Dynamic map does not update width

### ISSUE THREAD

**Issue by mdk73** [pyviz/holoviews#3714]
I am using the tutorial from here [http://pyviz.org/tutorial/12_Parameters_and_Widgets.html](url) as a start. The style options as in the tutorial are working. When I try to add ```width``` as an additional parameter, the image is not corresponding to changes of the width-slider.

```python
import param, panel as pn, numpy as np
import holoviews as hv
hv.extension('bokeh')

class StyleOptions(param.Parameterized):
    alpha = param.Magnitude(default=0.8)
    color = param.ObjectSelector(default='red', objects=['red', 'green', 'blue'])
    line_width = param.Number(default=1, bounds=(0, 10)) 
    #width = param.Number(500, bounds=(100, 500))
    
options = StyleOptions(name="")
pn.Row(options.param)

curve   = hv.Curve(np.sin(np.linspace(0, np.pi*3, 100)))
dmap    = hv.DynamicMap(lambda **kw: curve.opts(**kw), streams=[options])

pn.Row(options.param, dmap)
```
I get the following warning (which unfortunately is failing to mean anything useful to me):
```
WARNING:param.: The Parameterized instance has instance parameters created using new-style param APIs, which are incompatible with .params. Use the new more explicit APIs on the .param accessor to query parameter instances.To query all parameter instances use .param.objects with the option to return either class or instance parameter objects. Alternatively use .param[name] indexing to access a specific parameter object by name.
```
The resulting image is corresponding to the sliders
![styleoptions](https://user-images.githubusercontent.com/2737768/57796061-c0a60580-7747-11e9-88ae-df984fb715b0.png)

When I add ```width = param.Number(500, bounds=(100, 500))``` to the class ```StyleOptions```, the image is rendered with the correct width, but is not corresponding to changes of the width-slider.
![styleoptions_with_width](https://user-images.githubusercontent.com/2737768/57796373-75d8bd80-7748-11e9-95a0-72366bcbef60.png)

**Comment by philippjfr** [comment]
Fixed by https://github.com/pyviz/holoviews/issues/3714
