### ISSUE TITLE
point inside polygon

### ISSUE THREAD

**Issue by emryslda** [pyviz/holoviews#3718]
Hy guys,
Is it possible to extract from an holoviews image all the points inside the polygon (done with FreehandDraw or PolyDraw functions) ?

**Comment by philippjfr** [comment]
This is a usage question so should probably be filed on StackOverflow or asked on Gitter. I also think this particular question is beyond the scope of holoviews. I think you will want to convert the drawn polygon to a mask (e.g. look at this answer https://stackoverflow.com/questions/3654289/scipy-create-2d-polygon-mask) and then you can multiply that mask with your image to get the datapoints inside the polygon.
