### ISSUE TITLE
DynamicMap does not rescale for an additional title_format

### ISSUE THREAD

**Issue by Gerenuk** [pyviz/holoviews#3722]
When a DynamicMap starts with empty title_format, it does not rescale once the title_format appears later with a pipe input. The title is cut off in the display and does not cause the plot to re-adjust:

    pipe = Pipe(data=[])
    p = hv.DynamicMap(
        lambda data: hv.Curve(data).options(title_format=str(data[-1]) if data else ""),
        streams=[pipe],
    ).options(framewise=True)   # starts with empty title
    display(p)

    pipe.send([1,2,3])

(Holoviews. 1.12.1, JupyterLab, PyViz extension)

(Somehow it may work when called a second time, sometimes not)

**Comment by philippjfr** [comment]
This is really a bokeh bug and should ideally also be raised there with a pure bokeh example demonstrating that the layout isn't recomputed when adding a title.

**Comment by philippjfr** [comment]
Closing, can't do anything about this at the HoloViews level.
