### ISSUE TITLE
When used with Image: Buffer throws ValueError on sending update 

### ISSUE THREAD

**Issue by mdk73** [pyviz/holoviews#3723]
I am using the tutorial [http://holoviews.org/user_guide/Streaming_Data.html](url), section ''A simple example: Brownian motion '' as a start and try to modify it for use with ```hv.Image.```
The initial ```DynamicMap``` is displayed, but on ```Buffer.send(...)``` I get an error.

```python
import pandas as pd
import numpy as np
import holoviews as hv
from holoviews.streams import Buffer
hv.extension('bokeh')

# returns 3x3 array with random values
def imgdata():
    imgdata = {}
    m, n = 3, 3
    for item in list(range(0,m)): imgdata[str(item)] = np.random.randn(n)
    return pd.DataFrame(data=imgdata).values

example = imgdata()
value_stream = Buffer(example, length=1, index=False)
img_dmap = hv.DynamicMap(hv.Image, streams=[value_stream])
img_dmap
```
This gives me the following image: 
![image_buffer](https://user-images.githubusercontent.com/2737768/57981547-065d1980-7a39-11e9-8d5d-7499a1477808.png)

Now I try try to send new image values
```python
value_stream.send(imgdata())
```
and get a ValueError
```python
Traceback (most recent call last):
  File "C:\Users\mdk\Anaconda3\envs\paneldev\lib\site-packages\holoviews\plotting\util.py", line 272, in get_plot_frame
    return map_obj[key]
  File "C:\Users\mdk\Anaconda3\envs\paneldev\lib\site-packages\holoviews\core\spaces.py", line 1324, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "C:\Users\mdk\Anaconda3\envs\paneldev\lib\site-packages\holoviews\core\spaces.py", line 1097, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "C:\Users\mdk\Anaconda3\envs\paneldev\lib\site-packages\holoviews\core\spaces.py", line 733, in __call__
    ret = self.callable(*args, **kwargs)
  File "C:\Users\mdk\Anaconda3\envs\paneldev\lib\site-packages\holoviews\element\raster.py", line 321, in __init__
    raise ValueError('Density along Image axes could not be determined. '
ValueError: Density along Image axes could not be determined. If the data contains only one coordinate along the x- or y-axis ensure you declare the bounds and/or density.
```

As I did not find any documentation on using ```Buffer``` with ```Image```, my approach might be not the correct one...

**Comment by poplarShift** [comment]
This is a usage question and should probably be asked on Stackoverflow :) My guess is the problem comes from `Image` using 2D array data, whereas `Buffer` supplies tabular data (i.e. 1D).

**Comment by mdk73** [comment]
The reason I decided to open an issue is that the initial image is created, and only the update (using the same method as for initialization) is not working.
But you might be right, it could still be a usage error rather than an holoviews error.

**Comment by mdk73** [comment]
While I still did not find the possible error in my code above, the following code using ```Stream``` is working without errors:

```python
import holoviews as hv
from holoviews import streams
from holoviews.streams import Stream
import pandas as pd
import numpy as np
hv.extension('bokeh')

def set_df():
    imgdata = {}
    m, n = 2, 2
    for item in list(range(0,m)): imgdata[str(item)] = np.random.randn(n)
    return pd.DataFrame(imgdata)

def set_images(df=set_df()):
    return hv.Image(df.values)

DF = Stream.define('DataFrame', df=set_df())

dmap = hv.DynamicMap(set_images, streams=[DF(df=set_df())])
dmap
```
Updates with:
```python
dmap.event(df=set_df())
```

So I am strongly suspecting that I misused ```Buffer``` in some way...

**Comment by poplarShift** [comment]
> So I am strongly suspecting that I misused `Buffer` in some way...

As I said, it's for tabular data only.
