### ISSUE TITLE
Some data points are not plotted when using `invert_axes=True` when one axis is categorical

### ISSUE THREAD

**Issue by justinbois** [pyviz/holoviews#3748]
In some instances when I make identical `Scatter` plots with a categorical axis, when I use `invert_axes=True` (soon to be called `swap_axes=True`), some data points are omitted from the plot. This problem does not happen when I do not invert the axes, nor when both variables in the plot are numerical. There also seems to be some strange conversion of the numerical data to integers. See the example below.

```python
import holoviews as hv
from bokeh.sampledata.autompg import autompg as df
hv.extension('bokeh')

# Make cylinder a string to force categorical
df['cyl_str'] = df['cyl'].astype(str)

# Plots with integer cylinder
vertical_int = hv.Scatter(df, 'cyl', 'mpg'
    ).sort(
    ).opts(padding=0.1, jitter=0.5,
           color='cyl', cmap='Dark2', title='Ok')

horizontal_int = hv.Scatter(df, 'cyl', 'mpg'
    ).sort(
    ).opts(invert_axes=True, padding=0.1, jitter=0.3, 
           color='cyl', cmap='Dark2', title='Ok')

# Plots with string cylinder
vertical_str = hv.Scatter(df, 'cyl_str', 'mpg'
    ).sort(
    ).opts(padding=0.1, jitter=0.5,
           color='cyl_str', cmap='Dark2', show_legend=False,
           title='Ok')

horizontal_str = hv.Scatter(df, 'cyl_str', 'mpg'
    ).sort(
    ).opts(invert_axes=True, padding=0.1, jitter=0.3, 
           color='cyl_str', cmap='Dark2', show_legend=False,
           title='Missing points')


(vertical_int + horizontal_int + vertical_str + horizontal_str).cols(2)
```

<img width="614" alt="Screen Shot 2019-05-30 at 17 26 23" src="https://user-images.githubusercontent.com/1873517/58673407-178f0b80-8300-11e9-9722-e2adbc2cdb7c.png">

Version info:
```
CPython 3.7.3
IPython 7.5.0

pandas 0.24.2
bokeh 1.1.0
holoviews 1.12.1
jupyterlab 0.35.5
```

**Comment by justinbois** [comment]
And, as a possibly useful followup, here is another example which perhaps shows more clearly that data points that are not within some distance of an integer value are not displayed in the plot.

```python
import numpy as np
import pandas as pd
import holoviews as hv
from bokeh.sampledata.autompg import autompg as df
hv.extension('bokeh')

np.random.seed(1138312)

df = pd.DataFrame(
    data=dict(a=np.arange(60, dtype=float) + 0.01*np.random.random(60), 
              label=['label 1', 'label 2']*30))

not_ok_plot = hv.Scatter(df,
        kdims='label',
        vdims='a'
    ).opts(hv.opts.Scatter(
        padding=0.05,
        invert_axes=True)
    )

ok_plot = hv.Scatter(df,
        kdims='label',
        vdims='a'
    ).opts(hv.opts.Scatter(
        padding=0.05)
    )

ok_plot + not_ok_plot
```

As a workaround, the following code does not have the data deletion problem:
```python
ok_plot = hv.Scatter(df,
        kdims='a',
        vdims='label'
    ).opts(hv.opts.Scatter(
        padding=0.05)
    )
```
This is not useable in applications that need jittering, though, since we can only jitter `vdims`.

<img width="608" alt="Screen Shot 2019-05-31 at 08 54 08" src="https://user-images.githubusercontent.com/1873517/58718113-ad1eaf80-8381-11e9-8319-4656d2ba03e3.png">

**Comment by poplarShift** [comment]
Just stopping by to note that this is only in the bokeh backend and apparently only for `Scatter`. May be related to handling of categorical axes (`Bars` doesn't have this problem) and may be related to (just a guess on my side) by https://github.com/pyviz/holoviews/pull/3385.

**Comment by jbogaardt** [comment]
This is an issue for `Bars` as well at least for matplotlib. This one doesn't work:
```python
import holoviews as hv
hv.extension('matplotlib')
hv.Bars((['Apple','Banana'],[2,3])).opts(invert_axes=True)
```
holoviews version = 1.12.3

**Comment by philippjfr** [comment]
Seems to be fixed.
