### ISSUE TITLE
scatter_matrix for large data

### ISSUE THREAD

**Issue by rtmatx** [pyviz/holoviews#3750]
Hi,

I experimented with scatter_matrix and can use the function `dynspread(datashade(holoviews.scatter-matrix(df, c='some_column)))` to get an interactive plot for large data. Is there any way to retain the colors of the holoviews output generated using `some_column` while doing this. So far, I can only get a single color with varying saturation level based on its density across all plots.

Thanks

**Comment by poplarShift** [comment]
This behaviour is as expected, you have to pass an `aggregator` argument as per http://holoviews.org/user_guide/Large_Data.html

**Comment by jbednar** [comment]
And you can pass a single color as a list, if you don't want varying saturation level (e.g. `cmap=["#FF0000"]` in datashade), where you do have to supply the color again even if you already defined it as an option.  But then you'll get overplotting wherever points overlap; your choice!

**Comment by rtmatx** [comment]
Thanks @jbednar. I just need to see the color spread for a specific dataset. Your suggestions is helpful :)
