### ISSUE TITLE
[Question] Check current styling options 

### ISSUE THREAD

**Issue by cocoaaa** [pyviz/holoviews#3754]
Hi, 

I often try to figure out what exact styling options are being applied to my current Element instance, but couldn't figure out a clean way to do so.  Is there a way to check the final styling options for a specific `hv.Element` instance after applying all style-specifications? That is, after resolving any potential conflicts from the defaults configurations, the cell-wise style configurations (using `%%opts`), and the instance-wise configurations (using `%%opt` on a finer group/label or `.opts()` directly on the instance -- eg. `%%opts Image.GroupA.Special [bounds=small_bounds]`,or `imgSpecial.opts(cmap='fire'`))? 

This would be helpful when I have multiple `opts` specifications applicable to the same element type, yet at different level of granuality (group level, label level..), as well as when plotting multiple Element-types whose configs can be affected by the config specified for other Element types, eg. `bounds`, `extents` of `gv.Feature` and `gv.Image`.

Another releated question is, what would be a recommended way of setting the opts to the current defaults?
This [post](https://is.gd/TftBNo) suggests, `myImg.opts(clone=False)` but I would expect a method like `myImg.opts.reset_defaults()`.  If there is such method, would this `reset to default` method defaults the settings to the holoviews' initial defaults, or to the current session-wise default (which may have been changed using `opts.default`)?

Thank you!

**Comment by poplarShift** [comment]
This may help: https://stackoverflow.com/questions/54403554/retrieve-options-already-applied-to-a-holoviews-object

**Comment by cocoaaa** [comment]
Thank you, that definitely helps!
