### ISSUE TITLE
Selection1D with the source of hv.Table do not receive the selected indices

### ISSUE THREAD

**Issue by cocoaaa** [pyviz/holoviews#3765]
Hi, I'm trying to use a linked stream `Selection1D` to get the indices of selected rows from a hv.Table object.
```python
df = pd.DataFrame(np.random.rand(100,3), columns=['1','2','3'])

table = hv.Table(data=df)
sel = hv.streams.Selection1D(source=table)
table
```
but `sel.contents` always return `{'index': []}` even when some rows are selected on the table.

![image](https://user-images.githubusercontent.com/8037983/59153043-cb318300-8a05-11e9-818c-2861bda1cda8.png)
(There are two tables shown because I'm opening two notebook views in the Jupyterlab)

While trying to figure it out, I opened up a new notebook, and simply tried
```python
import holoviews as hv
hv.Curve([1,2,3])
```
and now the plot is not being displayed... 
![image](https://user-images.githubusercontent.com/8037983/59153093-e8b31c80-8a06-11e9-9d14-fe43abb98dc3.png)

Could you help me figure out what may be causing these? Could they be related somehow?

Thank you!

**Comment by philippjfr** [comment]
Can't immediately reproduce this, could you report the versions of holoviews and param you are using?

**Comment by youngsaj** [comment]
I'm unfortunately just now experiencing this after updated to the latest (conda-forge) param 1.9.1, bokeh 1.3.4, hv 1.12.5, jupyter lab 1.0.5, pyviz_comms 0.7.2, jupyter lab @pyviz/jupyterlab_pyviz 0.8.   I did have an awful time getting jupyter lab updated to work with special npm server on air gapped network, but libraries are loading and holoviews tables are displaying.  The very thing above is happening no index when selected.

**Comment by philippjfr** [comment]
@youngsaj See any errors on your JS console?

**Comment by youngsaj** [comment]
Uncaught Error: invalid bbox{left: 95, top:10, right:42, bottom:10} 
at new t (eval ......

Sorry it's on another system I can't copy paste here.

**Comment by youngsaj** [comment]
I'm also getting a couple Failed to load resource: net::ERR_NAME_NOT_RESOLVED

**Comment by philippjfr** [comment]
Okay thanks, those don't appear to be related.

**Comment by youngsaj** [comment]
Just needed to wrap a return with pn.Column to display a bokeh view so bbox error was my issue.

**Comment by youngsaj** [comment]
wrapping the table I'm wrapping with pn.Pane(pn.Row(my_hvtable))

**Comment by youngsaj** [comment]
bokeh stream (SelectXY()) zoom selection isn't working for dynamic map either.  Now I wonder if my install is messed up after that jupyter lab update?

**Comment by youngsaj** [comment]
A fresh environment based on holoviz, along with jupyterlab, jupyter install labextension @pyviz/jupyterlab_pyviz, and intake solved the problem for me
