### ISSUE TITLE
New rcparam warnings from matplotlib

### ISSUE THREAD

**Issue by jsignell** [pyviz/holoviews#3766]
Ran into this while running through pyviz tutorial:

<img width="985" alt="Screen Shot 2019-06-10 at 3 42 39 PM" src="https://user-images.githubusercontent.com/4806877/59222205-f1d2f380-8b96-11e9-9fdc-2b49ff343e38.png">

**Comment by philippjfr** [comment]
Seem like a high-priority. Let's aim to get this into a 1.12.4 release by next week.

**Comment by poplarShift** [comment]
Also see https://github.com/pyviz/holoviews/pull/3745

**Comment by zertrin** [comment]
Any news on 1.12.4 release to get rid of these warning with mpl 3.1?

**Comment by jsignell** [comment]
We are going to try to release by the end of this week.

**Comment by zertrin** [comment]
Hi, I've been slow to test, but I still have warnings with holoviews 1.12.5 and matplotlib 3.1.1:

```
Versions:
--------------------------------
python			3.7.3
numpy			1.17.0
pandas			0.24.2
matplotlib		3.1.1
seaborn			0.9.0
holoviews		1.12.5
```

![image](https://user-images.githubusercontent.com/1447163/63409829-8756f300-c424-11e9-8532-0a73c2297d2f.png)

Can we reopen this issue?

**Comment by zertrin** [comment]
Just in case you need a quick reproducer based on a fresh environment: https://anaconda.org/zertrin/2019-09-23-holoview-reproduce-bug-rcparams_warnings_matplotlib/notebook

**Comment by philippjfr** [comment]
Seems to be fixed in my testing of master.

**Comment by philippjfr** [comment]
Also thanks @zertrin, reproducible examples are **super** helpful!

**Comment by philippjfr** [comment]
Reopening, realized I didn't check with the appropriate matplotlib version.

**Comment by zertrin** [comment]
Is there a specific commit that solved this issue?

**Comment by philippjfr** [comment]
https://github.com/pyviz/holoviews/commit/23ead437bf63e7616d3d8e5487cb49256f04cfad

**Comment by philippjfr** [comment]
It looks like that commit made it into 1.12.4 though so I'm confused.

**Comment by philippjfr** [comment]
Still seeing the issue in some cases 😞
