### ISSUE TITLE
UserWarning: Config option `use_jedi` not recognized by `IPCompleter`.

### ISSUE THREAD

**Issue by mirik123** [pyviz/holoviews#3782]
This error is show when I'm trying to import bokeh:
`hv.extension('bokeh')`

Product versions:
- numpy 1.16.4
- pandas 0.24.4
- bokeh 1.2.0
- holoviews 1.12.3
- hvplot 0.4.0

**Comment by philippjfr** [comment]
Which version of IPython do you have?

**Comment by mirik123** [comment]
Python 3.6.8

**Comment by philippjfr** [comment]
Sorry, I was asking about **I**Python not Python itself.

**Comment by mirik123** [comment]
IPython 5.5.0

**Comment by philippjfr** [comment]
Could you try upgrading IPython to a more recent version? We should still make sure we are compatible with older versions but upgrading should be an easy fix.

**Comment by poplarShift** [comment]
Hm, I've seen this crop up in continuous integration too though IIRC.

**Comment by mirik123** [comment]
I upgraded ipython to version 7.5.0 and now it is working.
