### ISSUE TITLE
Using hv.Vectorfield: AttributeError: 'float' object has no attribute 'cos'

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoviews#3784]
```
import numpy as np
import holoviews as hv
hv.extension('bokeh')
hv.VectorField(([-1, 0, 1, 2, 3], np.deg2rad([0, 45, 90, 180, 360])))
```

![image](https://user-images.githubusercontent.com/15331990/59796361-2713cb80-9292-11e9-8bb6-b127cc71901c.png)

**Comment by ahuang11** [comment]
from @ea42gh 
```
>>> h=hv.VectorField(([-1, 0, 1, 2, 3], np.deg2rad([0, 45, 90, 180, 360])))
>>> h.data
   x         y Angle Magnitude
0 -1  0.000000   NaN       NaN
1  0  0.785398   NaN       NaN
2  1  1.570796   NaN       NaN
3  2  3.141593   NaN       NaN
4  3  6.283185   NaN       NaN
````

This works:
`hv.VectorField(([-1, 0, 1, 2, 3], [-1, 0, 1, 2, 3], np.deg2rad([0, 45, 90, 180, 360])))`

**Comment by philippjfr** [comment]
Definitely down to the datatype and missing nans:

```
np.cos(np.array([float('nan')], dtype='object'))
```

The solution here is that to ensure that the pandas interface will not let you create an vectorfield without all the dimensions.
