### ISSUE TITLE
[Question] HeatMap Tap stream of a correlation matrix 

### ISSUE THREAD

**Issue by StevenLi-DS** [pyviz/holoviews#3789]
I want to make a correlation heatmap for a DataFrame and a regression plot for each pair of the variables. I have tried to read all the docs and am still having a very hard time to connect two plots so that when I tap the heatmap, the corresponding regression plot can show up.

Here's some example code:

```python
import holoviews as hv
from holoviews import opts
import seaborn as sns
import numpy as np
import pandas as pd
hv.extension('bokeh')

df = sns.load_dataset('tips')
df = df[['total_bill', 'tip', 'size']]

corr = df.corr()
heatmap = hv.HeatMap((corr.columns, corr.index, corr))\
            .opts(tools=['tap', 'hover'], height=400, width=400, toolbar='above')

m, b = np.polyfit(df.tip, df.total_bill, deg=1)
x = np.linspace(df.tip.min(), df.tip.max())
y = m*x + b

curve = hv.Curve((x, y))\
          .opts(height=400, width=400, color='red', ylim=(0, 100))
points = hv.Scatter((df.tip, df.total_bill))

hv.Layout((points * curve) + heatmap).cols(2)
```

![image](https://user-images.githubusercontent.com/33796896/59961519-dfb25880-94a6-11e9-94ae-98f164a0d98f.png)

Any helps, please...

**Comment by poplarShift** [comment]
Is this not what you want? http://holoviews.org/reference/streams/bokeh/Tap.html

**Comment by StevenLi-DS** [comment]
@poplarShift I read this example and many examples from the doc. This example uses dataset of holoview and I tried and for some reasons, I just couldn't convert my dataframe in the right way.

**Comment by StevenLi-DS** [comment]
https://stackoverflow.com/questions/56716123/holoviews-heatmap-tap-stream-of-a-correlation-matrix

**Comment by poplarShift** [comment]
Great! Closing this now.

**Comment by StevenLi-DS** [comment]
@poplarShift if I understand this correctly. This is no way I can save a .html file while the tap stream is still working right?
