### ISSUE TITLE
[Improvement] Allow for open ended plot bounds

### ISSUE THREAD

**Issue by cristi-neagu** [pyviz/holoviews#3794]
Hello,

I think it would be useful to allow for open ended bounds on plots. Right now, a tuple needs to be passed to `xlim` and `ylim`. But as far as i can tell, there's no way to impose a limit on just one side of the axis and leave the other to autoscale. Something like `xlim=(0,)` or `xlim=(0, None)`. I would use this if i want to show the 0 point on the axis for reference, but i want the other end to autoscale.

Or is there a way to achieve this in a natural manner? (As in, other than plotting invisible points)

Thank you.

**Comment by poplarShift** [comment]
Works for me, can you provide an MWE?

**Comment by cristi-neagu** [comment]
Ok, now that's annoying. I tried all sorts of combinations and it wasn't working. Now it does. I think i was probably doing something wrong. Sorry about that.
