### ISSUE TITLE
ImportError: cannot import name 'Dimensioned' from 'holoviews'

### ISSUE THREAD

**Issue by leifulstrup** [pyviz/holoviews#3800]
I am trying the Gapminder example from here - https://github.com/pyviz-demos/gapminder

When executing the code segment from the example jupyter notebook cell:

pn.Column(gm.param,
          pn.Row(gm.hvplot_view, gm.altair_view),
          pn.Row(gm.mpl_view,    gm.plotly_view))

I encounter this error:

ImportError: cannot import name 'Dimensioned' from 'holoviews'

in this code context:
/lib/python3.7/site-packages/panel/pane.py in applies(cls, obj)
    185         if 'holoviews' not in sys.modules:
    186             return False
--> 187         from holoviews import Dimensioned
    188         return isinstance(obj, Dimensioned)
    189 

My environment:
OSX 10.14.5
conda list:
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0  
altair                    3.1.0                    py37_0    conda-forge
anaconda                  2019.03                  py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-project          0.8.2                    py37_0  
appnope                   0.1.0                    py37_0  
appscript                 1.1.0            py37h1de35cc_0  
asn1crypto                0.24.0                   py37_0  
astroid                   2.2.5                    py37_0  
astropy                   3.1.2            py37h1de35cc_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.1.0                   py37_1  
babel                     2.6.0                    py37_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                      py37_1  
backports.os              0.1.1                    py37_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
beautifulsoup4            4.7.1                    py37_1  
bitarray                  0.8.3            py37h1de35cc_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
blosc                     1.15.0               hd9629dc_0  
bokeh                     1.0.4                    py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.2.1            py37h1d22016_1  
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2019.1.23                     0  
certifi                   2019.3.9                 py37_0  
cffi                      1.12.2           py37hb5b8e2f_1  
chardet                   3.0.4                    py37_1  
click                     7.0                      py37_0  
cloudpickle               0.8.0                    py37_0  
clyent                    1.2.2                    py37_1  
colorama                  0.4.1                    py37_0  
confuse                   1.0.0                    pypi_0    pypi
contextlib2               0.5.5                    py37_0  
cryptography              2.6.1            py37ha12b0ac_0  
curl                      7.64.0               ha441bb4_2  
cycler                    0.10.0                   py37_0  
cython                    0.29.6           py37h0a44026_0  
cytoolz                   0.9.0.1          py37h1de35cc_1  
dask                      1.1.4                    py37_1  
dask-core                 1.1.4                    py37_1  
dbus                      1.13.6               h90a0687_0  
decorator                 4.4.0                    py37_1  
defusedxml                0.5.0                    py37_1  
distributed               1.26.0                   py37_1  
docutils                  0.14                     py37_0  
entrypoints               0.3                      py37_0  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                h0a44026_0  
fastcache                 1.0.2            py37h1de35cc_2  
filelock                  3.0.10                   py37_0  
flask                     1.0.2                    py37_1  
flatbuffers               1.11                     pypi_0    pypi
freetype                  2.9.1                hb4e5f40_0  
funcsigs                  1.0.2                    pypi_0    pypi
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.4.0            py37h1de35cc_0  
glib                      2.56.2               hd9629dc_0  
glob2                     0.6                      py37_1  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py37h6ef4df4_2  
greenlet                  0.4.15           py37h1de35cc_0  
h5py                      2.9.0            py37h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
heapdict                  1.0.0                    py37_2  
holoviews                 1.11.0             pyh39e3cac_0    pyviz
html5lib                  1.0.1                    py37_0  
htmlmin                   0.1.12                   pypi_0    pypi
hvplot                    0.3.0                      py_0    conda-forge
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py37_0  
imageio                   2.5.0                    py37_0  
imagesize                 1.1.0                    py37_0  
importlib_metadata        0.8                      py37_0  
intel-openmp              2019.3                      199  
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.4.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
isort                     4.3.16                   py37_0  
itsdangerous              1.1.0                    py37_0  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4                      py37_0  
jedi                      0.13.3                   py37_0  
jinja2                    2.10                     py37_0  
jpeg                      9b                   he5867d9_2  
jsonschema                3.0.1                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
jupyterlab                0.35.4           py37hf63ae98_0  
jupyterlab_server         0.2.0                    py37_0  
keyring                   18.0.0                   py37_0  
kiwisolver                1.0.1            py37h0a44026_0  
krb5                      1.16.1               hddcf347_7  
lazy-object-proxy         1.3.1            py37h1de35cc_2  
libarchive                3.3.3                h786848e_5  
libcurl                   7.64.0               h051b688_2  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
liblief                   0.9.0                h2a1bed3_2  
libpng                    1.6.36               ha441bb4_0  
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.8.0                ha12b0ac_4  
libtiff                   4.0.10               hcb84e12_2  
libxml2                   2.9.9                hab757c2_0  
libxslt                   1.1.33               h33a18ac_0  
llvmlite                  0.28.0           py37h8c7ce04_0  
locket                    0.2.0                    py37_1  
lxml                      4.3.2            py37hef8c89e_0  
lz4-c                     1.8.1.2              h1de35cc_0  
lzo                       2.10                 h362108e_2  
markupsafe                1.1.1            py37h1de35cc_0  
matplotlib                3.0.3            py37h54f8f79_0  
mccabe                    0.6.1                    py37_1  
missingno                 0.4.1                    pypi_0    pypi
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.3                      199  
mkl-service               1.1.2            py37hfbe908c_5  
mkl_fft                   1.0.10           py37h5e564d8_0  
mkl_random                1.0.2            py37h27c97d8_0  
modin                     0.5.3                    pypi_0    pypi
more-itertools            6.0.0                    py37_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.1                h3018a27_3  
mpmath                    1.1.0                    py37_0  
msgpack-python            0.6.1            py37h04f5b5a_1  
multipledispatch          0.6.0                    py37_0  
nb_conda                  2.2.1                    py37_0  
nb_conda_kernels          2.2.2                    py37_0  
nbconvert                 5.4.1                    py37_3  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_1  
networkx                  2.2                      py37_1  
nltk                      3.4                      py37_1  
nose                      1.3.7                    py37_2  
notebook                  5.7.8                    py37_0  
numba                     0.43.1           py37h6440ff4_0  
numexpr                   2.6.9            py37h7413580_0  
numpy                     1.16.2           py37hacdab7b_0  
numpy-base                1.16.2           py37h6575580_0  
numpydoc                  0.8.0                    py37_0  
olefile                   0.46                     py37_0  
openpyxl                  2.6.1                    py37_1  
openssl                   1.1.1b               h1de35cc_1    conda-forge
packaging                 19.0                     py37_0  
pandas                    0.24.2           py37h0a44026_0  
pandas-profiling          2.0.3                    pypi_0    pypi
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
panel                     0.1.0a14                   py_0    pyviz/label/dev
param                     1.9.1                      py_0    pyviz/label/dev
parso                     0.3.4                    py37_0  
partd                     0.3.10                   py37_1  
path.py                   11.5.0                   py37_0  
pathlib2                  2.3.3                    py37_0  
patsy                     0.5.1                    py37_0  
pcre                      8.43                 h0a44026_0  
pep8                      1.7.1                    py37_0  
pexpect                   4.6.0                    py37_0  
phik                      0.9.8                    pypi_0    pypi
pickleshare               0.7.5                    py37_0  
pillow                    5.4.1            py37hb68e598_0  
pip                       19.0.3                   py37_0  
pkginfo                   1.5.0.1                  py37_0  
plotly                    3.10.0                     py_0    plotly
pluggy                    0.9.0                    py37_0  
ply                       3.11                     py37_0  
prometheus_client         0.6.0                    py37_0  
prompt_toolkit            2.0.9                    py37_0  
psutil                    5.6.1            py37h1de35cc_0  
ptyprocess                0.6.0                    py37_0  
py                        1.8.0                    py37_0  
py-lief                   0.9.0            py37h1413db1_2  
pycodestyle               2.5.0                    py37_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.19                     py37_0  
pycrypto                  2.6.1            py37h1de35cc_9  
pycurl                    7.43.0.2         py37ha12b0ac_0  
pyflakes                  2.1.1                    py37_0  
pygments                  2.3.1                    py37_0  
pylint                    2.3.1                    py37_0  
pyodbc                    4.0.26           py37h0a44026_0  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.3.1                    py37_0  
pyqt                      5.9.2            py37h655552a_2  
pyrsistent                0.14.11          py37h1de35cc_0  
pysocks                   1.6.8                    py37_0  
pytables                  3.5.1            py37h5bccee9_0  
pytest                    4.3.1                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.5.0                    py37_0  
pytest-doctestplus        0.3.0                    py37_0  
pytest-openfiles          0.3.2                    py37_0  
pytest-pylint             0.14.0                   pypi_0    pypi
pytest-remotedata         0.3.1                    py37_0  
python                    3.7.3                h359304d_0  
python-dateutil           2.8.0                    py37_0  
python-libarchive-c       2.8                      py37_6  
python.app                2                        py37_9  
pytz                      2018.9                   py37_0  
pyviz_comms               0.7.2                      py_0    pyviz/label/dev
pywavelets                1.0.2            py37h1d22016_0  
pyyaml                    5.1              py37h1de35cc_0  
pyzmq                     18.0.0           py37h0a44026_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 0.5.7                    py37_1  
qtconsole                 4.4.3                    py37_0  
qtpy                      1.7.0                    py37_1  
ray                       0.7.0                    pypi_0    pypi
readline                  7.0                  h1de35cc_5  
redis                     3.2.1                    pypi_0    pypi
requests                  2.21.0                   py37_0  
retrying                  1.3.3                    py37_2  
rope                      0.12.0                   py37_0  
ruamel_yaml               0.15.46          py37h1de35cc_0  
scikit-image              0.14.2           py37h0a44026_0  
scikit-learn              0.20.3           py37h27c97d8_0  
scipy                     1.2.1            py37h1410ff5_0  
seaborn                   0.9.0                    py37_0  
send2trash                1.5.0                    py37_0  
setproctitle              1.1.10                   pypi_0    pypi
setuptools                40.8.0                   py37_0  
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37h0a44026_0  
six                       1.12.0                   py37_0  
snappy                    1.1.7                he62c110_3  
snowballstemmer           1.2.1                    py37_0  
sortedcollections         1.1.2                    py37_0  
sortedcontainers          2.1.0                    py37_0  
soupsieve                 1.8                      py37_0  
sphinx                    1.8.5                    py37_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-websupport  1.1.0                    py37_1  
spyder                    3.3.3                    py37_0  
spyder-kernels            0.4.2                    py37_0  
sqlalchemy                1.3.1            py37h1de35cc_0  
sqlite                    3.27.2               ha441bb4_0  
statsmodels               0.9.0            py37h1d22016_0  
sympy                     1.3                      py37_0  
tblib                     1.3.2                    py37_0  
terminado                 0.8.1                    py37_1  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.9.0                    py37_0  
tornado                   6.0.2            py37h1de35cc_0  
tqdm                      4.31.1                   py37_1  
traitlets                 4.3.2                    py37_0  
typed-ast                 1.4.0                    pypi_0    pypi
typing                    3.7.4                    pypi_0    pypi
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.24.1                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.14.1                   py37_0  
wheel                     0.33.1                   py37_0  
widgetsnbextension        3.4.2                    py37_0  
wrapt                     1.11.1           py37h1de35cc_0  
wurlitzer                 1.0.2                    py37_0  
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.1.5                    py37_0  
xlwings                   0.15.4                   py37_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.3.1                h0a44026_3  
zict                      0.1.4                    py37_0  
zipp                      0.3.3                    py37_1  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0

**Comment by philippjfr** [comment]
The hvplot version you are getting is quite outdated, you'd want hvplot 0.4.0.

**Comment by leifulstrup** [comment]
Philipp, thank you. I followed the conda install instructions and it kept loading these earlier versions. I'll figure out how to get everything updated.  Appreciate the rapid response. Looking forward to using your great tools.

**Comment by jbednar** [comment]
One thing you can do if you're having trouble is to go to [status.pyviz.org](http://status.pyviz.org) to see what the latest versions of things are, and then explicitly specify them in your conda install command. E.g. `conda install panel=0.6 hvplot=0.4 holoviews=1.12.3`.

**Comment by leifulstrup** [comment]
James, thank you. I'll try that now.

**Comment by philippjfr** [comment]
Wonder why you're getting these old versions by default though. Seems very strange.

**Comment by leifulstrup** [comment]
This solved it for me:

conda install -c conda-forge panel=0.6 hvplot=0.4 holoviews=1.12.3 altair=3.1.0 plotly=3.10.0

**Comment by leifulstrup** [comment]
James and Philipp, thank you both for the fast response and help. I recently set up Anaconda from scratch and kept trying to update it but could not get the more recent versions of the packages. I'm sure it is "operator error" on my side. I appreciate the help. It's working great in my Jupyter notebook. Looking forward to trying it with a real application I'm working on.
