### ISSUE TITLE
PointDraw missing `styles`

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoviews#3819]
Seems a bit inconsistent that BoxEdit and PolyDraw both have the styles kwd, but not PointDraw

**Comment by philippjfr** [comment]
That would be greatly appreciated! Let me know if you need any pointers. The basics are that you need to look at hv.streams.PolyDraw and copy the definition to hv.stream.PointDraw. Next you need to look at PolyDrawCallback in holoviews/plotting/bokeh/callbacks.py and implement the same styles handling for PointDraw.

**Comment by srp3003** [comment]
I have raised pull request #4063, however I am pretty sure I am missing something. Are there any tests for PointDraw that I can run first?
