### ISSUE TITLE
Inconsistent `label` argument behaviour for Points?

### ISSUE THREAD

**Issue by Thalos12** [pyviz/holoviews#3825]
When using `Points` to create a plot the `label` argument behaves strangely.
If more than one `Points` instances are overlaid the legend with the various labels is created, as I would expect.
On the other hand, if only one `Point` object is present the `label`is used as the title of the plot.
The image below shows what I mean.

![immagine](https://user-images.githubusercontent.com/13919407/61385906-9097f180-a8b3-11e9-9d44-5a5919a0f1dc.png)

The code I used to make these plots:

```python
%%opts RGB Points Scatter Curve [width=400]

hv.Points(np.column_stack((magpos,magerrσ)), label='stddev').opts(padding=0.1) + hv.Points(np.column_stack((magpos,magerr-magerrq16)), label='16th quantile').opts(color='r') * hv.Points(np.column_stack((magpos,magerrq84-magerr)), label='84th quantile').opts(color='g')
```

I find it weird, but maybe it is the desired behaviour?
Anyway, I need to create the legend so that my plot will all look the same and I would like to ask for some guidance.

PS: I have been using Holoviews just for a week, so I may have missed something and probably got some specific terms wrong, please excuse me.

**Comment by jlstevens** [comment]
> I find it weird, but maybe it is the desired behaviour?

I think this was the intended behavior - a legend with only a single item is also fairly strange so we opted to set the title instead. 

> Anyway, I need to create the legend so that my plot will all look the same and I would like to ask for some guidance.

I haven't tested it but an `NdOverlay` should make a legend appear for the items it contains. I'm not sure whether there is special handling or not in the case of single item though...

**Comment by Thalos12** [comment]
Thanks a lot for the suggestion, I will try it!

**Comment by poplarShift** [comment]
My workaround is to append a an empty elements, like `element * hv.Curve([])` or similar. That will make a legend with one entry.

**Comment by Thalos12** [comment]
@jlstevens @poplarShift sorry if I am answering late.

Both solutions achieve what I want!
I actually prefer `element * hv.Curve([])`, but I may change my decision as I learn more about Holoviews.

Thanks a lot for your help and your time!
