### ISSUE TITLE
ylim not working in bar chart

### ISSUE THREAD

**Issue by sophiamyang** [pyviz/holoviews#3838]
I am trying to define `ylim`. However, ylim won't work with barchart:
```python
df = pd.DataFrame([['group A', 10],['group B',20]], columns=['A','B'])
df.hvplot.bar('A', 'B', ylim=(0,100))
```
It works when I do `df.hvplot.bar('A', 'B', fields={'B': dict(range=(0, 100))})`.

However, I am not sure how to set ylim for stacked bar chart. Both `ylim` and defining fields won't work for stacked bar charts:
```python
df = pd.DataFrame([['group A', 10, 30],['group B',20, 40]], columns=['A','B','C']) 
df.hvplot.bar('A', ['B','C'], stacked=True, ylim=(0,100))
```

I'd really appreciate it if ylim works. Thanks!

**Comment by philippjfr** [comment]
Seems to be a holoviews bug, so transferring here.

**Comment by poplarShift** [comment]
Last time I checked setting the range on either the dimension or via `.redim.range()` worked, so that should be good as a workaround.
