### ISSUE TITLE
HoloMap/DynamicMap Slider disappears when rendered in Bokeh

### ISSUE THREAD

**Issue by rusiano** [pyviz/holoviews#3844]
Hi everyone,

I am trying to make a visualization dashboard with Bokeh and one of the plots should be a heatmap that changes according to one variable. I discovered that I can get what I want very easily with HoloMap, since it provides a handy slider.

Yet, when I want to create a bokeh Figure out of my HoloMap (since I cannot use the latter in bokeh layouts), the slider disappears.

Reproducible example:

```
import numpy as np
import holoviews as hv
from bokeh.io import show as bk_show, output_notebook as bk_output_notebook

hv.extension('bokeh')
bk_output_notebook()

obs_hmap = hv.HoloMap(
    {i: hv.Image(np.random.randn(10, 10), bounds=(0,0,3,3))
     for i in range(3)}, 
     kdims='Observation').opts(cmap='RdYlGn')

# shows the plot with slider
obs_hmap

# shows the plot without slider
bk_show(hv.render(obs_hmap))
```

Can someone help me on this matter?

**Comment by philippjfr** [comment]
Sorry for the late response, first question is why you would do this in the first place? That said starting in the next release the widgets will be based on panel, which is itself based on bokeh. So you will be able to do:

```python
import numpy as np
import holoviews as hv

obs_hmap = hv.HoloMap(
    {i: hv.Image(np.random.randn(10, 10), bounds=(0,0,3,3))
     for i in range(3)}, 
     kdims='Observation').opts(cmap='RdYlGn')

# shows the plot with slider
bokeh_model = pn.panel(obs_hmap).get_root()
```

That said, this will still not handle the comms for you so there is little point.
