### ISSUE TITLE
xlim/ylim has no effect

### ISSUE THREAD

**Issue by rusiano** [pyviz/holoviews#3846]
Hi everyone,

I cannot get xlim and ylim options to work. I've tried both with a simple hv.HLine and with a hv.Bar and I cannot manage to redefine the axes range with holoviews. The only thing I can do is to convert the holoviews object to a bokeh figure and then change it with bokeh.

Is something broken or am I missing something?

Reproducible example:

```
import numpy as np
import holoviews as hv

bars = (
    hv.Bars(np.random.rand(5,) * 100)
    .opts(ylim=(0, 200))
)

bars
```
![image](https://user-images.githubusercontent.com/32734508/61785308-bb31ff00-ae0b-11e9-803f-a051ad45f5a4.png)

The only way I have to get the desired result is:
```
from bokeh.io import show as bk_show
from bokeh.models import Range1d

bkfig = hv.render(bars)
bkfig.y_range=Range1d(0,200)

bk_show(bkfig)
```
![image](https://user-images.githubusercontent.com/32734508/61785362-da309100-ae0b-11e9-9322-5deb5f18069b.png)

**Comment by rusiano** [comment]
I am sorry I did not find/see [#3838](https://github.com/pyviz/holoviews/issues/3838) earlier. Possible duplicate.

Indeed `.redim.range(y=(0,200)` is a more elegant workaround.

**Comment by philippjfr** [comment]
Closing as duplicate, will push a fix shortly.
