### ISSUE TITLE
hv.DynamicMap does not return hv.HoloMap

### ISSUE THREAD

**Issue by Bixinn** [pyviz/holoviews#3852]
Hi all!
I have a Graph object which its hv.Nodes are connected to hv.DynamicMap which returns a hv.HoloMap and HoloMap does not show up. 

Ideal funcionality: 
When selecting a Node from the hierarchy tree it should appear a HoloMap underneath it with its dropdown/ slider widget to switch from the set of plots (Overlay Objects) I have for that particular Node being Cliked. 

The error: 
Only renders the Graph Object, and shows a warning message such as 
HoloMap can't not be displayed using Bokeh backend. 

hv.DynamicMap works if returning an Overlay: 
I have the hv.DynamicMap working if returning a single Overlay Object. "the first item in the dictionary basically". Each Overlay Object in the dictionary is something like this : area1*area2*line*line2*line3.

What I am doing is : 

df_tree =  {'A': [1,2,3,4] , 
               'B': [5,6,7,8] }

overlay_dict = {'A': [{ 0: Overlay, 1: Overlay, 2: Overlay, 3: Overlay }] , 
                      'B': [{ 0: Overlay, 1: Overlay, 2: Overlay, 3: Overlay }] }

1. I pass the index of the Node inside hv.Dynamic map using Select1D . 
2. I look up the name of the Node selected in df_tree e.g. 'A'.
3. I  filter the overlay dict by  column overlay_dict['A'].
4. I return hv.HoloMap(   overlay_dict['A']  )    <  Doesn't work 

But when returning

return hv.HoloMap(   overlay_dict['A'][0]  )      < It does work

What am I doing wrong? and how could I get this working? 
Any example would be very much appreciated!
Thanks for the help and for putting together this amazing library! 

Elia

**Comment by philippjfr** [comment]
DynamicMaps will never be able to return HoloMaps. It's part of the core design of HoloViews. If you need to dynamically display HoloMaps I'd suggest you look at panel (https://panel.pyviz.org).

**Comment by Bixinn** [comment]
Hi Philip! 
Thanks for your quick response! 
Would it be possible to update the hv.DynamicMap with two streams? 
The first one being the Selection1D from the Node’ Graph object, and the second one being a pointerXY which would capture the second key inside the dict so hv.Dynamic would return an Overlay instead of a hv.HoloMap({0:Overlay, 1:Overlay...}) ?? 

If not I’ll have a look at panel anyway. 
Thank you so much for your help,
Very much appreciated! 

Elia

**Comment by philippjfr** [comment]
>Would it be possible to update the hv.DynamicMap with two streams?

Yes, DynamicMaps can have as many streams as you want.
