### ISSUE TITLE
Get color information 

### ISSUE THREAD

**Issue by eliaborras** [pyviz/holoviews#3858]
Hi, I have a DynamicMap which takes through Streams Selection1d the info in hv.NdOverlay [ Curves objects ] and returns a hv.NdOverlay [ Histogram objects ] 
Like the one following: 

![2F8DD9BC-2827-4901-874A-CF73BC895AEC](https://user-images.githubusercontent.com/38831184/62047797-3546f700-b203-11e9-88d0-040e2d550b29.jpeg)

Is there any way I could get the Curve trace color and map it with the histogram? So both ‘same traces’ have same color? 
Thanks!

**Comment by philippjfr** [comment]
This is a usage question which is best posed on stackoverflow but I'd suggest you simply give each Curve and Histogram an explicit color.
