### ISSUE TITLE
code formating issue in holoviews documentation

### ISSUE THREAD

**Issue by ea42gh** [pyviz/holoviews#3863]
https://holoviz.org/tutorial/Interlinked_Panels.html The solution to the first exercise appears as follows
![Screenshot-from-2019-07-28-16-22-19](https://user-images.githubusercontent.com/13033479/62092946-60ead100-b245-11e9-9c1f-2703d3cace2f.png)

**Comment by philippjfr** [comment]
Thanks for raising this but isnt this a holoviz issue?

**Comment by ea42gh** [comment]
oops! moved it over
