### ISSUE TITLE
multibyte characters in widgets are not working

### ISSUE THREAD

**Issue by archiba** [pyviz/holoviews#3868]
desired result: 
![スクリーンショット 2019-08-02 13 36 57](https://user-images.githubusercontent.com/8945496/62344867-c7fcd400-b52a-11e9-860c-bb4767283f22.png)
(Label in chart title is equal to one in selection box, and it is corresponding)

actual result:
![スクリーンショット 2019-08-02 13 37 38](https://user-images.githubusercontent.com/8945496/62344870-ce8b4b80-b52a-11e9-9ada-0bc4395107a7.png)

Now I'm facing two different problems:
1. Nothing happened when I select item in selection box
2. displayed character in selection box is garbled

To solve problem 1, I think you need to put `ensure_ascii=False` for `json.dumps` at L463 in `holoviews/plotting/widgets/__init__.py`

To solve second one, `static_template` at L64 in `holoviews/plotting/renderer.py` should be

```python
static_template = """
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    {css}
    {js}
  </head>
  <body>
    {html}
  </body>
</html>
"""
```

My code is here:

```python
import pandas
import holoviews
import bokeh
import hvplot.pandas

print('pandas', pandas.__version__)
print('holoviews', holoviews.__version__)
print('bokeh', bokeh.__version__)

holoviews.extension('bokeh')

df = pandas.DataFrame({
    'a': ['あ', 'あ', 'あ', 'あ', 'あ', 'い', 'い', 'い', 'い', 'う', 'う', 'う'],
    'b': [10, 11, 12, 11, 10, 20, 21, 22, 21, 31, 32, 31],
    'c': [0, 1, 2, 1, 0, 0, -1, -2, -1, 1, 2, 3]
})
line_plot_groupby = df.hvplot.line(x='c', y='b', groupby='a', dynamic=False)
renderer = holoviews.renderer('bokeh')
renderer.save(line_plot_groupby, 'line_plot_groupby')
```

pandas 0.25.0
holoviews 1.2.9.post67+g7dd50144
bokeh 1.3.1

**Comment by philippjfr** [comment]
Thanks for the detailed bug report. Would you be willing to submit a PR for the fixes?

**Comment by philippjfr** [comment]
Actually nevermind, the widgets are about to be replaced entirely.

**Comment by archiba** [comment]
Thanks for your reply.
I gave up submit PR for the fixes because it was really difficult to understand how my code should be tested.

Additionally, I think problem can be solved by two different approaches:
1. fix python code to dump json
2. fix javascript code to load json

I don't know which approach is better for holoviews. So I just put issue.
