### ISSUE TITLE
Aspect + height/width doesn't work right

### ISSUE THREAD

**Issue by jsignell** [pyviz/holoviews#3869]
I would expect that these would have the same height

<img width="1020" alt="Screen Shot 2019-08-02 at 10 43 18 AM" src="https://user-images.githubusercontent.com/4806877/62378305-87915c00-b512-11e9-9fdd-6f4dbf8d7518.png">

**Comment by jsignell** [comment]
This is affecting the hvplot work on adding aspect and data_aspect.

**Comment by philippjfr** [comment]
Okay, sadly this is because the only way to ensure a specific aspect in bokeh is to set the frame width/height. I have no way of fixing this without also breaking the `aspect` option.

**Comment by philippjfr** [comment]
Going to close because there is no workaround that works with bokeh's layout engine. We've now added a warning at least.
