### ISSUE TITLE
data_aspect and aspect are flipped?

### ISSUE THREAD

**Issue by jsignell** [pyviz/holoviews#3871]
Not sure if this is the expectation. It felt unintuitive to me. 

<img width="1025" alt="Screen Shot 2019-08-02 at 11 16 04 AM" src="https://user-images.githubusercontent.com/4806877/62380305-efe23c80-b516-11e9-858a-012475a3b6c4.png">

**Comment by philippjfr** [comment]
Sadly the wrong convention for aspect has been around for years so there's no hope of fixing this now without breaking a ton of user code.
