### ISSUE TITLE
Bars not sorting when kdims is more then one

### ISSUE THREAD

**Issue by EnricoDiLello** [pyviz/holoviews#3881]
Starting from the 7-Tabular-Datasets.ipynb example on sorting bar graphs, I added the column 'z' to the dataset:

![Screenshot 2019-08-06 at 16 31 33](https://user-images.githubusercontent.com/40634008/62553676-af145b80-b867-11e9-846b-47255830b3f8.png)

The sorting example stops working if 'z' is added to the kdims, while it works normally if only 'x' is used. Basically, how do I sort columns by vdim when using more than one kdims?

**Comment by philippjfr** [comment]
Duplicate of https://github.com/pyviz/holoviews/issues/3839
