### ISSUE TITLE
4-Gridded_Datasets example does not display

### ISSUE THREAD

**Issue by robmarkcole** [pyviz/holoviews#3899]
When running `holoviews/examples/getting_started/4-Gridded_Datasets.ipynb` all plots are rendered correctly except for `ds.to(hv.Image...`:

![image](https://user-images.githubusercontent.com/11855322/63028834-713ab700-bea7-11e9-8dcc-4c5c1847cc47.png)

**Comment by philippjfr** [comment]
Which version of HoloViews are you using? This appears to be very old. We also need some more detail on whether this is in classic notebook or JupyterLab and if the latter if you have the JupyterLab extension installed.

**Comment by robmarkcole** [comment]
OK I had installed the jupyterlab extension but not restarted my jupyter server. On restart the plot is rendered correctly, sorry for the mistake!
