### ISSUE TITLE
hv.Table index column hide or use DateTimeIndex from pandas.DataFrame

### ISSUE THREAD

**Issue by darynwhite** [pyviz/holoviews#3918]
I'm working on returning a hv.Table of a selection from a hv.Points/Curve overlay. The selection1D is working well, but I have a DateTime index as it is a time series input. To see the timestamps I am currently resetting the index, but then an integer index is displayed no matter what I do. Also, if I do not reset the index on the DataFrame, the timestamps do not display at all.

Is there a method/option to hide the index of a table? Or perhaps a way to use the DateTime index from the source DataFrame?

Happy to work up an example if any of this is unclear.

**Comment by philippjfr** [comment]
The index in the bokeh Table actually bears no relation at all to the pandas index. By default HoloViews ignores pandas indexes which is a longstanding issue we want to work on. So for the time being I don't think there's any option but to reset_index. Separately though I think we should expose an option to disable the default index, for now you can hide it with:

```python
def hide_index(plot, element):
    plot.handles['table'].index_position = None

hv.Table(...).opts(hooks=[hide_index])
```

**Comment by darynwhite** [comment]
Thanks, Philipp! The hook did the trick, for now, an option to hide the default index would be great in the long term. I don't mind reset_index, but I look forward to what comes next for HoloViews as it has been invaluable in development for me.
