### ISSUE TITLE
bokeh backend with string xaxis yields empty plot with xticks in opts

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoviews#3922]
Works with matplotlib but not bokeh
```
import holoviews as hv
import hvplot.pandas
import pandas as pd

hv.extension('matplotlib')
df1 = pd.DataFrame({'coords': ['(0, 1)', '(0, 2)'], 'values': [0, 1]})
df1.hvplot('coords', 'values').opts(xticks=[(0, '(0, 1)N')])

hv.extension('bokeh')
df1 = pd.DataFrame({'coords': ['(0, 1)', '(0, 2)'], 'values': [0, 1]})
df1.hvplot('coords', 'values').opts(xticks=[(0, '(0, 1)N')])
```
![image](https://user-images.githubusercontent.com/15331990/63524596-e9196a80-c4c1-11e9-862c-9fe43aa91f54.png)

**Comment by philippjfr** [comment]
I don't get an empty plot here, but I also don't understand what you're trying to do. The main issue here is that bokeh does not support custom ticking on categorical axes, but from a holoviews perspective everything is working as intended.
