### ISSUE TITLE
dim transforms with "in" operator always evaluate to True for any nonempty list

### ISSUE THREAD

**Issue by poplarShift** [pyviz/holoviews#3928]
For dim transforms, membership operators don't behave as I would expect them to: 

```
from holoviews import dim

print(dim('a') in [])
print(dim('a') in [1, np.std])
print(dim('a') in [dim('a')])
```
gives 
```
False
True
True
```

**Comment by philippjfr** [comment]
This should be fixed but https://github.com/pyviz/holoviews/pull/3927 adds ``isin`` support to dims which might be better to use.

**Comment by philippjfr** [comment]
Right what we'd need is an __lcontains__

**Comment by philippjfr** [comment]
To be honest I don't think this can be solved, you should simply use ``.isin`` instead so I'd like to close this.

**Comment by poplarShift** [comment]
You are probably right, that means we'll have to do avoid `in` (or do type checking beforehand) if something (say, a function) could also be a dim transform.
