### ISSUE TITLE
hv.save saving PNGs with the Bokeh backend is not threadsafe

### ISSUE THREAD

**Issue by zbarry** [pyviz/holoviews#3942]
If you run this, you'll see `[0-19].png` be spit out into your cwd. When you open them up, you will notice that the title of the plot & the color of the image are replicated across multiple files. The intended result is that every plot is different between files.

```python
import holoviews as hv
import concurrent.futures
import numpy as np

hv.extension('bokeh')

def save_im(value):
    im = np.full((512, 512), value)

    im_hv = (
        hv.Image(im, bounds=(0, 0, im.shape[1], im.shape[0]))
        .redim.range(z=(0, 20))
        .options(title_format=f'{value}', colorbar=True, aspect='equal')
    )
    
    hv.save(im_hv, f'{value}.png')

with concurrent.futures.ProcessPoolExecutor(max_workers=10) as executor:
    futures = [executor.submit(save_im, value) for value in range(0, 20)]
```

@jbednar

**Comment by philippjfr** [comment]
Don't think there's anything that we can do about this in HoloViews. Would have to be reraised in bokeh, but even then I'm not sure there's much they can do about this.

**Comment by zbarry** [comment]
Yeah, this is a bokeh thing. @bryevdv had this to say about it in the pyviz gitter channel:

> At a minimum you would almost certainly need to explicitly create and pass a dedicated webdriver per thread
It's possible the the webdriver control state could be made to use thread local storage: https://github.com/bokeh/bokeh/blob/master/bokeh/io/webdriver.py#L97 in which case things could (probably) "just work" without explicit management
If someone wants to make a PR it should go against the landing-2.0 branch
I would consider this a feature, though, since the alternative, explicitly managing webdrivers, is already a thing that can be done
