### ISSUE TITLE
Plots with groupby styles don't display properly

### ISSUE THREAD

**Issue by tomchor** [pyviz/holoviews#3969]
I'm trying to go through the [tutorial for plotting gridded data](http://holoviews.org/user_guide/Gridded_Datasets.html) but I've been running into trouble with the plots that have a slider. 

If I go through the [tutorial](http://holoviews.org/user_guide/Gridded_Datasets.html) everything works well until the groupby example:

`dataset3d.to(hv.Image, ['y', 'z'], 'Value', ['x']) +
hv.HoloMap({x: hv.Scatter3D(dataset3d.select(x=x)) for x in range(3)}, kdims='x'))`

I get some warnings from matplotlib and end up with the following result:

![image](https://user-images.githubusercontent.com/13205162/65165610-fd368600-d9f3-11e9-9d01-330cfd1668ee.png)

Meaning that nothing shows up. If I set the extension as bokeh I get the same results.

I'm using version 1.12.5 of holoviews.

**Comment by jbednar** [comment]
Are you using Jupyter or JupyterLab?  If JLab, have you installed the extension as described at holoviews.org?

The MPL warnings are new and should go away with the next hv release, and for now you can use an older MPL version.

**Comment by tomchor** [comment]
Yes, I had installed the extensions. 
Something weird happened though. I re-installed them and now it appears to be working. I'm not sure what was causing the issue as I'm sure the extensions were installed though

**Comment by jbednar** [comment]
I don't know of any way the Jupyterlab extensions could get clobbered by something else, but it sounds like somehow the JS code defined by the extensions was not available until your reinstall.  If you can find a reproducible problem, please let us know!
