### ISSUE TITLE
Remove xarray isel_points for xarray 0.13.0

### ISSUE THREAD

**Issue by DancingQuanta** [pyviz/holoviews#3970]
Version 0.13.0 of xarray came out yesterday.
I saw in that version the indexing method `isel_points` has been removed.
So with xarray 0.13.0 installed with current version of holoviews caused the following line to fail

https://github.com/pyviz/holoviews/blob/a010cfc1f4608bfdc4bafb3d1b43e4974b7d8085/holoviews/core/data/xarray.py#L394

The advice by xarray is to use [vectorised indexing](http://xarray.pydata.org/en/stable/indexing.html#vectorized-indexing)

**Comment by philippjfr** [comment]
Thanks @DancingQuanta. This is very high priority. I'll try to fix it tomorrow morning and follow up with a release shortly after.
