### ISSUE TITLE
Hide Holomap widget

### ISSUE THREAD

**Issue by julioasotodv** [pyviz/holoviews#3972]
Hi,

Imagine that I want to create a simple Holomap (just like in the docs):

```python
import numpy as np
import holoviews as hv
hv.extension('bokeh')

frequencies = [0.5, 0.75, 1.0, 1.25]

def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

curve_dict = {f:sine_curve(0,f) for f in frequencies}


hmap = hv.HoloMap(curve_dict, kdims='frequency')
hmap
```
As expected, it works:
![holoviews_holomap_widget](https://user-images.githubusercontent.com/20630819/65198636-1edf4e00-da84-11e9-8212-a4728262e09d.png)

My question is: is there any way to hide the widget? 

I know it sounds weird, but I plan to update the Curve shown in the holomap using an external event rather than manually touching the widget, therefore I don't really need it.

Thank you!

**Comment by jbednar** [comment]
You can use .select or .sample to pull out a single frame and display that, which would be simple if you use it with Panel.pyviz.org.

**Comment by julioasotodv** [comment]
Yes, but that was not my point, as I want to be able to select one Curve from the Holomap without a Bokeh/Jupyter server running (so no custom Python logic)

**Comment by philippjfr** [comment]
You could try to add some custom CSS to hide the widget. That said in the next major release the widgets will be entirely replaced with [Panel](https://panel.pyviz.org) widgets. At that point you should be able to hide the widgets by setting the width/height of the widget box to zero or something similar.

**Comment by julioasotodv** [comment]
@philippjfr that makes sense. In that case I will try again when Holomap widgets come directly from Panel (which would be great)

Thank you! Should I leave this issue open until the next major release?

**Comment by philippjfr** [comment]
No, let's close it. Those changes have already been merged and it's not a common use case that necessarily needs to be documented.

**Comment by jbednar** [comment]
@philippjfr , in that case can this already be achieved by simply putting the HoloMap into a Panel layout, which then uses Panel widgets already?  Seems like you could then select only the plot portion of the layout using indexing and display that.

**Comment by philippjfr** [comment]
>@philippjfr , in that case can this already be achieved by simply putting the HoloMap into a Panel layout, which then uses Panel widgets already?

Yes, you could do that.

>Seems like you could then select only the plot portion of the layout using indexing and display that.

No, this is not possible, because the widgets are required by panel to compute the state space of the HoloMap. You have to include the widgets and then hide them in some way.
