### ISSUE TITLE
Dynspread argument shape='circle' does not work

### ISSUE THREAD

**Issue by Mossi8** [pyviz/holoviews#3974]
Hello!

I have been tying for a while to spread the datashader points with a circular shape using the dynspread function, as follows:

dynspread(datashade(Nd,color_key=color_dic,aggregator=ds.count_cat('Gene'),min_alpha=1200),max_px=5,shape='circle')

However, this does not seem to be working.

Thank you!

**Comment by Mossi8** [comment]
Yes, sorry. I was trying to reproduce an example and I realised that I need to play with the threshold parameter in order to get the circle shape.

Sorry for inconveniences and thank you!

**Comment by philippjfr** [comment]
So it's working now?

**Comment by Mossi8** [comment]
Yes! It was just not clear to me that threshold is controlling the spreading. Thanks!

**Comment by jbednar** [comment]
Ah, I see! Yes, it's probably best to use `spread` to figure out the shape you like, and only then worry about the thresholding required for `dynspread`.
