### ISSUE TITLE
Support passing widgets to operations

### ISSUE THREAD

**Issue by jbednar** [pyviz/holoviews#3976]
HoloViews operations already accept Parameter values, making it simple to instantiate widgets and connect them to the operation arguments in a way that re-runs the operation when the widget updates:

```
import os, colorcet, holoviews as hv, panel as pn, numpy as np
from holoviews.operation.datashader import rasterize, shade, spread
from collections import OrderedDict as odict

hv.extension('bokeh')

points = hv.Points(np.random.rand(500,2))
cmaps  = odict([(n,colorcet.palette[n]) for n in ['fire', 'bgy', 'bgyw', 'bmy', 'gray', 'kbc']])

cmap = pn.widgets.Select(name='Colormap', options=cmaps)
shade(rasterize(points), cmap=cmap.param.value)
```
![image](https://user-images.githubusercontent.com/1695496/65262806-bec2c900-dad0-11e9-918e-572e5422cf6d.png)

Given how obscure the syntax for doing it is and that many people can otherwise use Panel without knowing anything about Param, it would be nice if people could simply pass the widget instead:

```
shade(rasterize(points), cmap=cmap)
```

**Comment by philippjfr** [comment]
This will have to wait for 1.13.0 since panel is not officially a dependency until then.
