### ISSUE TITLE
hv.HSpan; mix of hv.Area and hv.HLine

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoviews#3996]
It's like hv.HLine, but with area, and it's like hv.Area, but only needing to specify the y1/y2.

**Comment by ahuang11** [comment]
BoxAnnotation in Bokeh
https://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html

**Comment by shubham-IU** [comment]
In order to use hv.HSpan, I tried getting the master branch of holoviews, however, while setting the backend, i get the following error: 

`
Holoviews bokeh extension could not be imported, it raised the following exception: ModuleNotFoundError('No module named 'panel'')
`

Following are the versions of the packages I'm using:
bokeh = 1.3.4
holoviews = 1.13.0a11.post1+g1f46bb63

**Comment by philippjfr** [comment]
No you need to install the panel library which is now a dependency for holoviews.

**Comment by shubham-IU** [comment]
@philippjfr that worked, thanks!

**Comment by shubham-IU** [comment]
@philippjfr I am running into a problem when I try using VSPan in a HoloMap. The holomap contains  different overlays which are being indexed by a 'feature' key, each of the overlays has a VSpan element. If I try to plot only an individual overlay by `holomap[feature']`, it works and the VSpan is correctly displayed. However if try to plot the holomap itself, then I get the following error: `AttributeError: 'VSpan' object has no attribute 'get'`. Am I using VSpan incorrectly in some way?

**Comment by shubham-IU** [comment]
I tried to extract a simple reproducible example, but it seems to be something related to my data itself. If I just create a holomap with 2 value for `feature` parameter, it's working fine, but it doesn't work if I include all 3 values for the `feature`. I'll try looking into the data for the third feature, once I have it nailed down, I'll create an issue and link it here.

**Comment by philippjfr** [comment]
@shubham-IU Much appreciated.

**Comment by shubham-IU** [comment]
I haven't been able to get a reproducible example for holomap. However I ran into a similar error for dynamic map, which I can reproduce with the following example:
```
def plot(n):
    data = hv.Curve(np.arange(n)) 
    vspan = hv.VSpan(0, n/2)
    return data * vspan  
```

A holomap gives correct output:

```
hmap = hv.HoloMap({n:plot(n) for n in [1,2,3,4,5]}, kdims=['n'])  
hmap  
```

![Screenshot_20191016_181015](https://user-images.githubusercontent.com/47774371/66920174-6a175d00-f040-11e9-89e5-14e4b4562543.png)


However, dynamic map is producing output as follows:

```
dmap = hv.DynamicMap(plot, kdims=['n'])    
dmap = dmap.redim.values(n=((1,2,3,4,5)))    
dmap    
```

![Screenshot_20191016_181100](https://user-images.githubusercontent.com/47774371/66920179-6b488a00-f040-11e9-9eea-9fe89c2d6801.png)
