### ISSUE TITLE
IOPub data rate exceeded

### ISSUE THREAD

**Issue by rezapci** [pyviz/holoviews#3999]
With the 5.0.0b1 version of the Jupyter notebook server, I'm getting error messages instead of some of my csv 

> IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

~~~
7.6.1
Python 3.7.3
conda 4.7.12
anaconda Command line client (version 1.7.2)
~~~

**Comment by philippjfr** [comment]
That version of the notebook server is very old and more recent versions don't have this issue. There is also nothing we can do about it. You simply have to set the data rate limit as the error suggests:

```
jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000 
```
