### ISSUE TITLE
Bar Plot with more than 2 level of index is not supported ?

### ISSUE THREAD

**Issue by kkumawat25** [pyviz/holoviews#4004]
Hi, 
 As attached, why unstacked bar plot with more than 2 levels of indices does not work?
![Bar Plot](https://user-images.githubusercontent.com/54132236/65781222-df41f180-e168-11e9-92cc-7d774d27c467.png)

**Comment by poplarShift** [comment]
Works in holoviews: 
```
a = pd.DataFrame(dict(x=(np.arange(10)%2).astype(str), y=(np.arange(10)%3).astype(str), z=(np.arange(10)%4).astype(str), u=(np.arange(10)%5)))
a = hv.Dataset(a, ['x', 'y', 'z'], ['u'])

hv.Bars(a)
```

**Comment by philippjfr** [comment]
Duplicate of https://github.com/pyviz/holoviews/issues/2878
