### ISSUE TITLE
Issue in pipelining : holoviews /  bokeh extension / jupyter console ?

### ISSUE THREAD

**Issue by First6a** [pyviz/holoviews#4019]
Hi,

As a real newbee to data science, I'm doing my best to learn _holoviews_ basics through the excellent tutos available on the Net. 

By reference to the jupyter notebook "_04-Working_with_Tabular_Data.ipynb_" referenced in the tutos, I'm trying to inject my own data into this notebook as a (personal) learning method...

In the original notebook, the main example is based on plotting some 'curves' of a small hv.Dataset, shaped : (350, 5). Doing Fine.
Then, 
-when trying the same code with my own data (extracted IRL from a pd.DataFrame collected during a personal work), ten times bigger, shaped (6816, 12), 
-holoviews does not draw anything, but the empty slider referencing the external 'groupby' xdim... (screen capture attached)

Strangely enough, nothing is displayed where the curve is supposed to take place, an no error message of any sort given : Only a silent killing of the plotting request, but the empty slider. In due position, but desperately empty...

I suspected a memory limitation issue, then reduced the size of the my data, and eventually obtained the correct figure (no meaning, but correctly drawn), with all the details and a functional slider, with a Dataset shaped (678, 12), that is 63.7+ KB memory usage, i.e. roughly the size of 10% of my complete data (6815 rows, 12 columns, 639.1+KB memory usage).

I tried with 3 different browsers (Firefox, Safari, Opera), with the exact same observed reproductible limitation: up to 678 observations in the dataset, everything's ok. 
Add only one more row to the dataset, and then : no figure,empty slider. Every time. Memory usage difference on the limit = 0.1 KB 
(678 observations dataset uses 63.6 KB, and is ok.)
(679 observations dataset uses 63.7KB, and the curve is not plotted.)

Then do I suspect a hidden issue in some data volumes parameters incompatibility between bokeh (hv extension) and/or the browser (any of the 3 I used, in fact) and/or jupyter notebook server.

Hereunder, you'll find my system specs : 

-holoviews 1.12.3
-bokeh 1.3.4
-jupyter notebook 6.0.1
-anaconda Command line client 1.7.2
-python 3.6.6
-Mac OS 10.14.6
-Firefox 69.0.1 (64bits)

While I do realize that a 6000+ observations dataset is ten time bigger than a toy example given for the sake of simplicity, I do imagine the impressive power of holoviews /PyViz is by conception adapted to big data, 6000 observations dataset being a rather small-big-one, and then there must be some glitch in my system configuration (that I need help to detect, if any). 

And/or, if something in the assembly line holoviews-bokeh-jupyter does not fit, bad luck...

Can you help me ? 
Please ! 😅

If so, many thanks in advance.

First6a

(Screen-captures attached)  
<img width="1280" alt="Capture d’écran 2019-10-03 à 02 03 44" src="https://user-images.githubusercontent.com/35047371/66090305-1a865b00-e583-11e9-8975-785e4d5835f7.png">
<img width="1280" alt="Capture d’écran 2019-10-03 à 02 04 43" src="https://user-images.githubusercontent.com/35047371/66090306-1b1ef180-e583-11e9-838c-c7ffe8d5bda3.png">
<img width="1280" alt="Capture d’écran 2019-10-03 à 02 05 20" src="https://user-images.githubusercontent.com/35047371/66090307-1b1ef180-e583-11e9-99b5-39215885f920.png">
<img width="1280" alt="Capture d’écran 2019-10-03 à 02 05 51" src="https://user-images.githubusercontent.com/35047371/66090308-1b1ef180-e583-11e9-8531-c1da7322257a.png">
<img width="1280" alt="Capture d’écran 2019-10-03 à 02 06 12" src="https://user-images.githubusercontent.com/35047371/66090309-1b1ef180-e583-11e9-87a5-8bf989927812.png">
<img width="1280" alt="Capture d’écran 2019-10-03 à 02 06 38" src="https://user-images.githubusercontent.com/35047371/66090311-1bb78800-e583-11e9-91fa-44efe8ed2d5e.png">
<img width="1280" alt="Capture d’écran 2019-10-03 à 02 07 38" src="https://user-images.githubusercontent.com/35047371/66090312-1bb78800-e583-11e9-9331-77ae16de32ea.png">
<img width="1280" alt="Capture d’écran 2019-10-03 à 02 09 15" src="https://user-images.githubusercontent.com/35047371/66090313-1bb78800-e583-11e9-94e4-82a88b5202b9.png">

**Comment by poplarShift** [comment]
Welcome to the HoloViz universe! Could you please provide a **minimal working example** code for people  to copy-paste? (Also note that for general support as opposed to bug reports, stackoverflow is a better place, but I didn't quite understand which of the two this is.)

**Comment by First6a** [comment]
Thank you for your message.


Thank you for your message.

I posted minutes ago the minimal working example yopu requested, on the GitHub public repository ["First6a/lost-in-translation".](https://github.com/First6a?tab=repositories).
The example is contained in the notebook "Minimal_Working_Example.ipynb", with the joint file attached, "homes.csv".
Should you need any other info, let me know.
And once again, Thank you for your help.

**Comment by poplarShift** [comment]
Maybe this helps: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by First6a** [comment]
My understanding is

1-the minimal working example I posted, while reproducible, is too long, and
2-StackOverFlow is probably a better place for this issue.

Then I'll do that.
Thank you anyway for your help.
