### ISSUE TITLE
Want Print Option for my Holoviews Plot.

### ISSUE THREAD

**Issue by sameerCoder** [pyviz/holoviews#4057]
Hi,
As like toolbar options - save, zooom in , zoom out , pan Etc .
Same way i am thinking to put Print options in toolbar . 
How i can add Print option in Holoviews plot so that it can capture the current view of plot as well, As every Web Browser allow Print option.

**Comment by jbednar** [comment]
A new tool for the Bokeh toolbar would be a request for [Bokeh](https://github.com/bokeh/bokeh), not holoviews.
