### ISSUE TITLE
PointerXY does not account for zooming and panning

### ISSUE THREAD

**Issue by ea42gh** [pyviz/holoviews#4075]
```
import datashader as ds
from bokeh.models import HoverTool

hover = HoverTool(tooltips=[ ("X", "$x{0,0.000}"), ("Y","$y{0,0.00}"), ("Z","@image{0,0.000}"),  ("S","@S{0,0.000}")])

x = np.arange(start=0, stop=100, step=1)
y = np.arange(start=0, stop=100, step=0.001)
z = np.random.normal( size=(len(y),len(x)))
s = np.random.normal( size=len(x)) # same value s for each y value

data = {'X': x, 'Y' : y, 'Z' : z, 'S' : np.lib.stride_tricks.as_strided( np.copy(s[::-1]), (len(y),len(x)),(0,64//8) )}

h_i =\
rasterize( hv.Image(data, ['X', 'Y'], ['Z','S'])\
                 .opts( colorbar=True, colorbar_position='left',
                        width=700, invert_xaxis=True, invert_yaxis=True, xticks=5, tools=[hover],
                        clim=(z.min(),z.max())),
               aggregator=ds.max(None)
             )

loc_stream = hv.streams.PointerXY(x=0, y=0, source=h_i)

def loc_table(x,y):
    nx = int( np.round(x,0))
    ny = int( np.round(y,0))
    z_ = np.round(h_i.data[()].data['Z'][ny,nx],2)
    s_ = np.round(h_i.data[()].data['S'][0,nx],4)
    
    return hv.Table(data=pd.DataFrame({ 'Parameter':['x','y', 'Z', 'S'],'Value':[nx,ny,z_,s_]}))

h_t =\
hv.DynamicMap( loc_table, streams=[ loc_stream ]).opts(width=200)
(h_i+h_t).cols(2)
```
When zooming and panning, the Hovertool returns the correct values,
the PointerXY stream does not.
------------------
additional edit 3 days later:

one reason seems to be that the PointerXY stream stops updating.
Additional panning and/or moving the mouse a sufficient distance (? can't quantify this)
can restore the table update

**Comment by ea42gh** [comment]
http://www.holoviews.org/reference/streams/bokeh/PointerXY.html#bokeh-gallery-pointerxy

The example in the reference gallery fails the moment the pointer is moved outside the image

**Comment by ea42gh** [comment]
Run the code,
pan the image
the table will update for only part of the displayed image,
not all of it.

**Comment by philippjfr** [comment]
I can't reproduce any bug here. When you leave the image the callback in your example and the callback in the example you pointed to throw errors because you are outside the bounds of the image, which prevents the table from being updated. As long as you are inside the image bounds the table updates fine for me.

**Comment by philippjfr** [comment]
I see now what you mean that it only works for part of the image but that's again because your callback is not indexing into the data structure correctly. You are doing integer indexing into the DataArray, and when you drag the image around the size of the image no longer matches the size you expect.

**Comment by philippjfr** [comment]
This is what you wanted I believe

```python
def loc_table(x,y):
    nx = int( np.round(x,0))
    ny = int( np.round(y,0))
    z_ = np.round(h_i.data[()].data['Z'].sel(X=nx, Y=ny, method='nearest'),2)
    s_ = np.round(h_i.data[()].data['S'].sel(X=nx, Y=ny, method='nearest'),4)
    # OR
    z_ = np.round(h_i.data[()][x,y]['Z'],2)
    s_ = np.round(h_i.data[()][x,y]['S'],4)
    
    return hv.Table(data=pd.DataFrame({ 'Parameter':['x','y', 'Z', 'S'],'Value':[nx,ny,z_,s_]}))
```

**Comment by ea42gh** [comment]
I see!  Thank you!!!!
