### ISSUE TITLE
framewise=True in HoloMap with Overlay plots doesn't work

### ISSUE THREAD

**Issue by sfcaracciolo** [pyviz/holoviews#4090]
Hi,

I'm trying to autoadjust axis in a HoloMap with framewise=True. In case of used a single hv.Curve() woks fine, but when I used hv.Curve()*hv.Curve() framewise hasn't efect.

In the example, we can see that 3 first cases works, but fourth doesn't work. 

![hv-issue](https://user-images.githubusercontent.com/41028670/68528951-e61b6280-02d7-11ea-8e73-110989806213.gif)

Is it really an issue or I have to modified the code?

Thanks!

**Comment by DancingQuanta** [comment]
You could try this
```
from holoviews import opts

holomap.opts(opts.Overlay(framewise=True))
```
where `holomap` is the `HoloMap` object you have created.

**Comment by DancingQuanta** [comment]
For more details about `holoviews.opts` see [here](http://holoviews.org/user_guide/Customizing_Plots.html)

**Comment by sfcaracciolo** [comment]
> You could try this
> 
> ```
> from holoviews import opts
> 
> holomap.opts(opts.Overlay(framewise=True))
> ```
> 
> where `holomap` is the `HoloMap` object you have created.

Thank you for response!. I tried this:
```
from holoviews import opts
N = 5
xs = [np.random.rand(100)*(i+1) for i in range(N)]
d = {'x%d'%i: hv.Curve(x)*hv.Curve(x+1) for i, x in enumerate(xs)}
p = hv.HoloMap(d, kdims='coord')
p.opts(opts.Overlay(framewise=True))
```

But, same previous result. Any other idea? :)

**Comment by splintersu** [comment]
This is very useful, thank you
