### ISSUE TITLE
Docker image for local testing

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#440]
Until fairly recently, the HoloViews developers (i.e both of us!) ran notebook tests on Linux. Travis runs on Linux too so all was well.

However, we have since switched to Mac OS, we haven't been able to run all the nosetests and notebook tests on our local machines due to odd, OS specific changes in matplotlib output. We've been relying on Travis which has worked ok so far.

As we don't want to save OS specific test data so the best solution I can propose is to use docker on Mac OS. This is a good idea for several reasons:
1. Things can change even on linux (e.g changes in core libs).
2. The website building process now uses a docker container on Linux. We can match the specifications in a new docker image so hopefully this image matches Travis. Then local testing, Travis and website building all happen in identical/similar environments.
3. On MacOS docker uses virtualization but it appears as a more lightweight solution than say VirtualBox.  All we need for this application is a command-line and not a GUI which is something that docker provides.
4. Docker would be a good way to distribute our test/website building environment to anyone who wants it (e.g new devs). We could even upload a Docker image to DockerHub someday...

**Comment by jbednar** [comment]
vagrant should work for this...

**Comment by jlstevens** [comment]
I've never used vagrant. Got any ideas of the pros/cons versus using docker? I've personally never used vagrant before so I don't know what the user experience is like...

**Comment by philippjfr** [comment]
Vagrant and docker do fairly similar I think, except vagrant always uses a virtual machine to run the environment. Vagrant now also has support for docker images, but there's probably no point in using both. Using docker should be fine for now. If we ever decide we should also have OSX and Windows testing environments we can come back to vagrant.

**Comment by jbednar** [comment]
Basically "vagrant up" to launch the virtual machine, then use ssh to ssh into it and do your business, all nicely from the command line.So it can easily just look like doozy always has.  Docker might be more lightweight and achieve the same.

**Comment by jlstevens** [comment]
I agree with @philippjfr that we can stick with docker for now although Vagrant does look interesting (as you say, for testing on other platforms). I will just note that on Linux docker is native but on Mac OS docker also uses VirtualBox in the background just like Vagrant does.

**Comment by philippjfr** [comment]
Given our experiences is this still something you want @jlstevens?

**Comment by jlstevens** [comment]
I believe I saw something about a docker image available that allows recreation of the Travis testing environment. I'm not too hot on docker but having a way of debugging Travis locally might be very helpful...

What do you think?

**Comment by philippjfr** [comment]
Agreed, I think Travis might provide something like it already.

**Comment by philippjfr** [comment]
I don't think this is something we should provide, travis already provides docker images.
