### ISSUE TITLE
Additional build target for buildbot

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#441]
Currently buildbot automatically merges the notebook test data appropriately when PRs are merged. Updating test data due to changes implemented directly on master is not easy to do yet. This isn't a big issue as we are moving to a PR based workflow so commits direct to master are becoming much rarer.

I propose to add a builder to buildbot (for use by devs only with buildbot credentials) for updating the test data on master (i.e by forcing a build). This should be fairly quick to implement as the steps are just a fairly simple variation of the current `merge` builder (which handles PR merges only).

**Comment by jbednar** [comment]
Suppirting

**Comment by jbednar** [comment]
Damned phone! 

Supporting this seems OK, but if a change is going to affect the tests, it probably should be in a PR for that

**Comment by jbednar** [comment]
Grr! 

for that reason alone.

**Comment by jlstevens** [comment]
Would you like me to clean up this thread after your phone issues- we can delete comments if appropriate! :-)

I'm not sure a PR makes that much sense. This involves changes to buildbot which isn't (yet) tracked by this repository (and I'm not sure it should be). In addition, it is only going to affect test data contents in terms of how easy it is to regenerate and ensure new commits are being tested against the latest version of the reference data.

If our testing code/infrastructure instructions should go anywhere, it is probably on the master branch of the holoviews-data repository (censoring out our private tokens as appropriate).

**Comment by jbednar** [comment]
I'm not sure we're talking about the same thing.  I just mean, if someone makes a change to holoviews itself that changes the test results, I'd think that ought to be in a PR where someone can check that it's ok, rather than as a direct commit.

**Comment by jlstevens** [comment]
Ah right! :-)

I agree and  had misunderstood what you meant there. That is exactly why setting up this builder isn't a big priority right now but it would be nice to have, just in case someone makes a commit to master that they think is harmless but does in fact change the test data somehow.

**Comment by jlstevens** [comment]
I've changed the issue title as there is at least two other simple targets I would like to see soon:

* Flakes testing with flake8.
* Possible PEP8 compliance check.

I wouldn't expect these to pass most of the time but I do want flakes to pass before releases. I'm not certain of the value of the PEP8 one as we certainly have a couple of our own conventions that aren't PEP8 compliant.

I'll work on getting the former running (should be quick!) as I want to check flakes is passing in order to release 1.4.2 tomorrow.

**Comment by jbednar** [comment]
flake8 would be great, and I would think you could do PEP8 as long as it allows a finite set of checks to be omitted.  It would be perfect to say that it's PEP8-compliant, except for X and Y.

**Comment by jlstevens** [comment]
I agree that flake8 is important. PEP8 compliance (excluding a few things) would be nice but we don't want to find ourselves wasting time changing things due to style issues.

I'll also make a note to myself that I need to update the instructions on the buildbot page (outdated). This is something I'll do at the same time as getting flake8 configured.

**Comment by jlstevens** [comment]
I've added the ``flakes`` and ``pylint`` builders to buildbot:

http://buildbot.holoviews.org:8010/waterfall

**Comment by philippjfr** [comment]
This issue is pretty stale and I think we should move away from buildbot rather than migrating more tasks to it. The PR based workflow has been working well for years now as well so I see no need for this issue.
