### ISSUE TITLE
Notebook archive should support interactive holomaps

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#449]
Right now, HoloMaps are exported as a single frame. There are several issues with exporting holomaps in archives:
- HoloMaps can take a lot more disk space than static images.
- They are harder to test if we want to use archive testing in the future.
- Saving out separate HTML+JS for our javascript widgets is hard to include in `index.html` due to the same origin policy.

Nonetheless, we now have static HTML export and it would be nice to be able to use it. Ideally we could have standalone HTML files that display nicely by themselves but that can also be linked into an overall notebook document. Unfortunately, this looks like it might be quite tricky to get right.

Lastly, this might link to the proposal of storing the main holomap data in JSON files....

**Comment by philippjfr** [comment]
I don't really understand the proposal here, we can and do support HoloMap exports now, but maybe not in archives? Please close if you think this has been addressed.

**Comment by jlstevens** [comment]
I know we can export standalone html files for holomaps now but I would need to check how this applies in the context of archives.
