### ISSUE TITLE
Support packed value dimensions in Grid interfaces

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#550]
This issue is a reminded to re-introduce a feature that didn't make it into PR #542: the ability to pack value dimensions into a single array in `GridColumns`. This PR is going to be merged to master shortly.

This was prototyped using a dictionary key called `'vdims'` but I think it would be nicer to allow tuple keys containing the actual value dimension names e.g `('height', 'pressure', 'temperature')`.

**Comment by philippjfr** [comment]
Can't see this making it into 1.7, postponing.

**Comment by jlstevens** [comment]
Agreed.
