### ISSUE TITLE
Issue warning when key dimensions redundant

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#726]
Right now sliders don't work when key dimensions are redundant (for good reasons) but this isn't always obvious looking at the output. I've often wondered why sliders don't appear to work in such a case.

It might be useful to issue a warning to explain why sliders aren't behaving as you might expect. Something like 'Redundant key dimensions dectected: Data exploration with sliders will be limited'.

**Comment by philippjfr** [comment]
I think it might sometimes just so happen that the dimensions are redundant so a warning doesn't seem appropriate. Only thing  I can imagine is some visual indicator, and there is little point implementing that for our current widgets.

**Comment by jbednar** [comment]
Even if it does sometimes just happen that dimensions are redundant, if we are generating widgets that don't work, it seems like there should be a warning that explains why.  I can't think of a case where a user wouldn't want to know why the widgets don't work, but you seem to be imagining one?

**Comment by philippjfr** [comment]
>I can't think of a case where a user wouldn't want to know why the widgets don't work, but you seem to be imagining one?

Yes, this is absolutely deliberate because the alternative is **much** worse, say you have keys (1, 2), (2, 4), (3, 6), so you get two sliders. Currently changing slider A will update slider B, while Slider B will be locked. If you select value 2 on slider A it automatically updates slider B to value 4. The alternative would be two completely independent sliders where combinations (1, 4), (1, 6), (2, 2), (2,6) and (3, 2), (3, 4) all result in empty plots.

**Comment by jbednar** [comment]
I'm not arguing that that behavior should change, just that when it happens, the user would want a message that says what's going on.  I've found it extremely unintuitive before, with no idea what I should look into to get an explanation, and if there were a warning message that explained what was happening and explained how to turn off the message if that's what I really wanted to do, I think I would have been far less bewildered.

**Comment by jlstevens** [comment]
I agree that a warning is probably appropriate, just to offer some explanation to the user. As the behavior may be intentional, it needs to be a warning that can be disabled.

**Comment by philippjfr** [comment]
We decided to no longer have special support for non-orthogonal dimensions since widgets are now handled by Panel.
