### ISSUE TITLE
Support vertical layout of widgets

### ISSUE THREAD

**Issue by philippjfr** [pyviz/holoviews#805]
This has been a recurring feature request. Rather than laying out the widgets next to the plot it should be possible to place the widgets below the actual plot instead. This arrangement is a lot more suitable for pages that have very little space and it should not be hard to do with a small amount of css. The main question is how the user can choose between the vertical and horizontal widget arrangement.

**Comment by jbednar** [comment]
I would vote for allowing all the location options (N,S,E,W) for the widget box -- all of those are valid arrangements, and each is useful sometimes.  

There's also the issue of how the widgets are laid out in the box -- for E and W locations, laying them out in a column is probably the only reasonable choice.  But for boxes in the N or S locations, 2-3 sliders lay out well horizontally, while any more than that has to be vertical, and in some cases people will want them all just to be in a single vertical column as for paramnb's Widgets() class.  So I would think there are two parameters that would be needed:

**widget_location:** N,S,E,W (or left, right, above, below, or whatever you want to call them) (default E)

**widget_layout:** row, column (default column)

**widget_cols:** 1, 2, or 3 (default 1)

**Comment by jlstevens** [comment]
Sounds like options for the output magic. I would vote to tab complete 'left', 'right', 'top' and 'bottom'. 

In addition, I think ``widget_cols`` might be sufficient (default 1) where you could just set a very high number if you always want a row layout.

**Comment by jbednar** [comment]
Sounds good.  Top vs above is a subtle distinction,  about whether it is higher or highest,  but that us up to you.

**Comment by jordansamuels** [comment]
+1 ability to move widgets to top or bottom of HoloMap.

Also remember some gitter discussion:

> Wojciech Jaśkowski @wjaskowski Jul 04 08:52
How to change the position of HoloMap widgets? (Normally they are rendered on the right but somehow I accidentally changed them to be at the bottom once)

> Philipp Rudiger @philippjfr Jul 04 08:52
They are on the bottom when the CSS is not applied (e.g. if you delete the output of the cell where hv.extension is loaded)
Currently the position isn't easily configurable, although there are workarounds with some CSS.

I'd love to have official support; if difficult, I'd like to see the CSS workaround.

**Comment by wjaskowski** [comment]
Yes! Widgets on the right leave not enough space for the actual plots.

**Comment by jvivian** [comment]
+1 — I've been wanting to build static pages that use Holomaps.

![image](https://user-images.githubusercontent.com/7576256/34959694-7a38cecc-f9ec-11e7-8106-f122bf3e7f1b.png)

**Comment by philippjfr** [comment]
Minor update, for dynamic content this is now all possible using http://panel.pyviz.org/. And we have plans to add support for exporting HoloMaps to panel in the near future.

**Comment by philippjfr** [comment]
This is now supported on master.

**Comment by basnijholt** [comment]
Where can I find documentation on how to do this in v1.13?

**Comment by philippjfr** [comment]
At some point along the way we lost the renderer/output docs. The easiest way of setting this is:

```python
hv.output(widget_location=['left', 'bottom', 'right', 'top', 'top_left', 'top_right', 'bottom_left',, 'bottom_right', 'left_top', 'left_bottom', 'right_top', 'right_bottom'])
```
